#!/bin/bash
#SBATCH --job-name=saga_e4
#SBATCH --time=24:00:00
#SBATCH --partition=a100
#SBATCH --gres=gpu:a100:4
#SBATCH --cpus-per-task=8
#SBATCH --ntasks-per-node=4
#SBATCH --array=0-2
#SBATCH --output=/home/vault/iwi5/iwi5359h/SAGA/e4/logs/e4_%A_%a.log
#SBATCH --error=/home/vault/iwi5/iwi5359h/SAGA/e4/logs/e4_%A_%a.err

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║ SUPERSEDED (TASK-09) — DO NOT SUBMIT.                                    ║
# ║ Any number this script produced is biased (bug B4: mIoU counted the 255  ║
# ║ ignore pixels into every class union) and its registers backbone was     ║
# ║ broken (bug B6). Its paths.yaml is also a stale copy of the e6           ║
# ║ fine-grained one (no ADE20K entries at all).                             ║
# ║ Use instead, ONE COMMAND PER LINE (a glob/brace form would run only the  ║
# ║ first script and pass the rest as arguments):                            ║
# ║     bash scripts/submit_seg_vitb_baseline_s1.sh                          ║
# ║     bash scripts/submit_seg_vitb_saga_s1.sh                              ║
# ║     bash scripts/submit_seg_vitb_registers_s1.sh                         ║
# ║ (generated by scripts/gen_dense_jobs.py from configs/dense_matrix.yaml)  ║
# ║ after the smoke:  sbatch scripts/jobs/dense_smoke_seg.sbatch             ║
# ║ Kept only for provenance — segmentation/tools/train.py has been          ║
# ║ rewritten, so the --config/--id/--paths invocation below no longer       ║
# ║ exists.                                                                  ║
# ╚══════════════════════════════════════════════════════════════════════════╝
#
# ── E4 Segmentation — 3 variants, 80 epochs each ─────────────────────────────
#
# Submit all:    sbatch --array=0-2 segmentation/scripts/e4_train_alex.sh
# Submit one:    sbatch --array=2   segmentation/scripts/e4_train_alex.sh
# Auto-resume:   resubmit same command after 24h timeout
#
# Variant mapping:
#   0 = ViT-B_baseline_seg
#   1 = ViT-B_registers_seg
#   2 = ViT-B_SAGA_seg

source /home/hpc/iwi5/iwi5359h/my_repos/SAGA/segmentation/scripts/env_alex.sh
source /home/hpc/iwi5/iwi5359h/my_repos/SAGA/segmentation/scripts/stage_ade20k.sh

cd $CODE_ROOT

MASTER_PORT=$((29920 + SLURM_ARRAY_TASK_ID))

VARIANT_NAMES=(
    "ViT-B_baseline_seg"
    "ViT-B_registers_seg"
    "ViT-B_SAGA_seg"
)

VARIANT_NAME=${VARIANT_NAMES[$SLURM_ARRAY_TASK_ID]}
LAST_CKPT=/home/vault/iwi5/iwi5359h/SAGA/e4/checkpoints/${VARIANT_NAME}/last.pth
RESUME_ARG=""

echo "======================================================"
echo "  SAGA E4 — $VARIANT_NAME"
echo "  Node: $SLURMD_NODENAME  |  Port: $MASTER_PORT"
echo "  $(date)"
echo "======================================================"

if [ -f "$LAST_CKPT" ]; then
    echo "  Resuming from: $LAST_CKPT"
    RESUME_ARG="--resume $LAST_CKPT"
else
    echo "  Starting from scratch"
fi

stage_ade20k

echo "======================================================"
echo "  Starting training  $(date)"
echo "======================================================"

/home/vault/iwi5/iwi5359h/envs/saga/bin/python -m torch.distributed.run \
    --nproc_per_node=4 \
    --nnodes=1 \
    --node_rank=0 \
    --master_addr=localhost \
    --master_port=$MASTER_PORT \
    segmentation/tools/train.py \
        --config    segmentation/configs/variants.yaml \
        --id        $SLURM_ARRAY_TASK_ID \
        --paths     segmentation/configs/paths.yaml \
        --data_root $DATA_ROOT \
        $RESUME_ARG

if [ $? -ne 0 ]; then
    echo "ERROR: $VARIANT_NAME failed."
    cleanup_ade20k
    exit 1
fi

echo ""
echo "======================================================"
echo "  $VARIANT_NAME DONE — $(date)"
echo "======================================================"

cleanup_ade20k