#!/usr/bin/env python3
"""
scripts/gen_slurm_chain.py
==========================
TASK-05 A3: generate, per run of the e2r matrix, a SLURM job file plus a
submit script that chains N copies with --dependency=afterany, every job
executing the SAME `train.py --resume auto` command (the trainer
fresh-starts on the first job and resumes on every successor — idempotent
by TASK-05 design).

    python scripts/gen_slurm_chain.py [--matrix configs/e2r_matrix.yaml] \
        [--out-dir scripts]

Emits: scripts/jobs/e2r_<run_id>.sbatch and scripts/submit_<run_id>.sh.
The #SBATCH header and environment/staging lines copy the known-good
patterns of classification/scripts/e2_train_alex.sh and How to Run.md.
"""

import argparse
from pathlib import Path

import yaml

# copied from the legacy e2 Alex scripts (How to Run.md §6); the master
# port is unique per run to avoid NCCL conflicts on shared nodes
JOB_TEMPLATE = """\
#!/bin/bash
#SBATCH --job-name={run_id}
#SBATCH --partition=a100
#SBATCH --gres=gpu:a100:4
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=8
#SBATCH --ntasks-per-node=4
#SBATCH --output=/home/vault/iwi5/iwi5359h/SAGA/logs/{run_id}_%j.log
#SBATCH --error=/home/vault/iwi5/iwi5359h/SAGA/logs/{run_id}_%j.err

# GENERATED by scripts/gen_slurm_chain.py -- do not edit by hand.
# The same command below fresh-starts and resumes (--resume auto), so this
# job file is submitted N times in an afterany dependency chain and each
# incarnation simply continues from ckpt/last.pth (<=1 epoch lost per kill).

source /home/hpc/iwi5/iwi5359h/my_repos/SAGA/scripts/env_alex.sh
source /home/hpc/iwi5/iwi5359h/my_repos/SAGA/scripts/stage_imagenet.sh
cd $CODE_ROOT

stage_imagenet

/home/vault/iwi5/iwi5359h/envs/saga/bin/python -m torch.distributed.run \\
    --nproc_per_node=4 \\
    --nnodes=1 \\
    --node_rank=0 \\
    --master_addr=localhost \\
    --master_port={port} \\
    classification/tools/train.py \\
        --matrix configs/e2r_matrix.yaml \\
        --run {run_id} \\
        --data_root $STAGE_DIR \\
        --resume auto
STATUS=$?

cleanup_imagenet
exit $STATUS
"""

SUBMIT_TEMPLATE = """\
#!/bin/bash
# GENERATED by scripts/gen_slurm_chain.py -- submit the {n}-job chain for
# {run_id} ({est}).
#
# Every job carries --dependency=singleton (job name == run_id), so SLURM
# never runs two jobs of this run at once — re-running this script later
# EXTENDS the run safely: the new jobs queue behind whatever is still
# running/pending, and --resume auto continues from ckpt/last.pth (a
# finished run exits quickly, so surplus jobs are harmless).
set -eu
cd "$(dirname "$0")/.."

jid=$(sbatch --parsable --dependency=singleton scripts/jobs/{run_id}.sbatch)
echo "submitted {run_id} job 1: $jid (singleton)"
for i in $(seq 2 {n}); do
    jid=$(sbatch --parsable --dependency=singleton,afterany:$jid scripts/jobs/{run_id}.sbatch)
    echo "submitted {run_id} job $i: $jid (singleton + afterany chain)"
done
"""


def main():
    parser = argparse.ArgumentParser(
        description="Generate SLURM dependency chains for the e2r matrix.")
    parser.add_argument("--matrix", default="configs/e2r_matrix.yaml")
    parser.add_argument("--out-dir", default="scripts")
    parser.add_argument("--base-port", type=int, default=29700)
    args = parser.parse_args()

    matrix = yaml.safe_load(open(args.matrix))
    chain = matrix.get("chain", {})
    out_dir = Path(args.out_dir)
    jobs_dir = out_dir / "jobs"
    jobs_dir.mkdir(parents=True, exist_ok=True)

    for i, (run_id, run) in enumerate(sorted(matrix["runs"].items())):
        n = int(chain.get(run["arch"], 2))
        port = args.base_port + i
        job_path = jobs_dir / f"{run_id}.sbatch"
        job_path.write_text(
            JOB_TEMPLATE.format(run_id=run_id, port=port),
            encoding="utf-8", newline="\n")

        est = f"{n}x24h walltime, arch {run['arch']}"
        submit_path = out_dir / f"submit_{run_id}.sh"
        submit_path.write_text(
            SUBMIT_TEMPLATE.format(run_id=run_id, n=n, est=est),
            encoding="utf-8", newline="\n")
        print(f"{run_id}: chain of {n} (port {port}) -> "
              f"{submit_path.name} + jobs/{job_path.name}")

    print(f"\n{len(matrix['runs'])} chains generated. Submit with e.g.:")
    print("  bash scripts/submit_e2r_vits_nomix_baseline_s1.sh")


if __name__ == "__main__":
    main()
