#!/usr/bin/env python3
"""
scripts/gen_dense_jobs.py
=========================
TASK-09: generate, per run of configs/dense_matrix.yaml, a SLURM job file
plus a submit script that chains N copies with --dependency=singleton,afterany
— every job executing the SAME `--resume auto` command (the trainers
fresh-start on the first job, resume on every successor, and a surplus job
exits in seconds via the completion fast-path).

    python scripts/gen_dense_jobs.py [--matrix configs/dense_matrix.yaml]

Emits, byte-for-byte deterministically:
    scripts/jobs/<run_id>.sbatch          6 runs
    scripts/submit_<run_id>.sh            6 chains
    scripts/jobs/dense_smoke_det.sbatch   50 iters + one capped eval
    scripts/jobs/dense_smoke_seg.sbatch   ... plus the on-device pytest

Every SLURM element is copied from committed, production-proven files:
the #SBATCH header from scripts/jobs/e2r_*.sbatch (How to Run.md §6:
partition a100, gpu:a100:4, 24 h wall, cpus-per-task 8, ntasks-per-node 4,
logs under $OUT_ROOT/logs), and the env + staging lines from the committed
detection/scripts/{env_alex,stage_coco}.sh and
segmentation/scripts/{env_alex,stage_ade20k}.sh (which is where the COCO and
ADE20K zip paths live — nothing here is invented).

Master ports: this file uses 29850..29855 for the six runs and 29860/29861
for the smokes. Every other committed launcher was enumerated before picking
that block, INCLUDING the ones whose port is computed from the array index
(`$((BASE + SLURM_ARRAY_TASK_ID))`), which a plain grep for a literal port
misses:
    29500 + 0..15  scripts/e1_variants{,_alex}.sh
    29600 + 0..8   classification/scripts/e2_train_alex.sh
    29698, 29699   scripts/saga_e2r{,_registers}_smoke.sh
    29700 + 0..2   classification/scripts/e2_sanity_alex.sh
    29700..29709   scripts/jobs/e2r_*.sbatch
    29750..29753   scripts/jobs/e2r_* (TASK-07 additions)
    29800 + 0..2   classification/scripts/e2_nomix_alex.sh   <-- the reason
                   this file no longer starts at 29800
    29900          detection/scripts/e3_sanity_alex.sh
    29910 + 0..2   detection/scripts/e3_train_alex.sh
    29920 + 0..2   segmentation/scripts/e4_{train,sanity}_alex.sh
tests/test_task09_dense.py re-derives that whole table from the repo and
asserts the dense ports are disjoint from it.
"""

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]

COCO_TRAIN_COUNT = 118287     # the count stage_coco.sh prints as expected
ADE_TRAIN_COUNT = 20210       # the count stage_ade20k.sh prints as expected

DET_COUNT_GUARD = f"""N_TRAIN=$(find $STAGE_DIR/train2017 -name "*.jpg" | wc -l)
if [ "$N_TRAIN" -ne {COCO_TRAIN_COUNT} ]; then
    echo "ERROR: train2017 has $N_TRAIN images, expected {COCO_TRAIN_COUNT}" >&2
    cleanup_coco
    exit 1
fi"""

SEG_COUNT_GUARD = f"""N_TRAIN=$(find $DATA_ROOT/images/training -name "*.jpg" | wc -l)
if [ "$N_TRAIN" -ne {ADE_TRAIN_COUNT} ]; then
    echo "ERROR: ADE20K training has $N_TRAIN images, expected {ADE_TRAIN_COUNT}" >&2
    cleanup_ade20k
    exit 1
fi"""

TASK_SETUP = {
    "detection": {
        "env": "detection/scripts/env_alex.sh",
        "stage": "detection/scripts/stage_coco.sh",
        "stage_fn": "stage_coco",
        "cleanup_fn": "cleanup_coco",
        "data_root": "$STAGE_DIR",
        "entry": "detection/tools/train.py",
        "epochs_note": "25 epochs",
        # stage_coco.sh enforces only the VAL count; a truncated train
        # extraction would otherwise train silently on partial data
        "count_guard": DET_COUNT_GUARD,
    },
    "segmentation": {
        "env": "segmentation/scripts/env_alex.sh",
        "stage": "segmentation/scripts/stage_ade20k.sh",
        "stage_fn": "stage_ade20k",
        "cleanup_fn": "cleanup_ade20k",
        # stage_ade20k() exports DATA_ROOT=$STAGE_DIR/ADEChallengeData2016
        "data_root": "$DATA_ROOT",
        "entry": "segmentation/tools/train.py",
        "epochs_note": "80 epochs",
        "count_guard": SEG_COUNT_GUARD,
    },
}

CODE_ROOT = "/home/hpc/iwi5/iwi5359h/my_repos/SAGA"
PYTHON = "/home/vault/iwi5/iwi5359h/envs/saga/bin/python"
LOG_DIR = "/home/vault/iwi5/iwi5359h/SAGA/logs"

JOB_TEMPLATE = """\
#!/bin/bash
#SBATCH --job-name={run_id}
#SBATCH --partition=a100
#SBATCH --gres=gpu:a100:4
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=8
#SBATCH --ntasks-per-node=4
#SBATCH --dependency=singleton
#SBATCH --output={log_dir}/{run_id}_%j.log
#SBATCH --error={log_dir}/{run_id}_%j.err

# GENERATED by scripts/gen_dense_jobs.py -- do not edit by hand.
# TASK-09 {task} run {run_id} ({variant} backbone).
# --dependency=singleton is in the HEADER as well as on submit_<run>.sh's
# sbatch line (job-name == run_id, which is what singleton keys on), so
# adding one more job by hand -- `sbatch scripts/jobs/{run_id}.sbatch`, the
# documented way to extend a chain that ran out of jobs -- still cannot run
# concurrently with a job of the same run and overwrite its ckpt/last.pth.
# The command below fresh-starts AND resumes (--resume auto), so this file is
# submitted N times in a singleton+afterany chain; each incarnation continues
# from ckpt/last.pth (<=1 epoch lost per kill) and a surplus job exits at the
# completion fast-path without allocating a model.

source {code_root}/{env}
source {code_root}/{stage}
set -u   # after env sourcing: unset vars (e.g. no SLURM context) fail loudly
cd $CODE_ROOT

# Surplus jobs are the NORMAL case in an over-long afterany chain. Check for
# completion BEFORE staging: otherwise every one of them unzips the dataset
# (~18 GB / 10-15 min for COCO) onto scratch on 4 A100s just to be told
# there is nothing to do. The same call resolves the backbone, so a moved or
# unreadable checkpoint aborts in seconds instead of after the stage.
# exit 0 = complete, 3 = no usable backbone, 2 = could not tell (fall through).
{python} tools/dense_done.py --matrix configs/dense_matrix.yaml \\
    --run {run_id} --require_backbone
DONE_STATUS=$?
if [ $DONE_STATUS -eq 0 ]; then
    echo "{run_id} is already complete -- exiting without staging data"
    exit 0
fi
if [ $DONE_STATUS -eq 3 ]; then
    echo "ERROR: {run_id} has no usable backbone -- not staging or training" >&2
    exit 1
fi

{stage_fn}

# The committed stage function enforces only the VAL count. A truncated
# train extraction would otherwise train {epochs_note} silently on partial
# data; the expected count is the one that stage function itself prints.
{count_guard}

{python} -m torch.distributed.run \\
    --nproc_per_node=4 \\
    --nnodes=1 \\
    --node_rank=0 \\
    --master_addr=localhost \\
    --master_port={port} \\
    {entry} \\
        --matrix configs/dense_matrix.yaml \\
        --run {run_id} \\
        --data_root {data_root}{ckpt_root_arg} \\
        --resume auto
STATUS=$?

{cleanup_fn}
exit $STATUS
"""

SUBMIT_TEMPLATE = """\
#!/bin/bash
# GENERATED by scripts/gen_dense_jobs.py -- submit the {n}-job chain for
# {run_id} ({est}).
#
# Every job carries --dependency=singleton (job name == run_id), so SLURM
# never runs two jobs of this run at once — re-running this script later
# EXTENDS the run safely: new jobs queue behind whatever is still
# running/pending, --resume auto continues from ckpt/last.pth, and a job that
# finds the run already complete exits in seconds.
#
# If the a0801 TaskProlog fault recurs (see docs/TASK_LOG.md), add
# --exclude=a0801 to the sbatch lines below.
set -eu
cd "$(dirname "$0")/.."

jid=$(sbatch --parsable --dependency=singleton scripts/jobs/{run_id}.sbatch)
echo "submitted {run_id} job 1: $jid (singleton)"
for i in $(seq 2 {n}); do
    jid=$(sbatch --parsable --dependency=singleton,afterany:$jid scripts/jobs/{run_id}.sbatch)
    echo "submitted {run_id} job $i: $jid (singleton + afterany chain)"
done
"""

SMOKE_TEMPLATE = """\
#!/bin/bash
#SBATCH --job-name=dense_smoke_{short}
#SBATCH --partition=a100
#SBATCH --gres=gpu:a100:4
#SBATCH --time=01:30:00
#SBATCH --cpus-per-task=8
#SBATCH --ntasks-per-node=4
#SBATCH --output={log_dir}/dense_smoke_{short}_%j.log
#SBATCH --error={log_dir}/dense_smoke_{short}_%j.err

# GENERATED by scripts/gen_dense_jobs.py -- do not edit by hand.
# TASK-09 {task} SMOKE: the unit suite ON DEVICE (so the B5 normalization
# assertion and the B4 mIoU-ignore test are checked with a real GPU and the
# HPC's own torch/timm), then {epochs}x{steps} = ~{total_steps} train
# iterations + one capped eval pass end to end. The epoch count is chosen so
# that the LAST epoch runs with the backbone UNFROZEN
# (freeze_backbone_epochs={freeze}) — a 1-epoch smoke would never exercise
# backbone gradients at dense resolution, which is the path most likely to
# break. Outputs go to results/smoke/ (git-ignored) and every JSON they
# produce carries "smoke": true, so a smoke number can never be mistaken for
# a result.

source {code_root}/{env}
source {code_root}/{stage}
set -u
cd $CODE_ROOT

echo "===================== dependency check ====================="
# pycocotools was never declared until TASK-09; if it is missing the unit
# suite would only SKIP its COCO tests and report green, so check explicitly
{python} -c "import pycocotools.cocoeval, timm, torch; print('deps ok:', torch.__version__, timm.__version__)"
if [ $? -ne 0 ]; then
    echo "ERROR: required packages missing on this node -- pip install -r requirements.txt" >&2
    exit 1
fi

echo "===================== on-device pytest ====================="
{python} -m pytest -q tests/test_task09_dense.py
PYTEST_STATUS=$?
if [ $PYTEST_STATUS -ne 0 ]; then
    echo "ERROR: tests/test_task09_dense.py FAILED on the compute node - not starting the smoke run" >&2
    exit $PYTEST_STATUS
fi

{stage_fn}

echo "===================== smoke run ====================="
{python} -m torch.distributed.run \\
    --nproc_per_node=4 \\
    --nnodes=1 \\
    --node_rank=0 \\
    --master_addr=localhost \\
    --master_port={port} \\
    {entry} \\
        --matrix configs/dense_matrix.yaml \\
        --run {run_id} \\
        --data_root {data_root} \\
        --out_root results/smoke/{task} \\
        --max_epochs {epochs} \\
        --max_steps {steps} \\
        --max_eval_images {eval_images}{ckpt_root_arg} \\
        --resume none
STATUS=$?

{cleanup_fn}
exit $STATUS
"""

# task -> (run_id, port, epochs, steps_per_epoch, eval_images, freeze_epochs)
# epochs > freeze_backbone_epochs so the last smoke epoch trains the backbone
SMOKE_RUNS = {
    "detection": ("det_vitb_saga_s1", 29860, 2, 25, 64, 1),
    "segmentation": ("seg_vitb_saga_s1", 29861, 3, 17, 64, 2),
}


def render(matrix: dict, out_dir: Path, base_port: int):
    jobs_dir = out_dir / "jobs"
    jobs_dir.mkdir(parents=True, exist_ok=True)
    written = []

    # ckpt/ defaults to the run dir, i.e. CODE_ROOT on the `hpc` filesystem —
    # which How to Run.md §1 reserves for CODE ONLY and which measured 101G
    # of a 100G soft quota on 2026-09-08. Setting `ckpt_root` in the matrix
    # redirects every checkpoint (~1.16 GiB per detection run, ~1.37 GiB per
    # segmentation run, and the same again for each SMOKE — the smokes write
    # checkpoints too) onto a bulk filesystem. Null/empty emits no flag and
    # keeps the previous default.
    ckpt_root = matrix.get("ckpt_root") or ""
    ckpt_root_arg = ("" if not ckpt_root else
                     " \\\n        --ckpt_root " + str(ckpt_root))

    for i, (run_id, run) in enumerate(sorted(matrix["runs"].items())):
        setup = TASK_SETUP[run["task"]]
        n = int(matrix.get("chain", {}).get(run["task"], 2))
        port = base_port + i
        job = JOB_TEMPLATE.format(
            run_id=run_id, task=run["task"], variant=run["variant"],
            log_dir=LOG_DIR, code_root=CODE_ROOT, python=PYTHON, port=port,
            env=setup["env"], stage=setup["stage"],
            stage_fn=setup["stage_fn"], cleanup_fn=setup["cleanup_fn"],
            entry=setup["entry"], data_root=setup["data_root"],
            epochs_note=setup["epochs_note"],
            count_guard=setup["count_guard"],
            ckpt_root_arg=ckpt_root_arg)
        path = jobs_dir / f"{run_id}.sbatch"
        path.write_text(job, encoding="utf-8", newline="\n")
        written.append(path)

        est = f"{n}x24h walltime, {run['task']} {run['variant']}"
        sub = out_dir / f"submit_{run_id}.sh"
        sub.write_text(
            SUBMIT_TEMPLATE.format(run_id=run_id, n=n, est=est),
            encoding="utf-8", newline="\n")
        written.append(sub)
        print(f"{run_id}: chain of {n} (port {port}) -> "
              f"{sub.name} + jobs/{path.name}")

    for task, spec in sorted(SMOKE_RUNS.items()):
        run_id, port, epochs, steps, eval_images, freeze = spec
        setup = TASK_SETUP[task]
        short = "det" if task == "detection" else "seg"
        smoke = SMOKE_TEMPLATE.format(
            short=short, task=task, run_id=run_id, log_dir=LOG_DIR,
            code_root=CODE_ROOT, python=PYTHON, port=port, epochs=epochs,
            steps=steps, total_steps=epochs * steps, freeze=freeze,
            eval_images=eval_images, env=setup["env"], stage=setup["stage"],
            stage_fn=setup["stage_fn"], cleanup_fn=setup["cleanup_fn"],
            entry=setup["entry"], data_root=setup["data_root"],
            ckpt_root_arg=ckpt_root_arg)
        path = jobs_dir / f"dense_smoke_{short}.sbatch"
        path.write_text(smoke, encoding="utf-8", newline="\n")
        written.append(path)
        print(f"smoke {task}: {run_id} (port {port}) -> jobs/{path.name}")
    return written


def main():
    p = argparse.ArgumentParser(
        description="Generate the TASK-09 dense SLURM chains + smokes.")
    p.add_argument("--matrix", default="configs/dense_matrix.yaml")
    p.add_argument("--out-dir", default="scripts")
    p.add_argument("--base-port", type=int, default=29850)
    args = p.parse_args()

    matrix_path = Path(args.matrix)
    if not matrix_path.is_absolute():
        matrix_path = REPO_ROOT / matrix_path
    matrix = yaml.safe_load(open(matrix_path))
    out_dir = Path(args.out_dir)
    if not out_dir.is_absolute():
        out_dir = REPO_ROOT / out_dir

    unknown = sorted({r["task"] for r in matrix["runs"].values()}
                     - set(TASK_SETUP))
    if unknown:
        sys.exit(f"matrix references unknown tasks {unknown}")

    render(matrix, out_dir, args.base_port)
    print(f"\n{len(matrix['runs'])} chains + 2 smokes generated. Smoke first:")
    print("  sbatch scripts/jobs/dense_smoke_det.sbatch")
    print("  sbatch scripts/jobs/dense_smoke_seg.sbatch")


if __name__ == "__main__":
    main()
