#!/usr/bin/env python3
"""
scripts/gen_ft_jobs.py — TASK-08 launcher generator
===================================================
Reads configs/ft_matrix.yaml and writes:

  scripts/jobs/ft_finegrained_array.sbatch   one single-GPU ARRAY job
                                             (0..N-1, one task per run —
                                             the pattern How to Run.md
                                             documents for Alex)
  scripts/jobs/ft_smoke.sbatch               2-epoch smoke of
                                             ft_cub_vits_saga_bs1_f0 into
                                             results/smoke/ (never touches
                                             results/runs/)

Each array task stages its dataset tarball to node-local /scratch keyed by
SLURM_JOB_ID (unique per array task -> no collisions), runs train_ft.py,
and cleans up. Completed runs are skipped by the trainer's requeue guard
(eval/test_final.json), so resubmitting the array (or a subset,
--array=3-5) is always safe.

Regenerate after editing the matrix:  python scripts/gen_ft_jobs.py
"""

import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]

# Alex conventions (How to Run.md / env_alex.sh / existing e2r job files)
ENV_SH = "/home/hpc/iwi5/iwi5359h/my_repos/SAGA/scripts/env_alex.sh"
PYTHON = "/home/vault/iwi5/iwi5359h/envs/saga/bin/python"
LOG_DIR = "/home/vault/iwi5/iwi5359h/SAGA/logs"

HEADER = """\
#!/bin/bash
#SBATCH --job-name={name}
#SBATCH --partition=a100
#SBATCH --gres=gpu:a100:1
#SBATCH --time={time}
#SBATCH --cpus-per-task=8
{array_line}#SBATCH --output={log_dir}/{name}_{log_suffix}.log
#SBATCH --error={log_dir}/{name}_{log_suffix}.err

# GENERATED by scripts/gen_ft_jobs.py -- do not edit by hand.
"""

BODY = """\
source {env_sh}
set -u   # after env sourcing: unset vars (e.g. no SLURM context) fail loudly
cd $CODE_ROOT

# node-local staging, keyed by SLURM_JOB_ID (unique per array task)
FT_STAGE=/scratch/iwi5359h/ft_${{SLURM_JOB_ID}}
mkdir -p "$FT_STAGE"

{run_select}
if [ -z "$RUN_ID" ]; then
    echo "ERROR: no run mapped to this array index" >&2
    exit 1
fi
{python} evaluation/e6_finegrained/tools/train_ft.py \\
    --matrix configs/ft_matrix.yaml \\
    --run "$RUN_ID" \\
    --stage_base "$FT_STAGE"{extra_args}
STATUS=$?

rm -rf "$FT_STAGE"
exit $STATUS
"""


def gen(matrix_path=REPO / "configs" / "ft_matrix.yaml"):
    with open(matrix_path) as f:
        matrix = yaml.safe_load(f)
    run_ids = list(matrix["runs"])  # yaml preserves matrix order

    jobs_dir = REPO / "scripts" / "jobs"
    jobs_dir.mkdir(parents=True, exist_ok=True)

    # ── array job: one task per run ────────────────────────────────────────
    # POSITIONAL mapping (matrix order): only ever APPEND runs to the
    # matrix — inserting would silently re-map remembered --array indices
    lines = ["RUN_IDS=("]
    for i, rid in enumerate(run_ids):
        lines.append(f'    "{rid}"        # {i}')
    lines.append(")")
    lines.append('RUN_ID=${RUN_IDS[$SLURM_ARRAY_TASK_ID]:-}')
    lines.append('echo "array task $SLURM_ARRAY_TASK_ID -> $RUN_ID"')
    run_select = "\n".join(lines)

    array_sbatch = (
        HEADER.format(name="saga_ft16", time="06:00:00",
                      array_line=f"#SBATCH --array=0-{len(run_ids) - 1}\n",
                      log_dir=LOG_DIR, log_suffix="%A_%a")
        + BODY.format(env_sh=ENV_SH, python=PYTHON,
                      run_select=run_select, extra_args=""))
    out_array = jobs_dir / "ft_finegrained_array.sbatch"
    out_array.write_text(array_sbatch, newline="\n")

    # ── smoke job: 2 epochs, CUB-S saga f0, results/smoke/ ─────────────────
    smoke_sbatch = (
        HEADER.format(name="saga_ft_smoke", time="00:45:00", array_line="",
                      log_dir=LOG_DIR, log_suffix="%j")
        + BODY.format(env_sh=ENV_SH, python=PYTHON,
                      run_select='RUN_ID=ft_cub_vits_saga_bs1_f0',
                      extra_args=" \\\n    --max_epochs 2"
                                 " \\\n    --out_root results/smoke"))
    out_smoke = jobs_dir / "ft_smoke.sbatch"
    out_smoke.write_text(smoke_sbatch, newline="\n")

    print(f"wrote {out_array.relative_to(REPO)} ({len(run_ids)} tasks) and "
          f"{out_smoke.relative_to(REPO)}")
    return out_array, out_smoke


if __name__ == "__main__":
    sys.exit(0 if gen() else 1)
