#!/bin/bash
# GENERATED by tools/gen_rederive_jobs.py -- do not edit by hand.
# Regenerate with:
#   python tools/gen_rederive_jobs.py --manifest results/legacy/checkpoint_manifest.csv --exp e2 \
#       --data '$STAGE_DIR' --out scripts/rederive_e2.sh
#
# Idempotent: steps whose output JSON already exists with the matching
# ckpt_sha256 are skipped, so a job killed at the walltime is simply
# resubmitted. Failures land in results/legacy/rederive_failures.log and
# the script continues.
set -u
cd "$(dirname "$0")/.."          # repo root
DATA_ROOT="$STAGE_DIR"
mkdir -p results/legacy/eval results/legacy/diag
# fresh failure log per (re)run: finished steps skip, failed steps re-attempt
rm -f results/legacy/rederive_failures.log

# ---- e2_vit_base_mixup_baseline_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_mixup_baseline_rlast_best.json 0abb6e9641925532a35dd912bead44ff8e16ea4f6a3df100de559b8b5430b1ce; then
    echo "SKIP eval e2_vit_base_mixup_baseline_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_baseline/best.pth --arch vit_base --variant baseline --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_mixup_baseline_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_mixup_baseline_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_mixup_baseline_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_mixup_baseline_rlast_best.json 0abb6e9641925532a35dd912bead44ff8e16ea4f6a3df100de559b8b5430b1ce; then
    echo "SKIP diag e2_vit_base_mixup_baseline_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_baseline/best.pth --arch vit_base --variant baseline --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_mixup_baseline_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_mixup_baseline_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_mixup_baseline_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_mixup_baseline_rlast_last.json 467daf9dfcfd712534737cf727ff05155b31e4905cd3597da766224526ba70a5; then
    echo "SKIP eval e2_vit_base_mixup_baseline_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_baseline/last.pth --arch vit_base --variant baseline --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_mixup_baseline_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_mixup_baseline_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_mixup_baseline_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_mixup_baseline_rlast_last.json 467daf9dfcfd712534737cf727ff05155b31e4905cd3597da766224526ba70a5; then
    echo "SKIP diag e2_vit_base_mixup_baseline_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_baseline/last.pth --arch vit_base --variant baseline --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_mixup_baseline_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_mixup_baseline_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_mixup_registers_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_mixup_registers_rlast_best.json c30f813dcb23c20b7182af0d9493ee71250e91098624e815caf6046098f2e698; then
    echo "SKIP eval e2_vit_base_mixup_registers_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_registers/best.pth --arch vit_base --variant registers --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_mixup_registers_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_mixup_registers_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_mixup_registers_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_mixup_registers_rlast_best.json c30f813dcb23c20b7182af0d9493ee71250e91098624e815caf6046098f2e698; then
    echo "SKIP diag e2_vit_base_mixup_registers_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_registers/best.pth --arch vit_base --variant registers --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_mixup_registers_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_mixup_registers_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_mixup_registers_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_mixup_registers_rlast_last.json 3e13c788fff6812a17ec0c04a2f1505a2e3af2a9c2db9d6afe9319084cdc1e53; then
    echo "SKIP eval e2_vit_base_mixup_registers_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_registers/last.pth --arch vit_base --variant registers --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_mixup_registers_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_mixup_registers_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_mixup_registers_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_mixup_registers_rlast_last.json 3e13c788fff6812a17ec0c04a2f1505a2e3af2a9c2db9d6afe9319084cdc1e53; then
    echo "SKIP diag e2_vit_base_mixup_registers_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_registers/last.pth --arch vit_base --variant registers --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_mixup_registers_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_mixup_registers_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_mixup_saga_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_mixup_saga_rlast_best.json bbfbc1d843e819910d68f660bcdb038510b4bf2e4ae8f6428c6a705e7c0e165e; then
    echo "SKIP eval e2_vit_base_mixup_saga_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_SAGA/best.pth --arch vit_base --variant saga --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_mixup_saga_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_mixup_saga_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_mixup_saga_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_mixup_saga_rlast_best.json bbfbc1d843e819910d68f660bcdb038510b4bf2e4ae8f6428c6a705e7c0e165e; then
    echo "SKIP diag e2_vit_base_mixup_saga_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_SAGA/best.pth --arch vit_base --variant saga --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_mixup_saga_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_mixup_saga_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_mixup_saga_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_mixup_saga_rlast_last.json c10af1fd55c4c39b44a0be7adc6527e3b0619c9db6a2dc7072d98d9adc9246f5; then
    echo "SKIP eval e2_vit_base_mixup_saga_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_SAGA/last.pth --arch vit_base --variant saga --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_mixup_saga_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_mixup_saga_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_mixup_saga_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_mixup_saga_rlast_last.json c10af1fd55c4c39b44a0be7adc6527e3b0619c9db6a2dc7072d98d9adc9246f5; then
    echo "SKIP diag e2_vit_base_mixup_saga_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_SAGA/last.pth --arch vit_base --variant saga --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_mixup_saga_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_mixup_saga_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_baseline_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_nomix_baseline_rlast_best.json df97d3215d477450fdc5c747eb8ee85a963e939f7c424ce24eca431a1e4fc3e6; then
    echo "SKIP eval e2_vit_base_nomix_baseline_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_baseline_nomix/best.pth --arch vit_base --variant baseline --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_nomix_baseline_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_nomix_baseline_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_baseline_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_nomix_baseline_rlast_best.json df97d3215d477450fdc5c747eb8ee85a963e939f7c424ce24eca431a1e4fc3e6; then
    echo "SKIP diag e2_vit_base_nomix_baseline_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_baseline_nomix/best.pth --arch vit_base --variant baseline --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_nomix_baseline_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_nomix_baseline_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_baseline_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_nomix_baseline_rlast_last.json 2a7f8c84dc32571e95dc3745422b4960f9dd602433cd42f1e16891b6c491cac5; then
    echo "SKIP eval e2_vit_base_nomix_baseline_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_baseline_nomix/last.pth --arch vit_base --variant baseline --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_nomix_baseline_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_nomix_baseline_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_baseline_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_nomix_baseline_rlast_last.json 2a7f8c84dc32571e95dc3745422b4960f9dd602433cd42f1e16891b6c491cac5; then
    echo "SKIP diag e2_vit_base_nomix_baseline_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_baseline_nomix/last.pth --arch vit_base --variant baseline --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_nomix_baseline_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_nomix_baseline_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_registers_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_nomix_registers_rlast_best.json 57e053d2a7ab551190b3eebf0fb28bb27fe36d8c6cfcf14272c7332caf942e13; then
    echo "SKIP eval e2_vit_base_nomix_registers_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_registers_nomix/best.pth --arch vit_base --variant registers --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_nomix_registers_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_nomix_registers_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_registers_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_nomix_registers_rlast_best.json 57e053d2a7ab551190b3eebf0fb28bb27fe36d8c6cfcf14272c7332caf942e13; then
    echo "SKIP diag e2_vit_base_nomix_registers_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_registers_nomix/best.pth --arch vit_base --variant registers --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_nomix_registers_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_nomix_registers_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_registers_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_nomix_registers_rlast_last.json 82365a311187250c34965c93a13ab435adf7ac2ad655115c855f7708f6f8ddb1; then
    echo "SKIP eval e2_vit_base_nomix_registers_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_registers_nomix/last.pth --arch vit_base --variant registers --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_nomix_registers_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_nomix_registers_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_registers_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_nomix_registers_rlast_last.json 82365a311187250c34965c93a13ab435adf7ac2ad655115c855f7708f6f8ddb1; then
    echo "SKIP diag e2_vit_base_nomix_registers_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_registers_nomix/last.pth --arch vit_base --variant registers --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_nomix_registers_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_nomix_registers_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_saga_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_nomix_saga_rlast_best.json 82456589c91ec3757509bd1d48aa6cf1e8dd51235a1138df6b7e1951181c2ba0; then
    echo "SKIP eval e2_vit_base_nomix_saga_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_SAGA_nomix/best.pth --arch vit_base --variant saga --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_nomix_saga_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_nomix_saga_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_saga_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_nomix_saga_rlast_best.json 82456589c91ec3757509bd1d48aa6cf1e8dd51235a1138df6b7e1951181c2ba0; then
    echo "SKIP diag e2_vit_base_nomix_saga_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_SAGA_nomix/best.pth --arch vit_base --variant saga --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_nomix_saga_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_nomix_saga_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_saga_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_base_nomix_saga_rlast_last.json 4a1c5a1fe54692afbffdc25f26b9491c255d826f27aefeec9b74cf775ba43ef2; then
    echo "SKIP eval e2_vit_base_nomix_saga_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_SAGA_nomix/last.pth --arch vit_base --variant saga --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_base_nomix_saga_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_base_nomix_saga_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_base_nomix_saga_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_base_nomix_saga_rlast_last.json 4a1c5a1fe54692afbffdc25f26b9491c255d826f27aefeec9b74cf775ba43ef2; then
    echo "SKIP diag e2_vit_base_nomix_saga_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-B_SAGA_nomix/last.pth --arch vit_base --variant saga --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_base_nomix_saga_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_base_nomix_saga_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_baseline_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_mixup_baseline_rlast_best.json 3667feeb3f80c2b19eef50843bea10532d5d4ecd65d82ec551bfac4435ae45c2; then
    echo "SKIP eval e2_vit_small_mixup_baseline_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_baseline/best.pth --arch vit_small --variant baseline --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_mixup_baseline_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_mixup_baseline_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_baseline_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_mixup_baseline_rlast_best.json 3667feeb3f80c2b19eef50843bea10532d5d4ecd65d82ec551bfac4435ae45c2; then
    echo "SKIP diag e2_vit_small_mixup_baseline_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_baseline/best.pth --arch vit_small --variant baseline --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_mixup_baseline_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_mixup_baseline_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_baseline_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_mixup_baseline_rlast_last.json cd926200127b98cbc597ddad82d84fd823376addc0ac1075a98de73b21e7d17d; then
    echo "SKIP eval e2_vit_small_mixup_baseline_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_baseline/last.pth --arch vit_small --variant baseline --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_mixup_baseline_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_mixup_baseline_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_baseline_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_mixup_baseline_rlast_last.json cd926200127b98cbc597ddad82d84fd823376addc0ac1075a98de73b21e7d17d; then
    echo "SKIP diag e2_vit_small_mixup_baseline_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_baseline/last.pth --arch vit_small --variant baseline --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_mixup_baseline_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_mixup_baseline_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_registers_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_mixup_registers_rlast_best.json a99aa1eebdb3503d481f23f8730af39d2a1c2c0ccf019e519e8e86520a882f28; then
    echo "SKIP eval e2_vit_small_mixup_registers_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_registers/best.pth --arch vit_small --variant registers --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_mixup_registers_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_mixup_registers_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_registers_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_mixup_registers_rlast_best.json a99aa1eebdb3503d481f23f8730af39d2a1c2c0ccf019e519e8e86520a882f28; then
    echo "SKIP diag e2_vit_small_mixup_registers_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_registers/best.pth --arch vit_small --variant registers --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_mixup_registers_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_mixup_registers_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_registers_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_mixup_registers_rlast_last.json e50859f062be20cf971cefac39fde542bd3dc47fa272f3ed78abc193b71a8a77; then
    echo "SKIP eval e2_vit_small_mixup_registers_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_registers/last.pth --arch vit_small --variant registers --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_mixup_registers_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_mixup_registers_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_registers_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_mixup_registers_rlast_last.json e50859f062be20cf971cefac39fde542bd3dc47fa272f3ed78abc193b71a8a77; then
    echo "SKIP diag e2_vit_small_mixup_registers_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_registers/last.pth --arch vit_small --variant registers --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_mixup_registers_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_mixup_registers_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_saga_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_mixup_saga_rlast_best.json 09d1889c7061db0903edad420833ec1147e507572b28038ff75e1efea139b672; then
    echo "SKIP eval e2_vit_small_mixup_saga_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_SAGA/best.pth --arch vit_small --variant saga --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_mixup_saga_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_mixup_saga_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_saga_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_mixup_saga_rlast_best.json 09d1889c7061db0903edad420833ec1147e507572b28038ff75e1efea139b672; then
    echo "SKIP diag e2_vit_small_mixup_saga_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_SAGA/best.pth --arch vit_small --variant saga --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_mixup_saga_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_mixup_saga_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_saga_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_mixup_saga_rlast_last.json 92a03a4716ce07c0460eb132720d8a816aaa2bcde49713b86c57c774fef22995; then
    echo "SKIP eval e2_vit_small_mixup_saga_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_SAGA/last.pth --arch vit_small --variant saga --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_mixup_saga_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_mixup_saga_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_mixup_saga_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_mixup_saga_rlast_last.json 92a03a4716ce07c0460eb132720d8a816aaa2bcde49713b86c57c774fef22995; then
    echo "SKIP diag e2_vit_small_mixup_saga_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_SAGA/last.pth --arch vit_small --variant saga --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_mixup_saga_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_mixup_saga_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_baseline_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_nomix_baseline_rlast_best.json 67c85a1d70b30f54bdacc16c18dbac7da3abba7ca98486536dc6f7a33b76eb07; then
    echo "SKIP eval e2_vit_small_nomix_baseline_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_baseline_nomix/best.pth --arch vit_small --variant baseline --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_nomix_baseline_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_nomix_baseline_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_baseline_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_nomix_baseline_rlast_best.json 67c85a1d70b30f54bdacc16c18dbac7da3abba7ca98486536dc6f7a33b76eb07; then
    echo "SKIP diag e2_vit_small_nomix_baseline_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_baseline_nomix/best.pth --arch vit_small --variant baseline --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_nomix_baseline_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_nomix_baseline_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_baseline_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_nomix_baseline_rlast_last.json 8d980da27a4b571a117e82451c8c9deff126e437206faee5120e069d3667e10d; then
    echo "SKIP eval e2_vit_small_nomix_baseline_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_baseline_nomix/last.pth --arch vit_small --variant baseline --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_nomix_baseline_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_nomix_baseline_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_baseline_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_nomix_baseline_rlast_last.json 8d980da27a4b571a117e82451c8c9deff126e437206faee5120e069d3667e10d; then
    echo "SKIP diag e2_vit_small_nomix_baseline_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_baseline_nomix/last.pth --arch vit_small --variant baseline --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_nomix_baseline_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_nomix_baseline_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_registers_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_nomix_registers_rlast_best.json 7453f3d4d808979d74c7532bea7be24d566f73680720c6968110383d9d8e52af; then
    echo "SKIP eval e2_vit_small_nomix_registers_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_registers_nomix/best.pth --arch vit_small --variant registers --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_nomix_registers_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_nomix_registers_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_registers_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_nomix_registers_rlast_best.json 7453f3d4d808979d74c7532bea7be24d566f73680720c6968110383d9d8e52af; then
    echo "SKIP diag e2_vit_small_nomix_registers_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_registers_nomix/best.pth --arch vit_small --variant registers --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_nomix_registers_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_nomix_registers_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_registers_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_nomix_registers_rlast_last.json 7ca33ed755106aa7f0d0b02ebf6ceb003808fc5dc3f78699538de1fba820e536; then
    echo "SKIP eval e2_vit_small_nomix_registers_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_registers_nomix/last.pth --arch vit_small --variant registers --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_nomix_registers_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_nomix_registers_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_registers_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_nomix_registers_rlast_last.json 7ca33ed755106aa7f0d0b02ebf6ceb003808fc5dc3f78699538de1fba820e536; then
    echo "SKIP diag e2_vit_small_nomix_registers_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_registers_nomix/last.pth --arch vit_small --variant registers --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_nomix_registers_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_nomix_registers_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_saga_rlast_best (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_nomix_saga_rlast_best.json e06051840eaf27b9e1612d5672bf16e52e2e4255e2ea8949fa88e3e64a4c42c3; then
    echo "SKIP eval e2_vit_small_nomix_saga_rlast_best (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_SAGA_nomix/best.pth --arch vit_small --variant saga --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_nomix_saga_rlast_best.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_nomix_saga_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_saga_rlast_best (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_nomix_saga_rlast_best.json e06051840eaf27b9e1612d5672bf16e52e2e4255e2ea8949fa88e3e64a4c42c3; then
    echo "SKIP diag e2_vit_small_nomix_saga_rlast_best (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_SAGA_nomix/best.pth --arch vit_small --variant saga --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_nomix_saga_rlast_best.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_nomix_saga_rlast_best FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_saga_rlast_last (eval) ----
if python tools/check_done.py results/legacy/eval/e2_vit_small_nomix_saga_rlast_last.json a482f5286b2c43ffa8d9f6606b1af24d06962421b808babfdd6b123a56b0f9ee; then
    echo "SKIP eval e2_vit_small_nomix_saga_rlast_last (already done)"
else
    python tools/eval.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_SAGA_nomix/last.pth --arch vit_small --variant saga --data "$DATA_ROOT" --out results/legacy/eval/e2_vit_small_nomix_saga_rlast_last.json --batch-size 256 --device cuda \
        || echo "eval/e2_vit_small_nomix_saga_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- e2_vit_small_nomix_saga_rlast_last (diag) ----
if python tools/check_done.py results/legacy/diag/e2_vit_small_nomix_saga_rlast_last.json a482f5286b2c43ffa8d9f6606b1af24d06962421b808babfdd6b123a56b0f9ee; then
    echo "SKIP diag e2_vit_small_nomix_saga_rlast_last (already done)"
else
    python tools/diagnose.py --ckpt /home/vault/iwi5/iwi5359h/SAGA/e2/checkpoints/ViT-S_SAGA_nomix/last.pth --arch vit_small --variant saga --data "$DATA_ROOT" --split-file results/diagsplit/val_diag_split.json --out results/legacy/diag/e2_vit_small_nomix_saga_rlast_last.json --batch-size 128 --device cuda \
        || echo "diag/e2_vit_small_nomix_saga_rlast_last FAILED" >> results/legacy/rederive_failures.log
fi

# ---- fixed thresholds (nomix baselines must have finished above) ----
python tools/compute_fixed_thr.py --diag-dir results/legacy/diag \
        --out results/diagsplit/fixed_thresholds.json \
    || echo "compute_fixed_thr FAILED" >> results/legacy/rederive_failures.log
python tools/apply_fixed_thr.py --diag-dir results/legacy/diag \
        --thresholds results/diagsplit/fixed_thresholds.json \
    || echo "apply_fixed_thr FAILED" >> results/legacy/rederive_failures.log

echo "======================================================"
if [ -s results/legacy/rederive_failures.log ]; then
    echo "  RE-DERIVATION FINISHED WITH FAILURES:"
    cat results/legacy/rederive_failures.log
    exit 1
fi
echo "  RE-DERIVATION COMPLETE, no failures"
