#!/bin/bash
# GENERATED by scripts/gen_dense_jobs.py -- submit the 4-job chain for
# det_vitb_baseline_s1 (4x24h walltime, detection baseline).
#
# Every job carries --dependency=singleton (job name == run_id), so SLURM
# never runs two jobs of this run at once — re-running this script later
# EXTENDS the run safely: new jobs queue behind whatever is still
# running/pending, --resume auto continues from ckpt/last.pth, and a job that
# finds the run already complete exits in seconds.
#
# If the a0801 TaskProlog fault recurs (see docs/TASK_LOG.md), add
# --exclude=a0801 to the sbatch lines below.
set -eu
cd "$(dirname "$0")/.."

jid=$(sbatch --parsable --dependency=singleton scripts/jobs/det_vitb_baseline_s1.sbatch)
echo "submitted det_vitb_baseline_s1 job 1: $jid (singleton)"
for i in $(seq 2 4); do
    jid=$(sbatch --parsable --dependency=singleton,afterany:$jid scripts/jobs/det_vitb_baseline_s1.sbatch)
    echo "submitted det_vitb_baseline_s1 job $i: $jid (singleton + afterany chain)"
done
