#!/bin/bash
# GENERATED by scripts/gen_slurm_chain.py -- submit the 4-job chain for
# e2r_vitb_mixup_baseline_s1 (4x24h walltime, arch vit_base_patch16_224).
#
# Every job carries --dependency=singleton (job name == run_id), so SLURM
# never runs two jobs of this run at once — re-running this script later
# EXTENDS the run safely: the new jobs queue behind whatever is still
# running/pending, and --resume auto continues from ckpt/last.pth (a
# finished run exits quickly, so surplus jobs are harmless).
set -eu
cd "$(dirname "$0")/.."

jid=$(sbatch --parsable --dependency=singleton scripts/jobs/e2r_vitb_mixup_baseline_s1.sbatch)
echo "submitted e2r_vitb_mixup_baseline_s1 job 1: $jid (singleton)"
for i in $(seq 2 4); do
    jid=$(sbatch --parsable --dependency=singleton,afterany:$jid scripts/jobs/e2r_vitb_mixup_baseline_s1.sbatch)
    echo "submitted e2r_vitb_mixup_baseline_s1 job $i: $jid (singleton + afterany chain)"
done
