#!/usr/bin/env python3
"""
tools/gen_rederive_jobs.py
==========================
Generate the sequential single-GPU re-derivation script for the legacy
checkpoints (TASK-02 1.4).

    python tools/gen_rederive_jobs.py \
        --manifest results/legacy/checkpoint_manifest.csv \
        --exp e2 --data '$STAGE_DIR' --out scripts/rederive_e2.sh

For every manifest row of the selected experiment(s), the script runs
tools/eval.py and tools/diagnose.py (with attention capture) on the
checkpoint, writing results/legacy/{eval,diag}/<stem>.json with
stem = <exp>_<arch>_<recipe>_<variant>_<seed>_<best|last>.

Idempotency (requeue safety): each step is guarded by tools/check_done.py —
it is skipped iff its output JSON exists AND its ckpt_sha256 matches the
manifest. Failures append to results/legacy/rederive_failures.log and the
script continues (never falls back to non-strict loading). The script ends
with compute_fixed_thr + apply_fixed_thr.

--data may be a literal path or an unexpanded variable like '$STAGE_DIR'
(resolved when the script runs inside the job, after staging).
"""

import argparse
import csv
import sys
from pathlib import Path

VALID_ARCHS = {"vit_small", "vit_base"}
VALID_VARIANTS = {"baseline", "registers", "saga"}

# rough minutes per step (spec 1.4): vit_small eval/diag, vit_base = 2x
EST_MIN = {"vit_small": {"eval": 5, "diag": 10},
           "vit_base": {"eval": 10, "diag": 20}}

HEADER = """\
#!/bin/bash
# GENERATED by tools/gen_rederive_jobs.py -- do not edit by hand.
# Regenerate with:
#   python tools/gen_rederive_jobs.py --manifest {manifest} --exp {exps} \\
#       --data '{data}' --out {out}
#
# Idempotent: steps whose output JSON already exists with the matching
# ckpt_sha256 are skipped, so a job killed at the walltime is simply
# resubmitted. Failures land in results/legacy/rederive_failures.log and
# the script continues.
set -u
cd "$(dirname "$0")/.."          # repo root
DATA_ROOT="{data}"
mkdir -p results/legacy/eval results/legacy/diag
# fresh failure log per (re)run: finished steps skip, failed steps re-attempt
rm -f results/legacy/rederive_failures.log
"""

STEP = """\

# ---- {stem} ({tool}) ----
if python tools/check_done.py {out_json} {sha}; then
    echo "SKIP {tool} {stem} (already done)"
else
    {cmd} \\
        || echo "{tool}/{stem} FAILED" >> results/legacy/rederive_failures.log
fi
"""

FOOTER = """\

# ---- fixed thresholds (nomix baselines must have finished above) ----
python tools/compute_fixed_thr.py --diag-dir results/legacy/diag \\
        --out results/diagsplit/fixed_thresholds.json \\
    || echo "compute_fixed_thr FAILED" >> results/legacy/rederive_failures.log
python tools/apply_fixed_thr.py --diag-dir results/legacy/diag \\
        --thresholds results/diagsplit/fixed_thresholds.json \\
    || echo "apply_fixed_thr FAILED" >> results/legacy/rederive_failures.log

echo "======================================================"
if [ -s results/legacy/rederive_failures.log ]; then
    echo "  RE-DERIVATION FINISHED WITH FAILURES:"
    cat results/legacy/rederive_failures.log
    exit 1
fi
echo "  RE-DERIVATION COMPLETE, no failures"
"""


def load_rows(manifest: Path, exps):
    with open(manifest, newline="") as f:
        rows = [r for r in csv.DictReader(f) if r["exp"] in exps]
    if not rows:
        sys.exit(f"no manifest rows for exp in {sorted(exps)}")
    for r in rows:
        problems = []
        if r["arch"] not in VALID_ARCHS:
            problems.append(f"arch={r['arch']!r}")
        if r["variant"] not in VALID_VARIANTS:
            problems.append(f"variant={r['variant']!r}")
        if not r["recipe"] or not r["seed"]:
            problems.append("empty recipe/seed")
        if r["filename"] not in ("best.pth", "last.pth"):
            problems.append(f"filename={r['filename']!r}")
        if not r["sha256"]:
            problems.append("empty sha256")
        if problems:
            sys.exit(f"manifest row not runnable ({', '.join(problems)}): "
                     f"{r['path']}\nFill/fix the manifest first.")
    return rows


def emit(rows, data: str, batch_eval: int, batch_diag: int) -> str:
    parts = []
    for r in sorted(rows, key=lambda r: (r["exp"], r["arch"], r["recipe"],
                                         r["variant"], r["seed"],
                                         r["filename"])):
        tag = r["filename"].removesuffix(".pth")
        stem = "_".join([r["exp"], r["arch"], r["recipe"], r["variant"],
                         r["seed"], tag])
        eval_cmd = (f"python tools/eval.py --ckpt {r['path']} "
                    f"--arch {r['arch']} --variant {r['variant']} "
                    f'--data "$DATA_ROOT" '
                    f"--out results/legacy/eval/{stem}.json "
                    f"--batch-size {batch_eval} --device cuda")
        diag_cmd = (f"python tools/diagnose.py --ckpt {r['path']} "
                    f"--arch {r['arch']} --variant {r['variant']} "
                    f'--data "$DATA_ROOT" '
                    f"--split-file results/diagsplit/val_diag_split.json "
                    f"--out results/legacy/diag/{stem}.json "
                    f"--batch-size {batch_diag} --device cuda")
        parts.append(STEP.format(stem=stem, tool="eval", sha=r["sha256"],
                                 out_json=f"results/legacy/eval/{stem}.json",
                                 cmd=eval_cmd))
        parts.append(STEP.format(stem=stem, tool="diag", sha=r["sha256"],
                                 out_json=f"results/legacy/diag/{stem}.json",
                                 cmd=diag_cmd))
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(
        description="Generate the idempotent legacy re-derivation script.")
    parser.add_argument("--manifest",
                        default="results/legacy/checkpoint_manifest.csv")
    parser.add_argument("--exp", default="e2",
                        help="comma-separated experiments, e.g. e2 or e2,e3")
    parser.add_argument("--data", required=True,
                        help="ImageNet root, or an unexpanded var like "
                             "'$STAGE_DIR' resolved at job runtime")
    parser.add_argument("--out", default="scripts/rederive_e2.sh")
    parser.add_argument("--batch-size-eval", type=int, default=256)
    parser.add_argument("--batch-size-diag", type=int, default=128)
    args = parser.parse_args()

    exps = {e.strip() for e in args.exp.split(",") if e.strip()}
    rows = load_rows(Path(args.manifest), exps)

    script = (HEADER.format(manifest=args.manifest, exps=",".join(sorted(exps)),
                            data=args.data, out=args.out)
              + emit(rows, args.data, args.batch_size_eval,
                     args.batch_size_diag)
              + FOOTER)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", newline="\n", encoding="utf-8") as f:
        f.write(script)

    total_min = sum(EST_MIN[r["arch"]]["eval"] + EST_MIN[r["arch"]]["diag"]
                    for r in rows)
    n_steps = 2 * len(rows)
    print(f"wrote {out}")
    print(f"{len(rows)} checkpoints x (eval + diagnose) = {n_steps} steps")
    print(f"rough estimate: ~{total_min} min (~{total_min / 60:.1f} h) on one "
          f"GPU -- well inside a 24 h walltime")


if __name__ == "__main__":
    main()
