#!/usr/bin/env python3
"""
analysis/build_gate1_report.py
==============================
TASK-02 Phase 2 (2.3 + 2.5): generate results/notes/gate1_report.md from
results/tables/legacy_e2_corrected.csv.

Every corrected number is read from the CSV (which is verbatim from the
result JSONs) — nothing is typed in by hand. The old known-buggy reference
values are embedded below exactly as printed in TASK_02_rederive_legacy.md,
labeled as such, and are used for comparison only.

    python analysis/build_gate1_report.py \
        [--table results/tables/legacy_e2_corrected.csv]
        [--out results/notes/gate1_report.md]
"""

import argparse
import csv
import subprocess
from datetime import datetime, timezone
from pathlib import Path

# Old KNOWN-BUGGY reference table, copied verbatim from
# TASK_02_rederive_legacy.md ("comparison only, never cite as results").
# (arch, recipe, variant) -> (top1, sink_percent, oversmooth)
OLD_BUGGY = {
    ("vit_small", "mixup", "baseline"): (79.456, 2.733, 0.6067),
    ("vit_small", "mixup", "registers"): (78.632, 0.528, 0.7018),
    ("vit_small", "mixup", "saga"): (79.224, 2.357, 0.5365),
    ("vit_small", "nomix", "baseline"): (78.824, 2.981, 0.6864),
    ("vit_small", "nomix", "registers"): (78.552, 0.596, 0.6949),
    ("vit_small", "nomix", "saga"): (79.800, 2.825, 0.5760),
    ("vit_base", "nomix", "baseline"): (77.384, 2.483, 0.5124),
    ("vit_base", "nomix", "registers"): (76.512, 1.086, 0.8678),
    ("vit_base", "nomix", "saga"): (77.968, 1.987, 0.5016),
    # ViT-B/16 mixup: no previous numbers existed
}

N_PATCHES = 196
BEST_LAST_FLAG = 0.25

ARCH_NAME = {"vit_small": "ViT-S/16", "vit_base": "ViT-B/16"}


def fmt(x, nd=4):
    if isinstance(x, float):
        return f"{x:.{nd}f}"
    return str(x)


def load_table(path):
    rows = list(csv.DictReader(open(path, newline="")))
    for r in rows:
        for k, v in r.items():
            if k in ("arch", "recipe", "variant", "ckpt_sha256_last"):
                continue
            if v in ("", "MISSING"):
                r[k] = v
            else:
                r[k] = float(v)
    return {(r["arch"], r["recipe"], r["variant"]): r for r in rows}


def cell_verdict(t, arch, recipe):
    """Evaluate the Gate-1 clause set for one (arch, recipe) cell."""
    base = t[(arch, recipe, "baseline")]
    reg = t[(arch, recipe, "registers")]
    saga = t[(arch, recipe, "saga")]
    if any(r["sink_mad_k5"] == "MISSING" for r in (base, reg, saga)):
        return "MISSING", [("all clauses", False,
                            "MISSING inputs in this cell")], base, reg, saga

    clauses = [
        ("SAGA sink < baseline",
         saga["sink_mad_k5"] < base["sink_mad_k5"],
         f"{fmt(saga['sink_mad_k5'])} vs {fmt(base['sink_mad_k5'])}"),
        ("SAGA oversmooth_pairwise < baseline",
         saga["oversmooth_pairwise"] < base["oversmooth_pairwise"],
         f"{fmt(saga['oversmooth_pairwise'])} vs {fmt(base['oversmooth_pairwise'])}"),
        ("SAGA oversmooth_pairwise_nosink < baseline",
         saga["oversmooth_pairwise_nosink"] < base["oversmooth_pairwise_nosink"],
         f"{fmt(saga['oversmooth_pairwise_nosink'])} vs {fmt(base['oversmooth_pairwise_nosink'])}"),
        ("registers sink < baseline",
         reg["sink_mad_k5"] < base["sink_mad_k5"],
         f"{fmt(reg['sink_mad_k5'])} vs {fmt(base['sink_mad_k5'])}"),
        ("registers oversmooth_pairwise > baseline",
         reg["oversmooth_pairwise"] > base["oversmooth_pairwise"],
         f"{fmt(reg['oversmooth_pairwise'])} vs {fmt(base['oversmooth_pairwise'])}"),
        ("registers oversmooth_pairwise_nosink > baseline",
         reg["oversmooth_pairwise_nosink"] > base["oversmooth_pairwise_nosink"],
         f"{fmt(reg['oversmooth_pairwise_nosink'])} vs {fmt(base['oversmooth_pairwise_nosink'])}"),
    ]
    saga_ok = [ok for _, ok, _ in clauses[:3]]
    if all(ok for _, ok, _ in clauses):
        verdict = "PASS"
    elif not any(saga_ok):
        verdict = "FAIL"
    else:
        verdict = "PARTIAL"
    return verdict, clauses, base, reg, saga


def git_sha():
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"],
                                       text=True).strip()
    except Exception:
        return "unknown"


def main():
    parser = argparse.ArgumentParser(description="Generate the Gate-1 report.")
    parser.add_argument("--table",
                        default="results/tables/legacy_e2_corrected.csv")
    parser.add_argument("--out", default="results/notes/gate1_report.md")
    args = parser.parse_args()

    t = load_table(args.table)
    cells = sorted({(a, r) for a, r, _ in t})
    L = []

    L.append("# Gate-1 report — corrected legacy e2 numbers")
    L.append("")
    L.append(f"Generated by `analysis/build_gate1_report.py` from "
             f"`{args.table}` (values verbatim from "
             f"`results/legacy/{{eval,diag}}/*.json`; diagnostics from "
             f"`last.pth`). git `{git_sha()[:12]}`, "
             f"{datetime.now(timezone.utc).date().isoformat()}.")
    L.append("")
    L.append("Old reference values are the KNOWN-BUGGY table from "
             "TASK_02_rederive_legacy.md — comparison only, never citable. "
             "Their definitions differ: old top-1 = rank-0 ~12.5k shard; old "
             "sink = % of tokens above a POOLED mu+3sigma (register tokens "
             "contaminated patch statistics); old oversmooth = "
             "consecutive-neighbor cosine on the last batch only. Corrected: "
             "top-1 = exact 50k full-val; sink_mad_k5 = mean COUNT per image "
             "above per-image median+5*MAD; oversmoothing = full pairwise "
             "mean cosine on the 10k frozen split. Sink and oversmoothing "
             "columns are therefore NOT unit-comparable old-vs-new; they are "
             "shown side by side to see direction and ranking only.")
    L.append("")

    # ── 1. best vs last ──────────────────────────────────────────────────────
    L.append("## 1. best.pth vs last.pth (memo input, 2.3)")
    L.append("")
    L.append("The paper will report `last.pth`: the old best-checkpoint "
             "selection used the buggy 12.5k-image shard, so `best.pth` is "
             "selected on a corrupted criterion. Runs with |top1_best - "
             f"top1_last| > {BEST_LAST_FLAG} are flagged for discussion.")
    L.append("")
    L.append("| arch | recipe | variant | top1_best | top1_last | best-last | flag |")
    L.append("|---|---|---|---|---|---|---|")
    for (a, rec, v), r in sorted(t.items()):
        d = r["top1_best_minus_last"]
        flag = "**DISCUSS**" if isinstance(d, float) and abs(d) > BEST_LAST_FLAG else ""
        L.append(f"| {ARCH_NAME[a]} | {rec} | {v} | {fmt(r['top1_best'], 3)} "
                 f"| {fmt(r['top1_last'], 3)} | {fmt(d, 3)} | {flag} |")
    L.append("")

    # ── 2. corrected vs old buggy ────────────────────────────────────────────
    L.append("## 2. Corrected vs old (known-buggy) values")
    L.append("")
    L.append("Expected shifts and their causes (one line each):")
    L.append("- top-1 moves within roughly +/-0.4: full 50k val replaces the "
             "~12.5k rank-0 shard (B1).")
    L.append("- registers' sink RISES: the prefix fix (B2) stops register "
             "tokens from inflating sigma and corrupting thresholds, and the "
             "per-image median+5*MAD threshold is robust to the absorbed "
             "outliers.")
    L.append("- oversmoothing changes scale entirely: different metric (B3; "
             "full pairwise vs consecutive-neighbor-last-batch).")
    L.append("")
    L.append("`sink_mu3s%` = sink_mu3s/196*100 is a DERIVED aid (per-image "
             "mu+3sigma count as % of tokens) — closest available comparator "
             "to the old pooled mu+3sigma %; still not the same definition.")
    L.append("")

    # observed-vs-expected, computed from the same table (facts, no framing)
    dtop1s = [(k, t[k]["top1_last"] - OLD_BUGGY[k][0])
              for k in sorted(OLD_BUGGY) if k in t
              and isinstance(t[k]["top1_last"], float)]
    lo_k, lo = min(dtop1s, key=lambda kv: kv[1])
    hi_k, hi = max(dtop1s, key=lambda kv: kv[1])
    n_beyond = sum(1 for _, d in dtop1s if abs(d) > 0.4)
    reg_dirs = []
    for (a, rec, v), (o_top1, o_sink, _) in sorted(OLD_BUGGY.items()):
        if v != "registers" or (a, rec, v) not in t:
            continue
        mu3pct = t[(a, rec, v)]["sink_mu3s"] / N_PATCHES * 100
        word = "ROSE" if mu3pct > o_sink else "FELL"
        reg_dirs.append(f"{ARCH_NAME[a]}/{rec} {word} "
                        f"({fmt(o_sink, 3)}% old -> {fmt(mu3pct, 3)}%)")
    L.append("Observed notes (computed from the table):")
    L.append(f"- top-1 (new last vs old): all {len(dtop1s)} comparable cells "
             f"shifted between {fmt(lo, 3)} ({ARCH_NAME[lo_k[0]]}/{lo_k[1]} "
             f"{lo_k[2]}) and {fmt(hi, 3)} ({ARCH_NAME[hi_k[0]]}/{hi_k[1]} "
             f"{hi_k[2]}); {n_beyond} of them exceed the expected ~±0.4. "
             "Caveat: this comparison mixes TWO changes at once — the B1 "
             "full-val fix AND best->last checkpoint selection (old values "
             "were best.pth picked on the buggy shard).")
    L.append("- registers' sink vs old (via the sink_mu3s% aid): "
             + "; ".join(reg_dirs) + ".")
    L.append("")
    L.append("| arch | recipe | variant | top1 old | top1 new (last) | d top1 "
             "| sink old % | sink_mad_k5 new | sink_mu3s% new | oversmooth old "
             "| oversmooth_pairwise new |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for (a, rec, v), r in sorted(t.items()):
        old = OLD_BUGGY.get((a, rec, v))
        mu3pct = (r["sink_mu3s"] / N_PATCHES * 100
                  if isinstance(r["sink_mu3s"], float) else r["sink_mu3s"])
        if old:
            o_top1, o_sink, o_over = old
            dtop1 = (r["top1_last"] - o_top1
                     if isinstance(r["top1_last"], float) else "MISSING")
            L.append(f"| {ARCH_NAME[a]} | {rec} | {v} | {fmt(o_top1, 3)} | "
                     f"{fmt(r['top1_last'], 3)} | {fmt(dtop1, 3)} | "
                     f"{fmt(o_sink, 3)} | {fmt(r['sink_mad_k5'])} | "
                     f"{fmt(mu3pct, 3)} | {fmt(o_over)} | "
                     f"{fmt(r['oversmooth_pairwise'])} |")
        else:
            L.append(f"| {ARCH_NAME[a]} | {rec} | {v} | — (none existed) | "
                     f"{fmt(r['top1_last'], 3)} | — | — | "
                     f"{fmt(r['sink_mad_k5'])} | {fmt(mu3pct, 3)} | — | "
                     f"{fmt(r['oversmooth_pairwise'])} |")
    L.append("")

    # ── 3. first-ever ViT-B/mixup ────────────────────────────────────────────
    L.append("## 3. ViT-B/16 mixup — FIRST-EVER numbers")
    L.append("")
    L.append("No previous values existed for this cell; everything below is "
             "reported for the first time (from the corrected pipeline).")
    L.append("")
    L.append("| variant | top1_last | sink_mad_k5 | oversmooth_pairwise | "
             "oversmooth_pairwise_nosink | eff_rank |")
    L.append("|---|---|---|---|---|---|")
    for v in ("baseline", "registers", "saga"):
        r = t[("vit_base", "mixup", v)]
        L.append(f"| {v} | {fmt(r['top1_last'], 3)} | {fmt(r['sink_mad_k5'])} "
                 f"| {fmt(r['oversmooth_pairwise'])} | "
                 f"{fmt(r['oversmooth_pairwise_nosink'])} | "
                 f"{fmt(r['eff_rank'], 2)} |")
    L.append("")

    # ── 4. Gate-1 verdict ────────────────────────────────────────────────────
    L.append("## 4. Gate-1 verdict")
    L.append("")
    L.append("Question (per cell): on corrected metrics, does SAGA improve "
             "BOTH sink (sink_mad_k5) and oversmoothing vs baseline, on BOTH "
             "oversmoothing variants, while registers improve sink but worsen "
             "oversmoothing?")
    L.append("")
    L.append("Rule applied: PASS = all 6 clauses true; FAIL = none of the 3 "
             "SAGA clauses true; PARTIAL = anything else. Lower is better for "
             "sink and oversmoothing.")
    L.append("")
    verdicts = {}
    for a, rec in cells:
        verdict, clauses, *_ = cell_verdict(t, a, rec)
        verdicts[(a, rec)] = verdict
        L.append(f"### {ARCH_NAME[a]} / {rec}: **{verdict}**")
        L.append("")
        for name, ok, nums in clauses:
            mark = "TRUE " if ok else "FALSE"
            L.append(f"- [{mark}] {name}: {nums}")
        L.append("")

    counts = {v: sum(1 for x in verdicts.values() if x == v)
              for v in ("PASS", "PARTIAL", "FAIL", "MISSING")}
    if counts["MISSING"]:
        overall = "INCOMPLETE"
    elif counts["PARTIAL"] == counts["FAIL"] == 0:
        overall = "PASS"
    elif counts["PASS"] == counts["PARTIAL"] == 0:
        overall = "FAIL"
    else:
        overall = "PARTIAL"
    L.append(f"### Overall: **{overall}** "
             f"({counts['PASS']} PASS, {counts['PARTIAL']} PARTIAL, "
             f"{counts['FAIL']} FAIL, {counts['MISSING']} MISSING "
             f"of {len(verdicts)} cells)")
    L.append("")
    L.append("The Gate-1 decision itself is the human's; this report only "
             "supplies the numbers.")
    L.append("")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L), encoding="utf-8", newline="\n")
    print(f"wrote {out}")
    for (a, rec), v in sorted(verdicts.items()):
        print(f"  {ARCH_NAME[a]} / {rec}: {v}")
    print(f"  overall: {overall}")


if __name__ == "__main__":
    main()
