#!/usr/bin/env python3
"""
analysis/build_I2_handoff.py
============================
TASK I2 D9 — `docs/I2_HANDOFF.md`, generated.

    python analysis/build_I2_handoff.py   -> docs/I2_HANDOFF.md

Every number is read from `results/frozen/I2_terminal/*/tables/`, the two
`thresholds_cal.json`, and `docs/LOCKED_ANALYSIS.md`; none is typed here, and
the D1 sentence is COPIED out of §1 of LOCKED_ANALYSIS rather than restated,
so the handoff cannot quote a decision the locked document does not carry.
No timestamp goes into the document, so `tests/test_I2_terminal.py` can pin
it byte for byte.

No training, no optimizer, no probe fitting.
"""

import argparse
import csv
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from analysis.i2_decision import (DECISION_CELL, PRIMARY_DIAGNOSTICS,  # noqa: E402
                                  SETTING_NATIVE, SETTING_S11, SETTING_TERM,
                                  SURVIVAL_CUTOFF, decide, load_gaps)

MISSING = "MISSING"
ROOT = "results/frozen/I2_terminal"
LOCKED = "docs/LOCKED_ANALYSIS.md"
OUT = "docs/I2_HANDOFF.md"


def _read(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _num(v):
    if v in (None, "", MISSING):
        return MISSING
    try:
        return float(v)
    except (TypeError, ValueError):
        return MISSING


def _f(v, nd=3):
    return MISSING if v == MISSING or v is None else f"{float(v):.{nd}f}"


def _cell(text):
    """A `|` inside a markdown cell breaks its row; every cell name here is
    `<arch>|<recipe_actual>` (TASK I0 Phase C hit this twice)."""
    return str(text).replace("|", "\\|")


def d1_from_locked(locked=LOCKED):
    """(sentence, signature line) COPIED from §1 of LOCKED_ANALYSIS."""
    text = Path(locked).read_text(encoding="utf-8")
    section = text.split("## 1. Feature stage", 1)[1].split("## 2.", 1)[0]
    quoted = [ln[2:].rstrip() for ln in section.splitlines()
              if ln.startswith("> ")]
    if not quoted:
        raise SystemExit(
            f"{locked} §1 carries no quoted D1 sentence — has D1 been signed?")
    sig_at = next((i for i, ln in enumerate(quoted)
                   if ln.startswith("Signed ")), len(quoted))
    sentence = " ".join(ln for ln in quoted[:sig_at] if ln).strip()
    signature = " ".join(ln for ln in quoted[sig_at:] if ln).strip()
    stage = re.search(r"D1 = `([^`]+)`", sentence)
    return sentence, signature, (stage.group(1) if stage else MISSING)


def build(root=ROOT, locked=LOCKED) -> str:
    root = Path(root)
    cal_t, ev_t = root / "calibration" / "tables", root / "evaluation" / "tables"
    sentence, signature, d1_stage = d1_from_locked(locked)

    cal_gaps = load_gaps(cal_t / "T_I2c_gaps.csv")
    ev_gaps = load_gaps(ev_t / "T_I2c_gaps.csv")
    vc = decide(cal_gaps[DECISION_CELL][0], cell=DECISION_CELL,
                n_pairs=cal_gaps[DECISION_CELL][1])
    ve = decide(ev_gaps[DECISION_CELL][0], cell=DECISION_CELL,
                n_pairs=ev_gaps[DECISION_CELL][1])

    inv = _read(ev_t / "T_I2a_invariance.csv")
    maps = _read(ev_t / "T_I2d_maps.csv")
    sweep = _read(ev_t / "T_I2b_sweep.csv")
    ev_meta = json.loads((ev_t / "build_meta.json").read_text("utf-8"))
    cal_meta = json.loads((cal_t / "build_meta.json").read_text("utf-8"))
    thr = {s: json.loads((root / s / "thresholds_cal.json")
                         .read_text("utf-8"))
           for s in ("calibration", "evaluation")}

    L = []
    w = L.append
    w("# TASK I2 handoff — the terminal patch gate, and the stage every new "
      "patch diagnostic is reported at")
    w("")
    w("**Status: COMPLETE (Phases A / B1 / C1 / B2 / C2). Nothing pending "
      "from the HPC.**  ")
    w("GENERATED by `analysis/build_I2_handoff.py`. Every number below is "
      "read from")
    w("`results/frozen/I2_terminal/*/tables/`, the two `thresholds_cal.json` "
      "and")
    w("`docs/LOCKED_ANALYSIS.md`; none is typed by hand, and the D1 sentence "
      "is COPIED")
    w("out of §1 of that document rather than restated. Re-run the script "
      "after new")
    w("results land and this document updates itself.")
    w("")
    w("## 0. The decision, as signed")
    w("")
    w("> " + sentence)
    w(">")
    w("> " + signature)
    w("")
    w(f"**D1 = `{d1_stage}`.** Every new patch diagnostic in I1, I3, I4 and "
      f"I5 is reported at that")
    w("stage. The final-block quantities are reported beside it with the "
      "`term_1.00`")
    w("and `s11_out` controls, never alone.")
    w("")

    # ── 1. what I2 measured ─────────────────────────────────────────────────
    w("## 1. What I2 measured")
    w("")
    w("Under a CLS-only loss the last block's patch gate receives no gradient "
      "and sits")
    w("at σ(0) = 0.5 in every SAGA checkpoint. I2 asked how much of the "
      "SAGA-vs-baseline")
    w("gap on the patch diagnostics that untrained constant produces, by "
      "overriding it")
    w("with four declared constants and measuring both the classifier and "
      "the patch")
    w("rows at three stages.")
    w("")
    w("| | calibration | evaluation |")
    w("|---|---|---|")
    w(f"| split sha | `{cal_meta['split_sha256'][:16]}…` | "
      f"`{ev_meta['split_sha256'][:16]}…` |")
    w(f"| images | {_read(cal_t / 'T_I2c_gaps.csv')[0]['n_images']} | "
      f"{_read(ev_t / 'T_I2c_gaps.csv')[0]['n_images']} |")
    w(f"| runs | {len(cal_meta['runs_present'])} | "
      f"{len(ev_meta['runs_present'])} |")
    w("| conditions | `native` on all 19; `term_0.25/0.50/0.75/1.00` on the "
      "8 SAGA | same |")
    w("| stages | `s11_out`, `hist`, `s12_post_norm` | same |")
    w("")

    # ── 2. the architectural half ───────────────────────────────────────────
    n_ckpt = len({r["run_id"] for r in inv})
    n_const = len({r["condition_id"] for r in inv})
    n_img = {r["n_images"] for r in inv}
    half = [r for r in inv if r["condition_id"] == "term_0.50"]
    w("## 2. The architectural half, on the evaluation split")
    w("")
    w(f"{n_ckpt} SAGA checkpoints × {n_const} constants × "
      f"{sorted(n_img)[0]} images:")
    w("")
    w("| | measured |")
    w("|---|---|")
    w(f"| max abs logit difference vs native | "
      f"**{max(float(r['max_abs_logit_diff_vs_native']) for r in inv):g}** |")
    w(f"| min top-1 agreement with native | "
      f"**{min(float(r['top1_agreement']) for r in inv):g}** |")
    w(f"| max mean abs ΔNLL | "
      f"**{max(float(r['mean_abs_delta_nll']) for r in inv):g}** |")
    w(f"| `native` ≡ `term_0.50` (φ_L = 0) | "
      f"**{sum(r['phi_L_zero_bit_identical'] == '1' for r in half)} of "
      f"{len(half)}** checkpoints bit-identical |")
    w(f"| max abs Δ`cos_all` at `hist` under `term_1.00` | "
      f"{max(float(r['max_abs_cos_all_diff_hist']) for r in inv if r['condition_id'] == 'term_1.00'):.4f} |")
    w("")
    w("Proposition 2 holds **exactly, not approximately**: a CLS-only readout "
      "cannot")
    w("see the terminal patch gate, and φ_L = 0 is the weight-decay fixed "
      "point it was")
    w("predicted to be on every trained SAGA checkpoint in the cohort. The "
      "patch")
    w("diagnostics at the same stage move while the classifier does not — "
      "which is the")
    w("panel, and `figures_data/frozen/F5A_terminal.npz` carries it: the "
      "diagnostic")
    w("against the terminal constant, per pair, at both stages, with the "
      "zero line.")
    w("")

    # ── 3. calibration vs evaluation ────────────────────────────────────────
    w("## 3. The decision rule, and what evaluation says about it")
    w("")
    w(f"`analysis/i2_decision.decide()` was committed in Phase A, before any "
      f"result existed. It votes on the `{_cell(DECISION_CELL)}` cell "
      f"({vc['n_pairs']} pairs) at a conventional survival cutoff of "
      f"{SURVIVAL_CUTOFF:.2f}.")
    w("")
    w(f"**D1 was decided on CALIBRATION: branch {vc['branch']}, "
      f"`{vc['d1_stage']}`.** It was then run ONCE on the evaluation tables "
      f"as a")
    w(f"consistency check and returned **branch {ve['branch']}, "
      f"`{ve['d1_stage']}`** — "
      + ("the same branch. " if vc["branch"] == ve["branch"]
         else "a DIFFERENT branch. ")
      + "That check is reported, not acted on: D1 is signed on calibration "
        "by design.")
    w("")
    w("| diagnostic | survival cal | survival eval | survival_s11 cal | "
      "survival_s11 eval |")
    w("|---|---|---|---|---|")
    for d in PRIMARY_DIAGNOSTICS:
        mark = "" if vc["passes_term"][d] else " **✗**"
        w(f"| `{d}` | {_f(vc['survival'][d])}{mark} | "
          f"{_f(ve['survival'][d])} | {_f(vc['survival_s11'][d])} | "
          f"{_f(ve['survival_s11'][d])} |")
    w("")
    w(f"The same {len(vc['failing_diagnostics_term'])} diagnostics fail the "
      f"bypass test on both splits "
      f"(`{'`, `'.join(vc['failing_diagnostics_term'])}`)"
      + (", and every survival agrees to within "
         f"{max(abs(ve['survival'][d] - vc['survival'][d]) for d in PRIMARY_DIAGNOSTICS if MISSING not in (ve['survival'][d], vc['survival'][d])):.3f}."
         if vc["failing_diagnostics_term"] == ve["failing_diagnostics_term"]
         else "."))
    w("")
    w("The non-voting cells, on both splits:")
    w("")
    w("| cell | n | branch cal | branch eval |")
    w("|---|---|---|---|")
    for c in sorted(ev_gaps):
        if c == DECISION_CELL:
            continue
        a = decide(cal_gaps[c][0], cell=c, n_pairs=cal_gaps[c][1])
        b = decide(ev_gaps[c][0], cell=c, n_pairs=ev_gaps[c][1])
        w(f"| `{_cell(c)}` | {b['n_pairs']} | {a['branch']} | {b['branch']} |")
    w("")

    # ── 4. thresholds ───────────────────────────────────────────────────────
    w("## 4. Thresholds")
    w("")
    w("`tau_canon` is the historical per-cell value, calibrated at the last "
      "block on")
    w("the DISCOVERY split; it is defined at `hist` and nowhere else, so "
      "`count_fixed_canon`")
    w("is the literal `MISSING` at every other stage. `tau_cal` re-runs the "
      "SAME recipe")
    w("(`tools/compute_fixed_thr.per_image_mad_thresholds`) per stage on the "
      "split being")
    w("evaluated, from each cell's canon-designated baseline.")
    w("")
    w("| cell | `tau_canon` | `tau_cal[hist]` cal | `tau_cal[hist]` eval | "
      "`tau_cal[s11_out]` eval | `tau_cal[s12_post_norm]` eval |")
    w("|---|---|---|---|---|---|")
    for c in sorted(thr["evaluation"]["tau_cal"]):
        e = thr["evaluation"]["tau_cal"][c]
        k = thr["calibration"]["tau_cal"][c]
        src = thr["evaluation"]["sources"][c]
        w(f"| `{_cell(c)}` | {src['tau_canon']} | {k['hist']:.5f} | "
          f"{e['hist']:.5f} | {e['s11_out']:.5f} | {e['s12_post_norm']:.5f} |")
    w("")

    # ── 5. s12_post_norm ────────────────────────────────────────────────────
    empty = [r for r in maps if r["rho_spatial"] == MISSING]
    stages = sorted({r["stage"] for r in empty})
    if empty:
        w("## 5. `s12_post_norm` is not a candidate reporting stage")
        w("")
        w(f"{len(empty)} of the {len(maps)} rows of `T_I2d_maps.csv` carry "
          f"`MISSING` for every spatial")
        w(f"statistic, all of them at `{stages[0]}`, because the exceedance "
          f"map there has ZERO")
        w("mass. After the final LayerNorm the patch norms are close to "
          "uniform, so nothing")
        w("exceeds either threshold and a map with no mass has no spatial "
          "arrangement to")
        w("correlate. For one baseline on this split:")
        w("")
        w("| run | stage | `norm_p50` | `norm_max` | `count_mad` | "
          "`count_fixed_cal` |")
        w("|---|---|---|---|---|---|")
        ref = "e2r_vits_mixup_baseline_s1"
        for r in sweep:
            if r["run_id"] == ref and r["condition_id"] == "native":
                w(f"| `{ref}` | `{r['stage']}` | {_f(_num(r['norm_p50']))} | "
                  f"{_f(_num(r['norm_max']))} | {_f(_num(r['count_mad']))} | "
                  f"{_f(_num(r['count_fixed_cal']))} |")
        w("")
        w("That is a property of the stage, not a gap in the results.")
        w("")

    # ── 6. where everything lives ───────────────────────────────────────────
    w("## 6. Where everything lives")
    w("")
    w("| what | path |")
    w("|---|---|")
    w("| conditions (the only place they are defined) | "
      "`configs/frozen/I2_terminal.yaml` |")
    w("| job file | `scripts/jobs/frozen_I2.sbatch` (the split is an "
      "ARGUMENT) |")
    w("| per-split sweep | "
      "`results/frozen/I2_terminal/<split_name>/<run_id>/` |")
    w("| per-stage thresholds | "
      "`results/frozen/I2_terminal/<split_name>/thresholds_cal.json` |")
    w("| tables | "
      "`results/frozen/I2_terminal/<split_name>/tables/T_I2a-e*.csv` |")
    w("| the decision, and the note behind it | "
      "`analysis/i2_decision.py`, `results/frozen/I2_terminal/D1_proposal.md` |")
    w("| figure data | `figures_data/frozen/F5A_terminal.npz` |")
    w("| per-image primary diagnostics (evaluation) | "
      "`figures_data/frozen/I2_evaluation_primary.npz` |")
    w("| tests | `tests/test_I2_terminal.py` |")
    w("")
    w("The evaluation `records.parquet` / `diag.parquet` stay on the cluster "
      "(19 runs ×")
    w("10,000 images). Each run's committed `run_meta.json` records their "
      "sha256 and")
    w("byte size, and the primary pack above carries the per-image values "
      "the")
    w("bootstrap resamples — so every number in these tables regenerates "
      "from the")
    w("repository.")
    w("")

    # ── 7. what I2 does not settle ──────────────────────────────────────────
    w("## 7. What I2 does NOT settle")
    w("")
    w("- I2 is descriptive. It shows a patch statistic moving while the "
      "classifier does")
    w("  not; it establishes no mechanism, and it cannot on its own justify "
      "acceptance.")
    w("- The 0.70 survival cutoff is conventional. §3(a) of "
      "`D1_proposal.md` records how")
    w("  close the branch was and what cutoff would have changed it.")
    w("- `D5` is still open in `docs/LOCKED_ANALYSIS.md` and still blocks "
      "I4: the")
    w("  prevalence map at the INPUT to block 7/8 does not exist, and I1 "
      "owns it.")
    w("- `docs/LOCKED_ANALYSIS.md` remains a DRAFT. D1-D4 and D6-D8 are "
      "closed; freezing")
    w("  the document is a separate act.")
    return "\n".join(L) + "\n"


def main():
    p = argparse.ArgumentParser(description="Generate docs/I2_HANDOFF.md.")
    p.add_argument("--root", default=ROOT)
    p.add_argument("--locked", default=LOCKED)
    p.add_argument("--out", default=OUT)
    args = p.parse_args()
    text = build(args.root, args.locked)
    Path(args.out).write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {args.out}: {len(text.splitlines())} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
