#!/usr/bin/env python3
"""
analysis/build_A_handoff.py
===========================
`docs/A_HANDOFF.md` — TASK A / A12, Phase C.

    python analysis/build_A_handoff.py

GENERATED. Every number is read from `results/frozen/I1_spatial/tables/`,
`results/frozen/I6_external/tables/`, `configs/frozen/I4_masks.json` and the
committed threshold files; none is typed by hand, and the I6 prediction is
COPIED out of `configs/frozen/I6_models.yaml` rather than restated. Re-run
after new results land and the document updates itself.

A `MISSING` or `PENDING` cell is carried through as it stands. It is never
averaged, never dropped and never replaced by a guess.

No training, no optimizer, no probe fitting, no selection by any loss.
"""

import argparse
import csv
import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from saga.frozen import external as ext  # noqa: E402
from saga.run_registry import git_sha  # noqa: E402

MISSING = "MISSING"
I1_TABLES = Path("results/frozen/I1_spatial/tables")
I6_TABLES = Path("results/frozen/I6_external/tables")
MASKS = Path("configs/frozen/I4_masks.json")
OUT = Path("docs/A_HANDOFF.md")


def read(path):
    p = Path(path)
    if not p.exists():
        return []
    with open(p, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def cell(v) -> str:
    """A value safe inside a markdown table cell — `arch|recipe` has a pipe
    in it, and an unescaped pipe silently shifts every later column."""
    return str(v).replace("|", r"\|")


def fnum(v, nd=4):
    try:
        return f"{float(v):.{nd}f}"
    except (TypeError, ValueError):
        return str(v)


def build(*, out=OUT, git_sha_value=None, i1_tables=I1_TABLES,
          i6_tables=I6_TABLES, masks=MASKS,
          registry_path="configs/frozen/I6_models.yaml") -> Path:
    sha = git_sha_value if git_sha_value else git_sha()
    registry = ext.load_registry(registry_path)
    L = []
    A = L.append

    A("# TASK A handoff — I1 (spatial structure) and I6 (external checkpoints)")
    A("")
    A("GENERATED by `analysis/build_A_handoff.py`. Every number is read from "
      "the committed tables; none is typed by hand, and the I6 prediction is "
      "COPIED out of `configs/frozen/I6_models.yaml` rather than restated.")
    A("")
    A(f"git sha `{sha}`")
    A("")

    # ── D5 ───────────────────────────────────────────────────────────────────
    A("## 1. D5 — the masks I4 perturbs")
    A("")
    if Path(masks).exists():
        raw = Path(masks).read_bytes()
        doc = json.loads(raw.decode("utf-8"))
        A(f"| | |")
        A(f"|---|---|")
        A(f"| file | `{Path(masks).as_posix()}` |")
        A(f"| sha256 | `{hashlib.sha256(raw).hexdigest()}` |")
        A(f"| cell | `{cell(doc['cell'])}` |")
        A(f"| basis | `{doc['basis']}` |")
        A(f"| discovery split | `{doc['discovery_split_name']}` |")
        A("")
        A("| stage | enters | paper block | ring composition | control "
          "overlap (observed) | expected |")
        A("|---|---|---|---|---|---|")
        for stage, m in sorted(doc["masks"].items()):
            comp = ", ".join(f"r{r}:{n}" for r, n in
                             sorted(m["primary_mask"]["ring_composition"].items()))
            obs = m["control_overlap_observed"]
            A(f"| `{stage}` | `blocks[{m['block_entered_0based']}]` | "
              f"{m['paper_block_1based']} | {comp} | {min(obs)}–{max(obs)} | "
              f"{m['control_overlap_expected']} |")
        A("")
        A("Is the perturbed address the reported address? Spearman between "
          "each source run's DISCOVERY block-input map and the SAME run's "
          "`s11_out` map on EVALUATION:")
        A("")
        A("| stage | ρ range | ring-adjusted ρ range |")
        A("|---|---|---|")
        for stage, m in sorted(doc["masks"].items()):
            rr = [r["rho"] for r in m["rho_vs_reporting_stage"]["per_run"]
                  if isinstance(r.get("rho"), float)]
            ra = [r["resid_rho"] for r in m["rho_vs_reporting_stage"]["per_run"]
                  if isinstance(r.get("resid_rho"), float)]
            A(f"| `{stage}` | {min(rr):.4f}–{max(rr):.4f} | "
              f"{min(ra):.4f}–{max(ra):.4f} |" if rr and ra
              else f"| `{stage}` | {MISSING} | {MISSING} |")
        A("")
        A("**D5 is not closed by this document.** Closing it in "
          "`docs/LOCKED_ANALYSIS.md` §5 with the sha256 above, and freezing "
          "that document, are the human's acts.")
    else:
        A(f"`{Path(masks).as_posix()}` does not exist — run "
          f"`analysis/build_D5_masks.py`.")
    A("")

    # ── I1 headlines ─────────────────────────────────────────────────────────
    A("## 2. I1 — the headline of each table")
    A("")
    A("Reporting split: `evaluation`. Selection material (`val_diag_split`) "
      "is tabulated separately under `tables_discovery/` and appears here "
      "only as the source of a D5 mask.")
    A("")

    a = read(Path(i1_tables) / "T_I1a_prevalence.csv")
    base = [r for r in a if r["variant"] == "baseline"
            and r["basis"] == "fixed_cal" and r["condition_id"] == "native"]
    A("### T_I1a — prevalence")
    A("")
    if base:
        A("Ring-0 vs ring-1 mean frequency, baselines, `fixed_cal`:")
        A("")
        A("| run | cell | stage | ring 0 | ring 1 | peak | mass | Gini excess "
          "| η² | split-half ρ |")
        A("|---|---|---|---|---|---|---|---|---|---|")
        for r in sorted(base, key=lambda x: (x["cell"], x["run_id"],
                                             x["stage"])):
            A(f"| `{r['run_id']}` | `{cell(r['cell'])}` | `{r['stage']}` | "
              f"{fnum(r['ring0_freq'])} | {fnum(r['ring1_freq'])} | "
              f"{r['peak_ring']} | {fnum(r['mass'],2)} | "
              f"{fnum(r['gini_excess'])} | {fnum(r['eta2_pos'],5)} | "
              f"{fnum(r['split_half_rho'])} |")
        A("")
        peaks = {}
        for r in base:
            peaks.setdefault(r["recipe_actual"], []).append(int(r["peak_ring"]))
        for recipe, v in sorted(peaks.items()):
            A(f"- `{recipe}` baselines: {sum(1 for p in v if p == 1)} of "
              f"{len(v)} (run x stage) peak at ring 1")
    else:
        A(f"`T_I1a_prevalence.csv` {MISSING}")
    A("")

    A("### T_I1b — the scale-only null")
    A("")
    b = read(Path(i1_tables) / "T_I1b_scale_null.csv")
    if b:
        A("| cell | tag | stage | c | ρ(baseline, SAGA) | ρ(rescaled, SAGA) | "
          "ρ(baseline, other seed) | MAD count invariant |")
        A("|---|---|---|---|---|---|---|---|")
        for r in b:
            A(f"| `{cell(r['cell'])}` | {r['provenance_tag']} | "
              f"`{r['stage']}` | {fnum(r['c_matched'])} | "
              f"{fnum(r['rho_baseline_vs_saga'])} | "
              f"{fnum(r['rho_rescaled_vs_saga'])} | "
              f"{fnum(r['rho_baseline_vs_baseline'])} | "
              f"{r['mad_count_invariant']} |")
    else:
        A("**PENDING.** `T_I1b_scale_null.csv` is not in the repository. The "
          "scale null rescales a NORM FIELD, and `norms_*.npz` is git-ignored "
          "and lives on the cluster, so it is produced by one command THERE "
          "— on a login node, numpy only, no GPU:")
        A("")
        A("```")
        A("python analysis/frozen_I1_scale_null.py --split evaluation")
        A("```")
        A("")
        A("This is a gap in the task file's phase plan, not a choice: §7 "
          "gives T_I1b's data as the norms, §10 puts T_I1b in a local phase, "
          "and §4 keeps the norms on the cluster. The three cannot all hold.")
    A("")

    A("### T_I1c — the recipe contrast")
    A("")
    c = read(Path(i1_tables) / "T_I1c_recipe.csv")
    rows = [r for r in c if r["statistic"] == "rho_mean"
            and r["basis"] == "fixed_cal"]
    if rows:
        A("| stage | within-recipe mean ρ | cross-recipe mean ρ | n cross |")
        A("|---|---|---|---|")
        by_stage = {}
        for r in rows:
            by_stage.setdefault(r["stage"], {})[r["question"]] = r
        for stage in sorted(by_stage):
            w = by_stage[stage].get("within_recipe_map_correlation")
            x = by_stage[stage].get("cross_recipe_map_correlation")
            A(f"| `{stage}` | {fnum(w['value']) if w else MISSING} | "
              f"{fnum(x['value']) if x else MISSING} | "
              f"{x['n'] if x else 0} |")
        A("")
        ord_rows = [r for r in c if r["statistic"] == "ring1_minus_ring0"
                    and r["basis"] == "fixed_cal" and r["stage"] == "s11_out"]
        if ord_rows:
            A("Ring-1 minus ring-0 at `s11_out`, with its image-level "
              "bootstrap CI (10,000 resamples, seed 0):")
            A("")
            A("| recipe | run | value | 95% CI |")
            A("|---|---|---|---|")
            for r in sorted(ord_rows, key=lambda x: (x["recipe_group"],
                                                     x["subject"])):
                A(f"| {r['recipe_group']} | `{r['subject']}` | "
                  f"{fnum(r['value'])} | [{fnum(r['ci_lo'])}, "
                  f"{fnum(r['ci_hi'])}] |")
    else:
        A(f"`T_I1c_recipe.csv` {MISSING}")
    A("")

    A("### T_I1d — seed stability")
    A("")
    d = [r for r in read(Path(i1_tables) / "T_I1d_seed_stability.csv")
         if r["subject"] == "MEAN" and r["basis"] == "fixed_cal"]
    if d:
        A("| cell | stage | mean ρ | ring-adjusted ρ | pairs |")
        A("|---|---|---|---|---|")
        for r in sorted(d, key=lambda x: (x["cell"], x["stage"])):
            A(f"| `{cell(r['cell'])}` | `{r['stage']}` | {fnum(r['rho'])} | "
              f"{fnum(r['resid_rho'])} | {r['n_transforms']} |")
    A("")

    A("### T_I1e — η²")
    A("")
    e = [r for r in read(Path(i1_tables) / "T_I1e_eta2.csv")
         if r["variant"] == "baseline" and r["basis"] == "fixed_cal"
         and r["stage"] == "s11_out"]
    if e:
        A("Baselines at `s11_out`, `fixed_cal`, with image-level bootstrap CI:")
        A("")
        A("| run | cell | η² | 95% CI |")
        A("|---|---|---|---|")
        for r in sorted(e, key=lambda x: (x["cell"], x["run_id"])):
            A(f"| `{r['run_id']}` | `{cell(r['cell'])}` | "
              f"{fnum(r['eta2_pos'],5)} | [{fnum(r['ci_lo'],5)}, "
              f"{fnum(r['ci_hi'],5)}] |")
    A("")

    A("### T_I1f — the block-input stages")
    A("")
    f = [r for r in read(Path(i1_tables) / "T_I1f_blockinput.csv")
         if r["variant"] == "baseline" and r["basis"] == "fixed_cal"]
    if f:
        rr = [float(r["rho_vs_s11_out"]) for r in f
              if r["rho_vs_s11_out"] not in (MISSING, "")]
        ra = [float(r["resid_rho_vs_s11_out"]) for r in f
              if r["resid_rho_vs_s11_out"] not in (MISSING, "")]
        A(f"Across {len(f)} baseline (run x stage) rows on the reporting "
          f"split, the block-input map correlates with the SAME run's "
          f"`s11_out` map at ρ = {min(rr):.4f}–{max(rr):.4f}, and at "
          f"{min(ra):.4f}–{max(ra):.4f} after ring adjustment.")
        A("")
        A("| run | stage | mass | ring 0 | ring 1 | peak | ρ vs `s11_out` | "
          "ring-adjusted |")
        A("|---|---|---|---|---|---|---|---|")
        for r in sorted(f, key=lambda x: (x["run_id"], x["stage"])):
            A(f"| `{r['run_id']}` | `{r['stage']}` | {fnum(r['mass'],2)} | "
              f"{fnum(r['ring0_freq'])} | {fnum(r['ring1_freq'])} | "
              f"{r['peak_ring']} | {fnum(r['rho_vs_s11_out'])} | "
              f"{fnum(r['resid_rho_vs_s11_out'])} |")
    A("")

    A("### T_I1g — variant maps")
    A("")
    g = [r for r in read(Path(i1_tables) / "T_I1g_variant_maps.csv")
         if r["basis"] == "fixed_cal" and r["condition_id"] == "native"
         and r["rho"] not in (MISSING, "")]
    if g:
        agg = {}
        for r in g:
            k = (r["cell"], r["variant"], r["stage"])
            agg.setdefault(k, []).append(r)
        A("Mean over same-provenance pairs, `fixed_cal`, `native`:")
        A("")
        A("| cell | variant | stage | n | ρ | ring-adjusted ρ | Δring-1 share "
          "| Δmass |")
        A("|---|---|---|---|---|---|---|---|")
        for (cl, var, stage), rs in sorted(agg.items()):
            m = lambda col: sum(float(x[col]) for x in rs) / len(rs)  # noqa: E731
            A(f"| `{cell(cl)}` | {var} | `{stage}` | {len(rs)} | "
              f"{m('rho'):.4f} | {m('resid_rho'):.4f} | "
              f"{m('delta_ring1_share'):+.4f} | {m('delta_mass'):+.2f} |")
    A("")

    A("### T_I1h — do I1 and I2 agree?")
    A("")
    h = read(Path(i1_tables) / "T_I1h_agreement.csv")
    if h:
        ident = sum(int(r["identical"]) for r in h)
        worst = max(int(r["max_abs_count_diff"]) for r in h)
        A(f"I1 recaptured `s11_out` and `hist` in the same forward passes "
          f"that produced the block-input stages, so both work packages "
          f"measured them independently. **{ident} of {len(h)} rows have "
          f"bit-identical per-position counts; the worst disagreement "
          f"anywhere is {worst}.**")
    A("")

    # ── I6 ───────────────────────────────────────────────────────────────────
    A("## 3. I6 — the external checkpoints")
    A("")
    A("**The prediction, copied verbatim from "
      "`configs/frozen/I6_models.yaml`, which was committed before any "
      "external weight was downloaded:**")
    A("")
    for line in registry["prediction"].split(". "):
        if line.strip():
            A("> " + line.strip().rstrip(".") + ".")
    A("")
    A(f"Registered {registry['registered_at']}; source "
      f"`{registry['prediction_source']}`. The outcome is computed by "
      f"`saga.frozen.external.prediction_outcome` from the rule registered "
      f"beside it — nobody types \"met\" into a table.")
    A("")
    i6 = [r for r in read(Path(i6_tables) / "T_I6a_external.csv")
          if r["basis"] == "fixed_cal"]
    if i6:
        A("| model | group | stage | grid | peak ring | ring-1 peak | Gini "
          "excess | outcome |")
        A("|---|---|---|---|---|---|---|---|")
        for r in sorted(i6, key=lambda x: (x["group"], x["model_id"],
                                           x["stage"])):
            A(f"| `{r['model_id']}` | {r['group']} | `{r['stage']}` | "
              f"{r['grid_side']}× | {r['peak_ring']} | "
              f"{'yes' if r['ring_1_peak'] == '1' else 'no'} | "
              f"{fnum(r['gini_excess'])} | **{r['prediction_outcome']}** |")
        A("")
        met = sum(1 for r in i6 if r["prediction_outcome"] == "met")
        nm = sum(1 for r in i6 if r["prediction_outcome"] == "not met")
        na = sum(1 for r in i6 if r["prediction_outcome"] == "not applicable")
        A(f"{met} met, {nm} not met, {na} not applicable, over "
          f"{len(i6)} (model x stage) rows on the `fixed_cal` basis.")
        A("")
        misses = sorted({r["model_id"] for r in i6
                         if r["prediction_outcome"] == "not met"})
        if misses:
            A(f"**The prediction is not met for: "
              + ", ".join(f"`{m}`" for m in misses) + ".** Either outcome is "
              "reported; these are the rows that matter most and they are "
              "stated here rather than buried.")
    else:
        A(f"`T_I6a_external.csv` {MISSING}")
    A("")
    A("Three of the nine models — every patch-14 DINOv2 — are natively "
      "518-pixel models run here at 224, with the position embedding "
      "interpolated to a 16×16 grid. Their rows are results about those "
      "models AT 224, not about them as published; `resolution_deviation` "
      "marks them in the table.")
    A("")

    # ── limits ───────────────────────────────────────────────────────────────
    A("## 4. What Track A does NOT settle")
    A("")
    A("- **I1 is descriptive.** It measures where exceedances fall and how "
      "stable that arrangement is. It establishes no mechanism, and a map "
      "correlation between two checkpoints licenses a statement about two "
      "maps and nothing else.")
    A("- **The scale null tests ONE alternative explanation, not all of "
      "them.** It asks whether a single multiplicative rescaling of the norm "
      "field reproduces the variant's map. A rescaling that varied by "
      "position, or any other confound, is untouched by it.")
    A("- **I6 tests PRESENCE, not cause.** The nine public checkpoints "
      "differ from this cohort and from each other in training data, "
      "objective, augmentation, patch size, depth and input resolution "
      "simultaneously. A model that shows the pattern shows it; the recipe "
      "grouping is a pre-registered prediction about which models will, not "
      "an identified cause. Nothing is pooled across models or groups.")
    A("- **The permutation reference is approximate for a bordered map.** "
      "Every spatial p here assumes exchangeability under the 8 dihedral "
      "transforms and all torus rolls, and a roll wraps the border onto the "
      "interior. Every p is approximate in the same direction.")
    A("- **D5's masks are selected on discovery data.** That is what makes "
      "I4 non-circular, and it is also why the mask coordinates are an input "
      "to an experiment rather than a finding.")
    A("- **`docs/LOCKED_ANALYSIS.md` is still a DRAFT.** D5 is the last open "
      "decision; closing it and freezing the document are the human's acts.")
    A("")

    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    return out


def main():
    p = argparse.ArgumentParser(description="Generate docs/A_HANDOFF.md.")
    p.add_argument("--out", default=str(OUT))
    args = p.parse_args()
    path = build(out=args.out)
    print(f"wrote {path} ({len(path.read_text(encoding='utf-8').splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
