#!/usr/bin/env python3
"""
analysis/build_e2r_first_look.py
================================
TASK-06B Part 3.6: generate results/notes/e2r_first_look.md. Every number
is read or computed from files under results/; facts only.

    python analysis/build_e2r_first_look.py \
        [--out results/notes/e2r_first_look.md]
"""

import argparse
import csv
import json
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
from analysis.check_eval_consistency import check_run  # noqa: E402

ARCH_NAME = {"vit_small": "ViT-S/16", "vit_base": "ViT-B/16"}
MISSING = "MISSING"


def fmt(x, nd=4):
    if isinstance(x, float):
        return f"{x:.{nd}f}"
    return str(x)


def git_sha():
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"],
                                       text=True).strip()[:12]
    except Exception:
        return "unknown"


def sec_header():
    return [
        "# e2r first look — pooled statistics & first mechanism read "
        "(TASK-06B Part 3)",
        "",
        f"Generated by `analysis/build_e2r_first_look.py`; git `{git_sha()}`,"
        f" {datetime.now(timezone.utc).date().isoformat()}. All numbers from "
        "files under `results/`. Facts only — framing is the human's.",
        "",
        "**Erratum recap** (full proof: `results/notes/recipe_erratum.md`): "
        "cell identity comes from the RESOLVED training config, never a "
        "directory name. Every legacy e2 run trained WITH MixUp+CutMix — "
        "including all `*_nomix` directories (ViT-S proven from committed "
        "code+configs; ViT-B resolved by the Part-2 harvest below). The "
        "only mixup-free runs in the project are the four e2r ViT-S "
        "true-nomix runs.",
        "",
    ]


def sec_vitb_resolution():
    L = ["## 1. ViT-B recipe resolution (Part-2 harvest)", ""]
    for p in sorted(Path("results/legacy/resolved_configs").glob(
            "ViT-B_*_nomix.yaml")):
        aug = yaml.safe_load(open(p))["augmentation"]
        L.append(f"- `{p.name}`: mixup_alpha={aug['mixup_alpha']}, "
                 f"cutmix_alpha={aug['cutmix_alpha']}")
    L += ["",
          "-> `recipe_actual = mixup` for the legacy ViT-B nomix-dir trio "
          "(all three completed at epoch 299 per the TASK-02C forensics); "
          "they join the ViT-B/mixup cell as its legacy repeats. The VOID "
          "legacy ViT-B mixup-dir trio (training never completed) appears "
          "nowhere. Manifest updated (`recipe_actual` column).",
          ""]
    return L


def sec_consistency():
    L = ["## 2. Eval <-> log.csv consistency (all 10 e2r runs)", ""]
    warns = 0
    for run_dir in sorted(Path("results/runs").glob("e2r_*")):
        if not run_dir.is_dir():
            continue
        status, msg = check_run(run_dir, 0.02)
        if status == "warn":
            warns += 1
            L.append(f"- {msg}")
    if warns == 0:
        L.append("- no warnings: every eval(last) matches its epoch-299 "
                 "log row within 0.02, and no run is truncated.")
    else:
        L.append("")
        L.append("Cause of the deltas (established): `tools/eval.py` runs "
                 "the exact evaluator in fp32 (`\"amp\": \"off\"` in the "
                 "eval JSONs) while the trainer's per-epoch validation ran "
                 "under bf16 autocast — a ±0.03-0.04 top-1 difference is "
                 "~15-20 flipped images of 50000 from precision alone. The "
                 "eval JSONs are the paper numbers.")
    L.append("")
    return L


def load_pooled():
    rows = list(csv.DictReader(open("results/tables/e2_pooled.csv",
                                    newline="")))
    return rows


def sec_pooled(rows):
    metrics_show = ["top1_last", "top1_best", "sink_fixed_canon",
                    "sink_mad_k5", "oversmooth_pairwise",
                    "oversmooth_pairwise_nosink", "eff_rank"]
    header = ("| variant | kind | provenance | n | "
              + " | ".join(metrics_show) + " |")
    sep = "|" + "---|" * (4 + len(metrics_show))

    L = ["## 3. Pooled table (`results/tables/e2_pooled.csv`; the CSV also "
         "carries cls_norm_ratio/cls_attn_share and Welch lines)", ""]
    cells = []
    for r in rows:
        key = (r["arch"], r["recipe_actual"])
        if key not in cells:
            cells.append(key)
    for arch, rec in cells:
        n_note = (" — n=2: SE stated but UNRELIABLE at this repeat count "
                  "(Part-3 amendment)" if rec == "nomix" else "")
        L += [f"### {ARCH_NAME[arch]} | recipe_actual={rec}{n_note}", "",
              header, sep]
        for r in rows:
            if (r["arch"], r["recipe_actual"]) != (arch, rec):
                continue
            if r["kind"] in ("welch_t", "welch_p"):
                continue
            vals = " | ".join(str(r[m]) for m in metrics_show)
            L.append(f"| {r['variant']} | {r['kind']} | {r['provenance']} "
                     f"| {r['n']} | {vals} |")
        L.append("")
    return L


def sec_significance(rows):
    expected = {"legacy-mixupdir": -0.13, "legacy-nomixdir": 0.57,
                "s1": 0.52, "s2": 0.88}
    deltas = {r["provenance"]: float(r["top1_last"])
              for r in rows
              if (r["arch"], r["recipe_actual"], r["variant"], r["kind"])
              == ("vit_small", "mixup", "saga", "paired_delta")}
    stat = {r["kind"]: r for r in rows
            if (r["arch"], r["recipe_actual"], r["variant"])
            == ("vit_small", "mixup", "saga")
            and r["kind"] in ("paired_delta_mean", "paired_delta_se",
                              "significant_2xSE", "welch_p")}
    mean = float(stat["paired_delta_mean"]["top1_last"])
    se = float(stat["paired_delta_se"]["top1_last"])
    sig = stat["significant_2xSE"]["top1_last"]
    L = ["## 4. ViT-S/mixup SAGA paired deltas — the human's arithmetic, "
         "verified from files", "",
         "| repeat pair | delta top1_last (exact eval) | human's expected |",
         "|---|---|---|"]
    for tag in ("legacy-mixupdir", "legacy-nomixdir", "s1", "s2"):
        L.append(f"| {tag} | {deltas[tag]:+.3f} | {expected[tag]:+.2f} |")
    L += ["",
          f"Mean = {mean:+.4f}, SE = {se:.4f}, 2xSE = {2 * se:.4f} -> "
          f"`significant_2xSE` = {sig} "
          f"({'|mean| > 2xSE' if sig == '1' else '|mean| <= 2xSE'}).",
          "",
          "The s1 pair differs from the expected +0.52 because the expected "
          "value was read from log.csv (bf16 validation); the exact fp32 "
          "eval files give "
          f"{deltas['s1']:+.3f}. Same cause as section 2. Welch p (unpaired "
          f"robustness line): {stat['welch_p']['top1_last']}.",
          ""]
    return L


def sec_vitb_sink(rows):
    vals = {}
    for r in rows:
        if (r["arch"], r["recipe_actual"], r["kind"], r["provenance"]) == \
                ("vit_base", "mixup", "repeat", "s1"):
            vals[r["variant"]] = (r["sink_fixed_canon"], r["sink_mad_k5"])
    canon = json.load(open("results/diagsplit/fixed_thresholds_canon.json"))
    tau = canon["vit_base|mixup"]
    L = ["## 5. ViT-B/mixup: canon-tau vs MAD sink ordering (new seeded "
         "runs, diag_final_last)", "",
         f"| variant | sink_fixed_canon (tau={tau:.2f}) | sink_mad_k5 |",
         "|---|---|---|"]
    for v in ("baseline", "saga"):
        c, m = vals[v]
        L.append(f"| {v} (s1) | {c} | {m} |")
    c_b, m_b = (float(vals["baseline"][0]), float(vals["baseline"][1]))
    c_s, m_s = (float(vals["saga"][0]), float(vals["saga"][1]))
    L += ["",
          f"Ordering: canon says SAGA {'<' if c_s < c_b else '>'} baseline; "
          f"MAD says SAGA {'<' if m_s < m_b else '>'} baseline — the "
          "legacy pattern (fixed-threshold and MAD disagreeing in exactly "
          "this direction on ViT-B) REPRODUCES on clean, completed, seeded "
          "runs.",
          ""]
    return L


def sec_trainloss(pooled_rows):
    vals = {}
    for run in ("e2r_vits_mixup_baseline_s1", "e2r_vits_mixup_baseline_s2",
                "e2r_vits_nomix_baseline_s1", "e2r_vits_nomix_baseline_s2"):
        rows = list(csv.DictReader(
            open(Path("results/runs") / run / "log.csv", newline="")))
        final = max(rows, key=lambda r: int(r["epoch"]))
        vals[run] = float(final["train_loss"])
    L = ["## 6. Final-epoch train_loss, nomix vs mixup baselines "
         "(Part-3 amendment)", "",
         "| run | train_loss (epoch 299) |", "|---|---|"]
    for run, v in vals.items():
        L.append(f"| {run} | {v:.4f} |")
    mix = np.mean([v for k, v in vals.items() if "mixup" in k])
    nom = np.mean([v for k, v in vals.items() if "nomix" in k])
    # the top-1 regime gap, computed from the pooled cell means (never typed)
    cell_mean = {(r["arch"], r["recipe_actual"], r["variant"]):
                 float(r["top1_last"])
                 for r in pooled_rows
                 if r["kind"] == "mean" and r["top1_last"] != MISSING}
    gap = (cell_mean[("vit_small", "mixup", "baseline")]
           - cell_mean[("vit_small", "nomix", "baseline")])
    L += ["",
          f"Mean final train_loss: mixup baselines {mix:.4f}, true-nomix "
          f"baselines {nom:.4f} (difference {mix - nom:+.4f}) — while "
          f"true-nomix baseline val top-1 sits {gap:.2f} points BELOW the "
          "mixup-cell baseline mean (section 3).",
          ""]
    return L


def sec_gradphi():
    rows = list(csv.DictReader(open("results/figures_data/gradphi.csv",
                                    newline="")))
    by = defaultdict(list)
    per_layer = defaultdict(lambda: defaultdict(list))
    per_epoch = defaultdict(lambda: defaultdict(list))
    for r in rows:
        v = float(r["grad_phi_norm"])
        by[r["recipe"]].append(v)
        per_layer[r["recipe"]][int(r["layer"])].append(v)
        per_epoch[r["recipe"]][int(r["epoch"])].append(v)
    L = ["## 7. grad-phi (epochs 0-30; the two instrumented ViT-S SAGA s1 "
         "runs; figure: `results/figures/gradphi_draft.pdf`)", ""]
    med = {}
    for recipe in ("mixup", "nomix"):
        a = np.array(by[recipe])
        med[recipe] = np.median(a)
        e_first = np.median(per_epoch[recipe][min(per_epoch[recipe])])
        e_last = np.median(per_epoch[recipe][max(per_epoch[recipe])])
        top_layers = sorted(per_layer[recipe],
                            key=lambda li: -np.median(per_layer[recipe][li]))[:3]
        L.append(f"- {recipe}: median ||dL/dphi|| = {np.median(a):.3e} "
                 f"(p10 {np.percentile(a, 10):.3e}, "
                 f"p90 {np.percentile(a, 90):.3e}); per-epoch median moves "
                 f"{e_first:.3e} (epoch {min(per_epoch[recipe])}) -> "
                 f"{e_last:.3e} (epoch {max(per_epoch[recipe])}); largest "
                 f"median layers: {top_layers}.")
    L += ["",
          f"Magnitude ratio nomix/mixup (medians): "
          f"{med['nomix'] / med['mixup']:.2f}.",
          ""]
    return L


def sec_gates():
    agree = list(csv.DictReader(open("results/tables/gate_agreement.csv",
                                     newline="")))
    stds = list(csv.DictReader(open("results/tables/gate_spatial_std.csv",
                                    newline="")))
    L = ["## 8. Gate-map repeat agreement (all six ViT-S SAGA sets; "
         "figure: `results/figures/gate_agreement_draft.pdf`)", "",
         "| pair | group | Spearman pooled | layer mean | layer min-max |",
         "|---|---|---|---|---|"]
    for r in agree:
        L.append(f"| {r['pair']} | {r['group']} | {r['spearman_pooled']} "
                 f"| {r['spearman_layer_mean']} "
                 f"| {r['spearman_layer_min']}..{r['spearman_layer_max']} |")
    groups = defaultdict(list)
    for r in agree:
        groups[r["group"]].append(float(r["spearman_pooled"]))
    L.append("")
    for g, vals in groups.items():
        L.append(f"- {g}: pooled Spearman {min(vals):.3f}..{max(vals):.3f} "
                 f"(mean {np.mean(vals):.3f}, {len(vals)} pairs).")
    by_set = defaultdict(list)
    for r in stds:
        by_set[r["set"]].append(float(r["spatial_std"]))
    L += ["",
          "Within-layer spatial std of sigmoid(phi) (mean over layers; the "
          "'did it learn spatial structure' scalar):",
          ""]
    for s, vals in by_set.items():
        L.append(f"- {s}: mean {np.mean(vals):.4f}, max layer "
                 f"{max(vals):.4f} (final layer ~0: phi stays at init "
                 f"there in every run).")
    L += ["",
          "High agreement across independent seeds means the repeats learn "
          "the SAME spatial map; the numbers above report it per group "
          "(within-mixup, within-nomix, cross-recipe) without further "
          "interpretation.",
          ""]
    return L


def sec_open_items():
    return [
        "## 9. Open items",
        "",
        "1. Optional ViT-B true-nomix pair (baseline+saga, ~2.5 job-days) — "
        "recommended, awaiting the human's yes.",
        "2. Registers has NO clean-protocol (seeded) runs — it appears only "
        "as legacy repeats; a rerun pair per cell is a decision for the "
        "human.",
        "3. n=2 cells (true-nomix; ViT-B/mixup) carry SEs flagged "
        "unreliable; an extra seed pair would firm them up.",
        "4. PROJECT.md full rewrite queued for the milestone (erratum stub "
        "in place).",
        "",
    ]


def main():
    parser = argparse.ArgumentParser(description="Generate e2r_first_look.md")
    parser.add_argument("--out", default="results/notes/e2r_first_look.md")
    args = parser.parse_args()

    rows = load_pooled()
    L = sec_header()
    L += sec_vitb_resolution()
    L += sec_consistency()
    L += sec_pooled(rows)
    L += sec_significance(rows)
    L += sec_vitb_sink(rows)
    L += sec_trainloss(rows)
    L += sec_gradphi()
    L += sec_gates()
    L += sec_open_items()

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L), encoding="utf-8", newline="\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
