#!/usr/bin/env python3
"""
analysis/build_teaser_note.py
=============================
TASK-11 C3 — generate `results/notes/teaser.md` from the committed artifacts.

    python analysis/build_teaser_note.py

Reads ONLY:
    results/tables/T_localization.csv      (analysis/build_localization_tables.py)
    results/figures_data/F1_localization.csv
    results/figures_data/F1_teaser.npz     (its `index`)

Every number in the note is read from those files. Nothing is typed by hand —
the same rule TASK-02B/06B/07/08's note generators follow, and the reason
TASK-07 caught a hand-typed "1.79x" that should have been 1.71x.

The note states, in this order: which 3 images the figure shows and why, which
model panels are missing or pending, the localization table with its nulls,
the honest reading of those numbers (including where they do NOT support the
framing this task was written around), and the failure cases — kept for the
appendix, never discarded.
"""

import argparse
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from saga.run_registry import git_sha                     # noqa: E402
from tools.dense_runtime import atomic_write_text         # noqa: E402

MISSING = "MISSING"
HEADLINE = ("boxes20", "inbox_mass")


def choose_images(index, n=3):
    """The figure's 3 rows: the first curated image of each criterion, in
    sorted-criterion order. Deterministic, and pinned against
    plotting/plot_F1.py's own default by a test."""
    seen, out = set(), []
    for im in index["images"]:
        if im["criterion"] not in seen:
            seen.add(im["criterion"])
            out.append(im)
    return out[:n]


def load_table(path):
    with open(path, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def num(s):
    return None if s in (MISSING, "", None) else float(s)


def fmt(s, nd=4):
    v = num(s)
    return MISSING if v is None else f"{v:.{nd}f}"


def per_image(loc_csv):
    d = defaultdict(dict)
    with open(loc_csv, encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            d[(r["run_id"], r["group"], r["metric"])][r["image_id"]] = \
                float(r["value"])
    return d


def table_block(rows, arch):
    """Markdown table for one architecture."""
    out = ["| group | metric | model | n | mean | std | null | Δ vs baseline "
           "| Δ SE | 2×SE |",
           "|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        if r["arch"] != arch:
            continue
        d = num(r["delta_vs_baseline_mean"])
        dcell = MISSING if d is None else f"{d:+.4f}"
        sig = r["delta_significant_2xSE"]
        sig = "—" if sig == MISSING else ("**YES**" if sig == "YES" else "no")
        out.append(
            f"| {r['group']} | `{r['metric']}` | {r['variant']} | {r['n']} "
            f"| {fmt(r['mean'])} | {fmt(r['std'])} | {fmt(r['null_mean'])} "
            f"| {dcell} | {fmt(r['delta_se'])} | {sig} |")
    return "\n".join(out)


def significant(rows, arch, variant, group, metric):
    for r in rows:
        if (r["arch"], r["variant"], r["group"], r["metric"]) == \
                (arch, variant, group, metric):
            return r
    return None


def main():
    p = argparse.ArgumentParser(description="Generate results/notes/teaser.md")
    p.add_argument("--table", default="results/tables/T_localization.csv")
    p.add_argument("--localization",
                   default="results/figures_data/F1_localization.csv")
    p.add_argument("--archive", default="results/figures_data/F1_teaser.npz")
    p.add_argument("--figure", default="results/figures/F1_teaser_draft.pdf")
    p.add_argument("--out", default="results/notes/teaser.md")
    args = p.parse_args()

    rows = load_table(args.table)
    vals = per_image(args.localization)
    with np.load(args.archive, allow_pickle=False) as z:
        index = json.loads(str(z["index"]))
        grid = index["grid"]
        ring_cells = int(z["ring1_mask"].sum())

    chosen = choose_images(index)
    archs = sorted({r["arch"] for r in rows})
    by_run = index.get("provenance", {})
    variants_present = {p.get("variant") for p in by_run.values()}

    L = []
    A = L.append
    A("# Figure 1 (teaser) — what it shows and what the numbers say")
    A("")
    A("Generated by `analysis/build_teaser_note.py`. Every number below is read "
      "from `results/tables/T_localization.csv`, "
      "`results/figures_data/F1_localization.csv` and the `index` of "
      "`results/figures_data/F1_teaser.npz`. None is typed by hand.")
    A("")
    A(f"Figure: `{args.figure}` · grid {grid}×{grid} · ring-1 mask = "
      f"{ring_cells} of {grid * grid} patches.")
    A("")

    # ── 1. the three displayed images ───────────────────────────────────────
    A("## 1. The three images the figure shows")
    A("")
    A("One per stated criterion, taken in sorted-criterion order — the first "
      "curated image of each. The criteria are **class-level priors** "
      "(`criterion_basis` below), not per-image verification: the probe-set "
      "builder picks a synset pool per criterion and samples from it, so an "
      "individual image may not be a perfect example of its label.")
    A("")
    A("| # | criterion | basis | synset | image |")
    A("|---|---|---|---|---|")
    for i, im in enumerate(chosen, 1):
        A(f"| {i} | {im['criterion']} | {im.get('criterion_basis', MISSING)} "
          f"| `{im['synset']}` | `{im['image_id'].split('/')[-1]}` |")
    A("")
    A("**These three panels are illustrations, not evidence.** Every number in "
      "the figure's captions and in §3 below is a mean over the POPULATION "
      "(`random200`, n=200; `boxes20`, n=20), never over the displayed images.")
    A("")

    # ── 2. missing / pending panels ─────────────────────────────────────────
    A("## 2. Missing and pending panels")
    A("")
    absent = index.get("absent", [])
    if "ttr" not in variants_present:
        A("- **TTR — PENDING.** No test-time-registers model was dumped, so "
          "that column renders as an explicit dotted `pending` panel. TASK 10 "
          "has since produced TTR run directories; wiring its builder into "
          "`tools/dump_attention.py --model-builder` and re-running the dump "
          "for that row alone would fill the column.")
    for arch in archs:
        have = {r["variant"] for r in rows if r["arch"] == arch}
        for v in ("registers", "saga", "baseline"):
            if v not in have:
                A(f"- **{arch} / {v} — ABSENT.** No such run exists; the cell "
                  f"is reported absent, never zero and never pooled across "
                  f"architectures.")
    for a in absent:
        A(f"- `{a}` — recorded in the archive's `absent` list; the figure's "
          f"bottom strip uses the **baseline** sink map, which is present.")
    A("")

    # ── 3. the table ────────────────────────────────────────────────────────
    A("## 3. Localization over the population")
    A("")
    A("Deltas are **paired by image** against the SAME architecture's "
      "baseline; SE = sd/√n_pairs; `2×SE` flags |Δ| > 2·SE. `null` is the "
      "uniform-attention reference for that metric — `box_area_frac` for "
      "`inbox_mass`, the ring's area fraction for `ring1_mass` — without "
      "which neither number means anything (TASK-07 established that these "
      "statistics can invert sign once their null is accounted for).")
    for arch in archs:
        A("")
        A(f"### {arch}")
        A("")
        A(table_block(rows, arch))
    A("")

    # ── 4. the honest reading ───────────────────────────────────────────────
    A("## 4. What these numbers say")
    A("")
    A("**The spread is over IMAGES, not over seeds.** Each cell here is a "
      "single training run, so `2×SE` answers *\"does this model attend "
      "differently on these images?\"* — NOT *\"would another training seed "
      "reproduce this?\"* No claim of seed-stability is made or supported by "
      "this table. (TASK-06B/08 deltas, which do carry seed replication, are "
      "a different and stronger kind of number.)")
    A("")

    lines = []
    for arch in archs:
        for variant in ("saga", "registers"):
            r = significant(rows, arch, variant, *HEADLINE)
            if r is None:
                continue
            d, base = num(r["delta_vs_baseline_mean"]), num(r["null_mean"])
            mean = num(r["mean"])
            rel = ("above" if mean is not None and base is not None
                   and mean > base else "at or below")
            lines.append(
                f"- **{arch} / {variant}**: in-box mass {mean:.4f} vs a "
                f"uniform-attention null of {base:.4f} — {rel} the null; "
                f"Δ vs baseline {d:+.4f} "
                f"({'significant' if r['delta_significant_2xSE'] == 'YES' else 'not significant'} "
                f"at 2×SE).")
    L.extend(lines)
    A("")

    sig_rows = [r for r in rows if r["delta_significant_2xSE"] == "YES"]
    if sig_rows:
        A("Significant deltas at 2×SE, all of them:")
        A("")
        for r in sorted(sig_rows, key=lambda r: (r["arch"], r["variant"],
                                                 r["group"], r["metric"])):
            A(f"- `{r['arch']}` / {r['variant']} / `{r['metric']}` "
              f"({r['group']}): {float(r['delta_vs_baseline_mean']):+.4f} "
              f"± {fmt(r['delta_se'])} — {r['delta_direction']}")
    else:
        A("No delta in this table reaches 2×SE.")
    A("")

    sig_by_variant = defaultdict(list)
    for r in sig_rows:
        sig_by_variant[r["variant"]].append(r)
    if sig_by_variant.get("registers") and len(
            sig_by_variant["registers"]) >= len(sig_by_variant.get("saga", [])):
        A("> **This does not support the framing TASK 11 was written around.** "
          "The task assumed the teaser would show SAGA's gate suppressing the "
          "sink address. On this probe set the model that measurably "
          "localizes is **registers**, not SAGA: it carries "
          f"{len(sig_by_variant['registers'])} of the "
          f"{len(sig_rows)} significant deltas, including the in-box mass and "
          "the pointing game, while SAGA's only significant effect is a small "
          "reduction in ring-1 mass. The figure and this note report that as "
          "it stands; the framing is the human's call, not something to be "
          "resolved by choosing different panels.")
        A("")

    # ── 5. caveats ──────────────────────────────────────────────────────────
    A("## 5. Caveats that bound every number above")
    A("")
    reg_runs = [rid for rid, p in by_run.items()
                if p.get("variant") == "registers"]
    if reg_runs:
        A(f"1. **The registers run is not seed-matched to the others.** "
          f"`{reg_runs[0]}` is a LEGACY e2-era checkpoint (manifest seed "
          f"`rlast`, no seed control), while the baseline and SAGA runs are "
          f"the clean seeded e2r reruns. Per the recipe erratum it belongs to "
          f"the same (vit_small, mixup) cell, so the comparison is legitimate "
          f"— but it is a different training era, not a paired seed.")
    nullrow = next((r for r in rows if r["metric"] == "box_area_frac"), None)
    if nullrow:
        A(f"2. **`inbox_mass` has little headroom.** The GT boxes cover "
          f"{float(nullrow['mean']):.1%} of the cropped frame on average "
          f"(std {float(nullrow['std']):.4f}), so uniform attention already "
          f"scores {float(nullrow['mean']):.4f}. A model has to beat that to "
          f"mean anything, and `boxes20` is only n={nullrow['n']}.")
    A("3. **Probe-set scale.** `random200` is 200 images (one per class over "
      "200 seeded classes); `boxes20` is 20 COCO-val images. Both are frozen "
      "forever, so these numbers are reproducible, but they are a probe, not "
      "a benchmark.")
    A("4. **Attention is not attribution.** CLS→patch attention in the last "
      "block is one readout of where a model looks; it is not a saliency "
      "method and carries none of their guarantees.")
    A("")

    # ── 6. failure cases, kept ──────────────────────────────────────────────
    A("## 6. Failure cases (for the appendix — listed, not discarded)")
    A("")
    area = vals.get((list(by_run)[0], "boxes20", "box_area_frac"), {})
    worse, missed = defaultdict(list), []
    for rid in sorted(by_run):
        ib = vals.get((rid, "boxes20", "inbox_mass"), {})
        for img, v in sorted(ib.items()):
            if img in area and v < area[img]:
                worse[rid].append(img)
    hits = {rid: vals.get((rid, "boxes20", "pointing_hit"), {})
            for rid in sorted(by_run)}
    all_imgs = sorted(area)
    for img in all_imgs:
        if all(h.get(img, 0.0) == 0.0 for h in hits.values()):
            missed.append(img)

    A(f"**Attention below the uniform null** (`inbox_mass` < `box_area_frac`, "
      f"i.e. the model attends INSIDE the boxes less than chance would), of "
      f"{len(all_imgs)} boxes20 images:")
    A("")
    for rid in sorted(worse):
        A(f"- `{rid}`: {len(worse[rid])}/{len(all_imgs)} images — "
          + (", ".join(f"`{i}`" for i in worse[rid][:6])
             + (" …" if len(worse[rid]) > 6 else "") if worse[rid] else "none"))
    A("")
    A(f"**Pointing game missed by EVERY model** ({len(missed)} of "
      f"{len(all_imgs)} images) — these are the cases the teaser must not be "
      f"read as solving:")
    A("")
    for img in missed:
        A(f"- `{img}`")
    A("")
    A("The other nine curated images not shown in the figure are kept in the "
      "frozen probe set and in `F1_teaser.npz`, so any of them can be "
      "substituted into the figure without re-running inference:")
    A("")
    shown = {im["image_id"] for im in chosen}
    for im in index["images"]:
        if im["image_id"] not in shown:
            A(f"- `{im['image_id'].split('/')[-1]}` ({im['criterion']})")
    A("")

    A("---")
    A("")
    A(f"Provenance: git `{git_sha()[:12]}`; dumps from "
      + ", ".join(f"`{rid}` ({p.get('variant')}, ckpt "
                  f"`{str(p.get('ckpt_sha256'))[:12]}`)"
                  for rid, p in sorted(by_run.items())) + ".")

    atomic_write_text("\n".join(L) + "\n", Path(args.out))
    print(f"wrote {args.out} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
