#!/usr/bin/env python3
"""
analysis/build_ablation_note.py
===============================
TASK-12 Phase C.4: results/notes/ablation.md, GENERATED.

Every number in the note is read from results/tables/T2_ablation.csv,
T2_ablation_address.csv and results/tables/e2_pooled.csv. Nothing is typed
in, and a test re-renders the note from the committed tables and requires it
byte-identical, so no value in it can drift from its source.

    python analysis/build_ablation_note.py \
        [--table results/tables/T2_ablation.csv] \
        [--address results/tables/T2_ablation_address.csv] \
        [--pooled results/tables/e2_pooled.csv] \
        [--out results/notes/ablation.md]

The note answers TASK-12's four questions. Where the canonical fp32 / canon-
tau evidence is not yet derived it says PENDING and names the job that
produces it; it does NOT quietly answer from the trainer's bf16 log values
instead. Those appear once, fenced, labelled not citable, because the
project has already been burned by a log value being quoted as a result
(TASK-06B: a +0.52 log value against +0.456 fp32).
"""

import argparse
import csv
from datetime import date
from pathlib import Path

MISSING = "MISSING"


def num(v):
    """float, or None when the cell is MISSING/empty."""
    if v in (None, "", MISSING):
        return None
    try:
        return float(v)
    except ValueError:
        return None


def f(v, nd=3, signed=False):
    x = num(v)
    if x is None:
        return MISSING
    return f"{x:+.{nd}f}" if signed else f"{x:.{nd}f}"


def load(path):
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def pooled_reference(rows):
    """The 300-epoch ViT-S/mixup SAGA-vs-baseline paired delta this cell's
    arm E is compared against, read from e2_pooled.csv."""
    out = {}
    for r in rows:
        if r.get("arch") != "vit_small" or r.get("recipe_actual") != "mixup":
            continue
        if r.get("variant") == "saga" and r.get("kind") == "paired_delta_mean":
            out["delta_mean"] = num(r["top1_last"])
            out["n"] = r["n"]
            out["sink_canon"] = num(r["sink_fixed_canon"])
            out["oversmooth"] = num(r["oversmooth_pairwise"])
        if r.get("variant") == "saga" and r.get("kind") == "paired_delta_se":
            out["delta_se"] = num(r["top1_last"])
        if r.get("variant") == "saga" and r.get("kind") == "paired_delta":
            out.setdefault("repeats", []).append(
                (r.get("provenance", "?"), num(r["top1_last"])))
        for v in ("baseline", "saga"):
            if r.get("variant") == v and r.get("kind") == "mean":
                out[f"{v}_top1"] = num(r["top1_last"])
                out[f"{v}_oversmooth"] = num(r["oversmooth_pairwise"])
                out[f"{v}_eff_rank"] = num(r["eff_rank"])
    return out


def q_block(rows, col, delta_col, label, unit=""):
    """A comparison table over the arms for one metric column."""
    lines = [f"| arm | gate_mode | trainable gate params | {label} "
             f"| Δ vs A |", "|---|---|---|---|---|"]
    for r in rows:
        lines.append(
            f"| {r['arm']} | `{r['gate_mode']}` | {r['gate_params_trainable']}"
            f" | {f(r[col])}{unit} | {f(r[delta_col], signed=True)} |")
    return lines


def build(table, address, pooled, today):
    by_arm = {r["arm"]: r for r in table}
    ref = pooled_reference(pooled)
    L = []

    def w(s=""):
        L.append(s)

    derived = all(num(r["top1_last"]) is not None for r in table)
    canon_present = all(num(r["sink_fixed_canon"]) is not None
                        for r in table)
    saturated = [r for r in table
                 if str(r.get("sink_canon_saturated", "")).lower() == "true"]
    # a saturated threshold has been MEASURED but orders nothing, which is
    # not the same state as "not yet derived" and must not be reported as it
    canon = canon_present and not saturated
    has_addr = any(num(r["rho"]) is not None for r in address)

    w("# TASK-12 — matched-init ablation: is the spatial structure the "
      "active ingredient?")
    w()
    w(f"Generated by `analysis/build_ablation_note.py` on {today}. Every "
      f"number is read from")
    w("`results/tables/T2_ablation.csv`, `results/tables/"
      "T2_ablation_address.csv` and")
    w("`results/tables/e2_pooled.csv`; none is typed into this file.")
    w()
    w("## 0. Status of the evidence")
    w()
    w(f"- exact fp32 full-50k top-1 for every arm: "
      f"**{'derived' if derived else 'PENDING'}**")
    w(f"- primary-metric sink counts (the cell's canon tau): "
      + ("**derived**" if canon else
         ("**DERIVED BUT SATURATED — see §5, they order nothing**"
          if saturated else "**PENDING**")))
    w(f"- gate-vs-address correlations: "
      f"**{'derived' if has_addr else 'PENDING'}**")
    # only for what is genuinely NOT YET DERIVED. A saturated threshold has
    # been measured; re-running the job would not change it.
    if not (derived and canon_present and has_addr):
        w()
        w("What is PENDING above comes from one job — "
          "`sbatch scripts/jobs/abl_derive.sbatch` — which runs "
          "`tools/derive_runs.py --pattern 'abl_*'`, then "
          "`tools/apply_fixed_thr.py --version canon`, then "
          "`tools/sink_address.py`. Re-running this generator fills those "
          "sections in. **No question below is answered from a substitute "
          "number.**")
    w()
    w("## 1. The six arms, and the structural check that they are what they "
      "claim")
    w()
    w("All six are ViT-S/16 on the mixup recipe, seed 0, 100 epochs, and "
      "differ ONLY in")
    w("`gate_mode` (and `gate_init_logit` for arm F) — verified by diffing "
      "the six resolved")
    w("configs key by key, not asserted.")
    w()
    w("| arm | run | gate_mode | gate params (registered / trainable) | "
      "final gate mean | within-layer spatial std | expected |")
    w("|---|---|---|---|---|---|---|")
    for r in table:
        w(f"| {r['arm']} | `{r['run_id']}` | `{r['gate_mode']}` | "
          f"{r['gate_params_registered']} / {r['gate_params_trainable']} | "
          f"{f(r['gate_mean_final'], 4)} | "
          f"{f(r['gate_spatial_std_final'], 6)} | "
          f"{r['spatial_std_expected']} |")
    w()
    w("The spatial-std column is the point: it is **0 by construction** for "
      "the frozen arm and")
    w("for the head-scalar arm, and non-zero only where the gate can vary "
      "across positions.")
    w("Arm B registers a full-size gate and trains none of it.")
    w()

    # ── Q1 ───────────────────────────────────────────────────────────────
    w("## 2. Q1 — does the spatial arm beat the non-spatial controls and the "
      "frozen floor?")
    w()
    if derived:
        L.extend(q_block(table, "top1_last", "delta_top1_vs_A",
                         "top-1 (fp32, full 50k, last)"))
        w()
        e = num(by_arm["E"]["top1_last"])
        pairs = [(k, num(by_arm[k]["top1_last"])) for k in ("B", "C", "D")]
        for k, v in pairs:
            w(f"- E − {k} = **{e - v:+.3f}**")
        # TASK-12's Phase-D trigger names {C, D} specifically — B is the
        # floor, not a control — so the margin is computed over those two
        best_ctrl_arm, best_ctrl = max(
            ((k, v) for k, v in pairs if k in ("C", "D")),
            key=lambda t: t[1])
        margin = e - best_ctrl
        spread = (max(num(r["top1_last"]) for r in table)
                  - min(num(r["top1_last"]) for r in table))
        w()
        w(f"E's margin over the better of {{C, D}} (arm {best_ctrl_arm}) is "
          f"**{margin:+.3f}**, against an arm-to-arm")
        w(f"spread of **{spread:.3f}**. "
          + ("Because that margin is SMALLER than the spread, TASK-12's "
             "Phase-D condition is met: the comparison needs seeds 1-2 "
             "before it can carry a standard error."
             if margin < spread else
             "That margin exceeds the spread."))
    else:
        w("**PENDING** — needs the fp32 evaluation (see §0).")
    w()

    # ── Q2 ───────────────────────────────────────────────────────────────
    w("## 3. Q2 — does the init matter (E vs F)?")
    w()
    if derived:
        e, fv = num(by_arm["E"]["top1_last"]), num(by_arm["F"]["top1_last"])
        w(f"F − E = **{fv - e:+.3f}** top-1.")
    else:
        w("**PENDING** — needs the fp32 evaluation (see §0).")
    w()
    gm_e = num(by_arm["E"]["gate_mean_final"])
    gm_f = num(by_arm["F"]["gate_mean_final"])
    if gm_e is not None and gm_f is not None:
        w("But the arms' own gate dumps say the question is not clean. Arm F "
          "starts at")
        w(f"sigmoid(+4) = 0.982 and ends at a mean gate of **{gm_f:.4f}**, "
          f"against arm E's **{gm_e:.4f}**.")
        w("phi = 0 is a fixed point of decoupled weight decay while phi = +4 "
          "is not, so arm F is")
        w("pulled toward arm E's regime throughout training by the weight "
          "decay both arms share")
        w("(`wd_phi_zero: false`, the shipped e2r treatment of phi). The "
          "arms may differ only in")
        w("`gate_mode` and `gate_init_logit`, so this was left matched "
          "deliberately — but it means")
        w("**F is not a clean test of initialisation**; it is a test of "
          "initialisation under a decay")
        w("that erases it. Reading F as an init preference would overstate "
          "what was measured.")
    w()

    # ── Q3 ───────────────────────────────────────────────────────────────
    w("## 4. Q3 — is the 100-epoch ranking consistent with the 300-epoch "
      "headline?")
    w()
    dm, se, n = ref.get("delta_mean"), ref.get("delta_se"), ref.get("n")
    if dm is not None:
        reps = ", ".join(f"{v:+.3f}" for _, v in sorted(
            ref.get("repeats", []), key=lambda t: t[0]))
        w(f"The headline cell (`results/tables/e2_pooled.csv`, ViT-S/mixup, "
          f"300 epochs, n={n}):")
        w(f"SAGA − baseline = **{dm:+.3f}** top-1, SE {se:.3f}, from the "
          f"per-repeat deltas {reps}.")
        w()
    if derived:
        d = num(by_arm["E"]["delta_top1_vs_A"])
        w(f"Here, at 100 epochs and a single seed: E − A = **{d:+.3f}**.")
        w()
        if dm is not None and (d < 0) != (dm < 0):
            w("### ⚠ SIGN INVERSION AGAINST THE HEADLINE")
            w()
            w(f"The headline delta is {dm:+.3f} and this one is {d:+.3f}. "
              f"That is flagged here as loudly")
            w("as TASK-12 requires, and it is also calibrated rather than "
              "left to alarm:")
            neg = [f"{v:+.3f}" for _, v in ref.get("repeats", [])
                   if v is not None and v < 0]
            if neg:
                w(f"**{len(neg)} of the {n} 300-epoch repeats was itself "
                  f"negative ({', '.join(neg)})**, so a single")
                w("100-epoch draw of this size sits inside the spread the "
                  "headline cell already shows.")
                w("It is not evidence of an inversion and it is not evidence "
                  "of replication. It is one seed,")
                w("on a shorter schedule, and the honest reading is that "
                  "this cell cannot settle E vs A.")
        elif dm is not None:
            w("The sign agrees with the headline; the magnitudes are not "
              "comparable across schedules.")
    else:
        w("**PENDING** — needs the fp32 evaluation (see §0).")
    w()

    # ── diagnostics ──────────────────────────────────────────────────────
    w("## 5. Diagnostics")
    w()
    if canon:
        L.extend(q_block(table, "sink_fixed_canon", "delta_sink_canon_vs_A",
                         "sinks (canon tau, PRIMARY)"))
        w()
        b = num(by_arm["B"]["sink_fixed_canon"])
        e = num(by_arm["E"]["sink_fixed_canon"])
        w(f"**The comparison that bears on the mechanism claim: arm B "
          f"({b:.4f}) against arm E ({e:.4f}).**")
        w("Arm B trains zero gate parameters. Whatever sink reduction it "
          "achieves is the effect of")
        w("the 0.5 scaling alone, with no learning and no spatial structure "
          "of any kind.")
    elif saturated:
        tau = f(table[0]["canon_thr_value"], 4)
        counts = ", ".join(f"{r['arm']} {f(r['sink_fixed_canon'], 4)}"
                           for r in table)
        w("### The primary sink metric SATURATES in this cell and orders "
          "nothing")
        w()
        w(f"Under the committed ViT-S/mixup canon tau ({tau}) every arm "
          f"counts essentially all 196")
        w(f"patch tokens as sinks: {counts}. That is above TASK-02B's own "
          f"saturation flag (>= 95% of")
        w("the patch tokens), and a threshold that every token clears cannot "
          "rank anything. The")
        w("differences between those numbers are the last decimal of a "
          "saturated count and are not")
        w("evidence about any arm.")
        w()
        w("**The cause is a schedule mismatch, not a fault in the runs.** "
          "The canon tau was")
        w("calibrated on the 300-epoch `e2r_vits_mixup_baseline_s1`, and "
          "these models are 100-epoch")
        w("models with a different norm scale: arm A's own last-block patch "
          "norms have a median of")
        w("37.28 against that tau of 20.85, and its own per-image MAD "
          "threshold (the quantity the")
        w("canon definition is built from) is 52.95 — read from "
          "`diag_final_last_normstats.json`,")
        w("fields `p50` and `mean_threshold_mad_k5`. A tau calibrated on "
          "this cell would sit near")
        w("the latter, i.e. roughly 2.5x the one applied here.")
        w()
        w("**Nothing was recalibrated.** TASK-12's acceptance list requires "
          "the canon tau be taken")
        w("from the ViT-S/mixup cell and never recalibrated, so it was not, "
          "and the saturation is")
        w("reported instead of worked around. The consequence has to be "
          "stated plainly: **this")
        w("ablation cannot answer the sink question on its primary metric.** "
          "Answering it would need")
        w("a threshold calibrated on THIS cell's own arm-A baseline, "
          "declared under its own key")
        w("with its own provenance — a decision for the human, not a "
          "substitution to be made here.")
        w()
        w("What remains is the secondary MAD metric, and it is confounded "
          "against precisely the")
        w("comparison at issue: PROJECT.md §3.2 records that per-image "
          "median+5·MAD falls with the")
        w("norm bulk, and a uniform 0.5 gate compresses exactly that bulk. "
          "So arm B scoring well on")
        w("MAD is the predicted behaviour of the metric, not evidence about "
          "the mechanism. Both")
        w("numbers are below; neither settles anything.")
        w()
    else:
        w("Primary-metric (canon tau) sink counts are **PENDING** (see §0), "
          "and they are what")
        w("decides the mechanism question, so nothing is claimed here yet. "
          "The secondary MAD")
        w("metric is in the table; `results/notes/gate1_addendum.md` and "
          "PROJECT.md §3.2 record")
        w("why it is secondary — per-image median+5·MAD falls with the norm "
          "bulk, which a uniform")
        w("0.5 scaling compresses by construction, so on that metric a "
          "frozen gate can look like a")
        w("learned one for a reason that has nothing to do with the address.")
    w()
    canonical_diag = any(num(r["oversmooth_pairwise"]) is not None
                         for r in table)
    suffix = "" if canonical_diag else "_intrain"
    if not canonical_diag:
        ep = table[0]["intrain_diag_epoch"]
        w(f"The table below is therefore the trainer's OWN periodic "
          f"diagnostics at epoch {ep} —")
        w("same metric code and same frozen 10k split as the canonical pass, "
          "but a different file")
        w("and a norms-only pass (no attention capture). It is here so the "
          "section is not empty,")
        w("it is labelled in `T2_ablation.csv` by the `_intrain` suffix, and "
          "the canonical columns")
        w("stay MISSING until the derivation runs.")
        w()
    w("| arm | oversmoothing (pairwise) | oversmoothing (no-sink) | "
      "eff. rank | sinks (MAD, secondary) |")
    w("|---|---|---|---|---|")
    for r in table:
        w(f"| {r['arm']} | {f(r['oversmooth_pairwise' + suffix], 4)} | "
          f"{f(r['oversmooth_pairwise_nosink' + suffix], 4)} | "
          f"{f(r['eff_rank' + suffix], 2)} | "
          f"{f(r['sink_mad_k5' + suffix], 4)} |")
    w()
    if canonical_diag and saturated:
        b = num(by_arm["B"]["sink_mad_k5"])
        e = num(by_arm["E"]["sink_mad_k5"])
        a = num(by_arm["A"]["sink_mad_k5"])
        if None not in (a, b, e):
            w(f"On MAD, the frozen arm B ({b:.4f}) and the learned spatial "
              f"arm E ({e:.4f}) both sit far")
            w(f"below the baseline ({a:.4f}). As above, that is what this "
              f"metric does when the norm")
            w("bulk is compressed, so it is not evidence that the two "
              "interventions are equivalent —")
            w("and it is not evidence that they differ either. The question "
              "is open and this cell,")
            w("as calibrated, cannot close it.")
            w()
    if not canonical_diag:
        b = num(by_arm["B"]["sink_mad_k5_intrain"])
        e = num(by_arm["E"]["sink_mad_k5_intrain"])
        a = num(by_arm["A"]["sink_mad_k5_intrain"])
        if None not in (a, b, e):
            w(f"Read on the SECONDARY metric only, and therefore not a "
              f"conclusion: the frozen arm B")
            w(f"({b:.4f}) and the learned spatial arm E ({e:.4f}) both sit "
              f"far below the baseline ({a:.4f}).")
            w("If that survives the canon tau, the sink reduction is an "
              "init-scale effect rather than")
            w("a learned-structure one, and the mechanism claim needs "
              "rewriting. If it does not, the")
            w("MAD metric behaved exactly as PROJECT.md §3.2 says it does. "
              "The derivation decides it;")
            w("nothing is concluded here.")
            w()
    if ref.get("baseline_oversmooth") is not None:
        w(f"Context for reading these: the 300-epoch baseline of this cell "
          f"sits at oversmoothing")
        w(f"{ref['baseline_oversmooth']:.4f} and effective rank "
          f"{ref['baseline_eff_rank']:.2f} (same file, n={n}). A 100-epoch "
          f"model of the")
        w("same architecture is a less pathological object than a 300-epoch "
          "one, so there is less")
        w("for any gate to recover here. That is a property of the cell, not "
          "a defence of an arm.")
    w()

    # ── address ──────────────────────────────────────────────────────────
    w("## 6. Does the learned gate track this cell's sink address?")
    w()
    w("Correlations use TASK-07's EXACT permutation null (8 dihedral × 196 "
      "torus rolls),")
    w("imported from `analysis/address_analysis.py`, never the iid Spearman "
      "reference — for maps")
    w("this smooth the iid null is far too generous. The extremal layer is "
      "an argmax over 12,")
    w("so its p is Bonferroni-corrected.")
    w()
    degenerate_bases = sorted({r["map_basis"] for r in address
                               if "ADDRESS MAP is constant" in r["note"]})
    if degenerate_bases:
        w(f"**The `{'`, `'.join(degenerate_bases)}` basis carries no address "
          f"map in this cell.** The same")
        w("saturation as §5: every position is a sink in every image, so "
          "freq is exactly 1.0 at all")
        w("196 positions and the map has no spatial structure to correlate "
          "against. Those rows")
        w("carry no rho, deliberately. Only the MAD basis remains, so unlike "
          "TASK-07 — which")
        w("required a result to hold in BOTH bases — nothing here can be "
          "cross-checked between them.")
        w()
    if has_addr:
        w("| arm | basis | extremal layer | rho | p (exact) | p (Bonferroni) "
          "| null sd |")
        w("|---|---|---|---|---|---|---|")
        for r in address:
            if str(r["layer"]).startswith("layer_absmax"):
                w(f"| {r['arm']} | {r['map_basis']} | {r['layer']} | "
                  f"{f(r['rho'], 4)} | {f(r['p_spatial'], 5)} | "
                  f"{f(r['p_bonferroni'], 5)} | {f(r['null_sd'], 4)} |")
        w()
        sig = [r for r in address
               if str(r["layer"]).startswith("layer_absmax")
               and num(r["p_bonferroni"]) is not None
               and num(r["p_bonferroni"]) < 0.05]
        if sig:
            w("TASK-07 found this gate-vs-address relationship on the "
              "300-epoch ViT-S/mixup runs at")
            w("**layers 7-8, negative, rho −0.518…−0.594, Bonferroni-"
              "significant in 4/4 repeats**")
            w("(`results/notes/sink_address.md`). Here:")
            w()
            for r in sig:
                w(f"- arm {r['arm']} reaches rho **{f(r['rho'], 4)}** at "
                  f"{r['layer'].replace('layer_absmax=', 'layer ')}, "
                  f"Bonferroni p {f(r['p_bonferroni'], 4)} — same sign, same "
                  f"depth.")
            w()
            w("That is an independent replication of the mechanism finding "
              "on a different schedule,")
            w("and it is the strongest result in this ablation. Its limits "
              "are equally concrete: one")
            w("seed, one basis only (the canon map is degenerate here, so "
              "the two-basis agreement")
            w("TASK-07 required cannot be checked), and a correlation is an "
              "alignment — not a")
            w("demonstration that the alignment is what produces the "
              "accuracy.")
            w()
    else:
        w("**PENDING** — needs the address maps (see §0).")
        w()
    # Arms whose GATE cannot vary across positions, taken from gate_mode
    # rather than from note text. Two other things also produce a blank rho
    # and must not be confused with this one: a degenerate ADDRESS map
    # (covered just above), and a single layer of a spatial arm that happens
    # to be constant — the final layer usually is, since it stays at its
    # init. Calling those "arms with no structure" would be false.
    undefined = sorted({r["arm"] for r in address
                        if r["gate_mode"] in ("const", "headscalar")})
    flat_layers = sorted({(r["arm"], r["layer"]) for r in address
                          if r["gate_mode"] == "spatial"
                          and "layer is spatially constant" in r["note"]})
    if undefined:
        w(f"Arms {', '.join(undefined)} appear in the table with **no "
          f"correlation value, deliberately**: their")
        w("gate is constant across positions by construction, so a rank "
          "correlation against any")
        w("map is *undefined*, not zero. Printing 0.0 there would read as "
          "\"the non-spatial gate")
        w("ignores the address\", which would be a statement about "
          "arithmetic rather than about the")
        w("model.")
        if flat_layers:
            per_arm = {}
            for arm, layer in flat_layers:
                per_arm.setdefault(arm, []).append(str(layer))
            w()
            w("Individual layers of the SPATIAL arms are blank for the same "
              "reason and no other: "
              + "; ".join(f"arm {a} at layer(s) {', '.join(sorted(set(ls)))}"
                          for a, ls in sorted(per_arm.items()))
              + ". A layer that never moved from its init is spatially "
                "constant, so its rho is undefined too — that is one layer, "
                "not the arm.")
    else:
        w("(Arms B and C hold a gate that is constant across positions, so "
          "their correlation is")
        w("undefined rather than zero; the address table records that in "
          "words once it is built.)")
    w()

    # ── caveats ──────────────────────────────────────────────────────────
    w("## 7. Caveats — all of them apply to every number above")
    w()
    w(f"1. **One seed per arm.** No delta here carries a standard error, and "
      f"none of the project's")
    w("   significance machinery applies. The headline cell's own per-repeat "
      "deltas at 300 epochs")
    if dm is not None and ref.get("repeats"):
        rr = [v for _, v in ref["repeats"] if v is not None]
        w(f"   span {min(rr):+.3f} to {max(rr):+.3f} — wider than every "
          f"arm-to-arm difference measured here.")
    w("2. **100 epochs, not the headline's 300.** `warmup_epochs` stays at "
      "20, i.e. 20% of this")
    w("   schedule against 6.7% of the headline's; it was not retuned, "
      "because the arms had to")
    w("   stay identical to each other and to `e2r_vits_mixup_*` in "
      "everything but the gate.")
    w("   Cross-schedule comparisons of absolute top-1 are not meaningful.")
    w("3. **One cell.** ViT-S/16, mixup recipe. Nothing here speaks to "
      "ViT-B or to true-nomix.")
    w("4. **Arm D is standard LayerScale, which scales every token "
      "including CLS**, while the gate")
    w("   never touches CLS; and its gamma carries the same weight decay phi "
      "does. Both are")
    w("   deliberate (it is the control a reviewer means), both are "
      "deviations from the gate's")
    w("   treatment, and both are recorded in `configs/abl_matrix.yaml`.")
    w("5. **Arm F's initialisation does not survive its own schedule** "
      "(§3), so it under-tests the")
    w("   init question rather than answering it.")
    if saturated:
        w("6. **The primary sink metric saturates here** (§5), so the "
          "mechanism half of this")
        w("   ablation is unanswered rather than answered either way. The "
          "accuracy half (§2-4) and")
        w("   the gate-vs-address correlation (§6) are unaffected — they do "
          "not depend on that")
        w("   threshold.")
    w()
    w("## 8. Provenance")
    w()
    w("| arm | run_id | epochs | seed | checkpoint sha256 |")
    w("|---|---|---|---|---|")
    for r in table:
        sha = r["ckpt_sha256"]
        w(f"| {r['arm']} | `{r['run_id']}` | {r['n_epochs']} | {r['seed']} | "
          f"`{sha[:16] + '…' if sha != MISSING else MISSING}` |")
    w()
    notes = [(r["arm"], r["note"]) for r in table if r["note"]]
    if notes:
        w("Incomplete evidence, recorded rather than filled in:")
        w()
        for arm, note in notes:
            w(f"- **{arm}**: {note}")
        w()
    w("Not citable, and here only so the reader is not tempted to look for "
      "it elsewhere: the")
    w("trainer's own per-epoch full-val runs under **bf16** autocast, and "
      "those values are in")
    w("`T2_ablation.csv`'s `top1_last_bf16_log` column. They are a different "
      "quantity from the")
    w("fp32 evaluation above — TASK-06B measured a gap of the same order as "
      "the deltas in this")
    w("table (a +0.52 log value against +0.456 fp32) — and no conclusion in "
      "this note rests on")
    w("them.")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description="TASK-12 ablation note.")
    ap.add_argument("--table", default="results/tables/T2_ablation.csv")
    ap.add_argument("--address",
                    default="results/tables/T2_ablation_address.csv")
    ap.add_argument("--pooled", default="results/tables/e2_pooled.csv")
    ap.add_argument("--out", default="results/notes/ablation.md")
    ap.add_argument("--date", default=None,
                    help="override the generation date (tests pin it)")
    args = ap.parse_args()

    text = build(load(args.table), load(args.address), load(args.pooled),
                 args.date or date.today().isoformat())
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {out}  ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
