#!/usr/bin/env python3
"""
analysis/build_task11_handoff.py
================================
Generate `docs/TASK_11_HANDOFF.md` — the standalone handoff for whoever picks
TASK 11 up next (or writes the paper from it).

    python analysis/build_task11_handoff.py

Same contract as `analysis/build_task07_handoff.py`: every experimental number
is read from the committed artifacts, none is typed by hand, and re-running
the script after new results land updates the document in place.

Sources (and nothing else):
    results/probe/probe_set.json
    results/figures_data/F1_localization.csv  (+ _meta.json)
    results/figures_data/F1_teaser.npz        (its `index`)
    results/tables/T_localization.csv
"""

import argparse
import csv
import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from saga.run_registry import git_sha                     # noqa: E402
from tools.dense_runtime import atomic_write_text         # noqa: E402

MISSING = "MISSING"


def load_csv(p):
    with open(p, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def count_test_defs(path) -> int:
    """Test-function count, derived rather than typed. Not the same as
    pytest's collected count — a parametrized function is one def."""
    if not Path(path).exists():
        return 0
    return sum(1 for line in Path(path).read_text(encoding="utf-8").splitlines()
               if line.startswith("def test_"))


def failure_cases(per_image_rows):
    """(n_boxes, n_missed_by_every_model, {run_id: n_below_null}) — the
    appendix material, recomputed here from the per-image rows."""
    raw = defaultdict(dict)
    for r in per_image_rows:
        raw[(r["run_id"], r["group"], r["metric"])][r["image_id"]] = \
            float(r["value"])
    runs = sorted({k[0] for k in raw})
    if not runs:
        return 0, 0, {}
    area = raw[(runs[0], "boxes20", "box_area_frac")]
    missed = sum(1 for i in area
                 if all(raw[(r, "boxes20", "pointing_hit")].get(i, 0.0) == 0.0
                        for r in runs))
    below = {}
    for r in runs:
        ib = raw[(r, "boxes20", "inbox_mass")]
        below[r] = sum(1 for i in ib if i in area and ib[i] < area[i])
    return len(area), missed, below


def num(s):
    return None if s in (MISSING, "", None) else float(s)


def f4(s):
    v = num(s) if isinstance(s, str) else s
    return MISSING if v is None else f"{v:.4f}"


def main():
    p = argparse.ArgumentParser(description="Generate docs/TASK_11_HANDOFF.md")
    p.add_argument("--probe", default="results/probe/probe_set.json")
    p.add_argument("--localization",
                   default="results/figures_data/F1_localization.csv")
    p.add_argument("--meta",
                   default="results/figures_data/F1_localization_meta.json")
    p.add_argument("--archive", default="results/figures_data/F1_teaser.npz")
    p.add_argument("--table", default="results/tables/T_localization.csv")
    p.add_argument("--out", default="docs/TASK_11_HANDOFF.md")
    args = p.parse_args()

    probe = json.loads(Path(args.probe).read_text(encoding="utf-8"))
    loc_meta = json.loads(Path(args.meta).read_text(encoding="utf-8"))
    rows = load_csv(args.table)
    per_image = load_csv(args.localization)
    with np.load(args.archive, allow_pickle=False) as z:
        index = json.loads(str(z["index"]))
        grid = index["grid"]
        ring_cells = int(z["ring1_mask"].sum())
        archive_keys = list(z.files)

    runs = loc_meta["runs"]
    archs = sorted({r["arch"] for r in rows})
    sig = [r for r in rows if r["delta_significant_2xSE"] == "YES"]
    sig_by_variant = defaultdict(list)
    for r in sig:
        sig_by_variant[r["variant"]].append(r)

    L = []
    A = L.append

    A("# TASK 11 — probe set, attention dumps, localization, Figure 1: handoff")
    A("")
    A(f"GENERATED by `analysis/build_task11_handoff.py` at git "
      f"`{git_sha()[:7]}`. Every experimental number below is read from "
      f"`results/tables/T_localization.csv`, "
      f"`results/figures_data/F1_localization.csv` and the frozen probe set; "
      f"none is typed by hand. Re-run the script after new dumps land and "
      f"this document updates itself.")
    A("")

    # ── status ──────────────────────────────────────────────────────────────
    A("## Status")
    A("")
    A("| phase | what | state |")
    A("|---|---|---|")
    A("| A | probe-set builder, attention dumper, localization score, "
      "F1 collector + plotter, a40 job | **done** (`df2e515`, `a060c03`; "
      "merged `9887be7`) |")
    A("| B | HPC: freeze the probe set, dump 5 models, score, collect | "
      "**done** (`c5320d2`) |")
    A("| C | `T_localization.csv`, `teaser.md`, `F1_teaser_draft.pdf` | "
      "**done** (`78a3a0c`; merged `48c6e2b`) |")
    A("| — | TTR column of Figure 1 | **pending** — see *What was not done* |")
    A("")
    A("**Nothing is pending from the HPC.** TASK 11 is complete as specified.")
    A("")

    # ── the question ────────────────────────────────────────────────────────
    A("## The question this task had to settle")
    A("")
    A("Figure 1 is the paper's first impression and nothing existed to build "
      "it from. TASK 07 had established the mechanism quantitatively — the "
      "sink address is a ring one patch inside the border, seed-stable at "
      "rho ~= 0.91, and in every ViT-S/mixup SAGA repeat the layer-7/8 gate "
      "is significantly *anti*-correlated with it. The teaser therefore had "
      "to show that mechanism **and carry a number**, so it could not be "
      "dismissed as three cherry-picked attention maps.")
    A("")
    A("The number exists now. **It does not say what the task assumed it "
      "would.** See *Results*.")
    A("")

    # ── how to read ─────────────────────────────────────────────────────────
    A("## How to read these numbers (read this before quoting any)")
    A("")
    A("1. **The spread is over IMAGES, not over seeds.** Every cell is a "
      "single training run, so `2xSE` answers *\"does this model attend "
      "differently on these images?\"* — NOT *\"would another training seed "
      "reproduce this?\"* These are weaker than the TASK-06B/08 deltas, "
      "which do carry seed replication. Do not present them as equivalent.")
    A("2. **Every localization statistic needs its null.** `inbox_mass` is "
      "meaningless without `box_area_frac` (what uniform attention scores on "
      "the same boxes), and `ring1_mass` without the ring's area fraction. "
      "TASK 07 established that these statistics can invert sign once the "
      "null is accounted for. Both nulls are in the table as their own rows.")
    A("3. **Architectures are never pooled.** A ViT-S model is paired only "
      "against the ViT-S baseline. There is no ViT-B registers run.")
    A("4. **The three displayed images are illustrations, not evidence.** "
      "Every number is a population mean; no number in the figure or the "
      "note is computed from the shown images.")
    A("5. **Attention is not attribution.** CLS->patch attention in the last "
      "block is one readout of where a model looks. It is not a saliency "
      "method and carries none of their guarantees.")
    A("")

    # ── results ─────────────────────────────────────────────────────────────
    A("## Results")
    A("")
    A(f"Of the deltas in `T_localization.csv`, **{len(sig)} reach 2xSE**. "
      + (f"**{len(sig_by_variant.get('registers', []))} of them are "
         f"registers'; {len(sig_by_variant.get('saga', []))} "
         f"{'is' if len(sig_by_variant.get('saga', [])) == 1 else 'are'} "
         f"SAGA's.**" if sig else ""))
    A("")
    for r in sorted(sig, key=lambda r: (r["arch"], r["variant"], r["metric"])):
        A(f"- `{r['arch']}` / **{r['variant']}** / `{r['metric']}` "
          f"({r['group']}): {float(r['delta_vs_baseline_mean']):+.4f} "
          f"+/- {f4(r['delta_se'])} — {r['delta_direction']}")
    A("")

    A("### The full table")
    A("")
    for arch in archs:
        A(f"#### {arch}")
        A("")
        A("| group | metric | model | n | mean | std | null | Δ vs baseline "
          "| Δ SE | 2×SE |")
        A("|---|---|---|---|---|---|---|---|---|---|")
        for r in rows:
            if r["arch"] != arch:
                continue
            d = num(r["delta_vs_baseline_mean"])
            dc = MISSING if d is None else f"{d:+.4f}"
            s = r["delta_significant_2xSE"]
            s = "—" if s == MISSING else ("**YES**" if s == "YES" else "no")
            A(f"| {r['group']} | `{r['metric']}` | {r['variant']} | "
              f"{r['n']} | {f4(r['mean'])} | {f4(r['std'])} | "
              f"{f4(r['null_mean'])} | {dc} | {f4(r['delta_se'])} | {s} |")
        A("")

    # two readings that the nulls make visible, both computed
    A("### Two readings the nulls make visible")
    A("")

    def cell(arch, variant, group, metric, field="mean"):
        for r in rows:
            if (r["arch"], r["variant"], r["group"], r["metric"]) == \
                    (arch, variant, group, metric):
                return num(r[field])
        return None

    for arch in archs:
        base_r = cell(arch, "baseline", "random200", "ring1_mass")
        null_r = cell(arch, "baseline", "random200", "ring1_mass", "null_mean")
        parts = []
        for v in ("saga", "registers"):
            x = cell(arch, v, "random200", "ring1_mass")
            if x is not None:
                parts.append((v, x))
        if base_r is not None and null_r is not None and parts:
            txt = ", ".join(f"{v} {x:.4f}" for v, x in parts)
            A(f"- **{arch} ring-1 mass** vs a uniform null of {null_r:.4f}: "
              f"baseline {base_r:.4f}, {txt}."
              + (" Registers lands essentially AT the null — it has erased "
                 "the ring address, which is what the address result "
                 "predicts registers should do."
                 if any(v == "registers" and abs(x - null_r) < 0.02
                        for v, x in parts) else ""))
    for arch in archs:
        null_b = cell(arch, "baseline", "boxes20", "inbox_mass", "null_mean")
        base_b = cell(arch, "baseline", "boxes20", "inbox_mass")
        if null_b is None or base_b is None:
            continue
        below = [("baseline", base_b)]
        for v in ("saga", "registers"):
            x = cell(arch, v, "boxes20", "inbox_mass")
            if x is not None:
                below.append((v, x))
        under = [v for v, x in below if x < null_b]
        if under:
            A(f"- **{arch} in-box mass**: uniform attention already scores "
              f"{null_b:.4f} on these boxes. "
              + ", ".join(f"{v} {x:.4f}" for v, x in below)
              + f" — {', '.join(under)} "
              + ("is" if len(under) == 1 else "are")
              + " at or BELOW the null, i.e. no better than chance at "
                "attending inside the labelled objects.")
    A("")

    # ── failure cases ───────────────────────────────────────────────────────
    n_box, n_missed, below = failure_cases(per_image)
    if n_box:
        A("### Failure cases (full list in the note, §6)")
        A("")
        A(f"- **{n_missed} of {n_box}** `boxes20` images have the pointing "
          f"game missed by EVERY model. The teaser must not be read as "
          f"solving those.")
        A(f"- Images where a model attends inside the boxes LESS than chance "
          f"(`inbox_mass` < `box_area_frac`), of {n_box}: "
          + "; ".join(f"`{r}` {n}" for r, n in sorted(below.items())) + ".")
        A("")

    # ── what was not done ───────────────────────────────────────────────────
    A("## What was NOT done (and why)")
    A("")
    variants = {p.get("variant") for p in runs.values()}
    A("| not done | why | cost to fix |")
    A("|---|---|---|")
    if "ttr" not in variants:
        A("| **The TTR column of Figure 1** | TASK 10 had produced no "
          "test-time-registers model when Phase B ran, so the column renders "
          "as an explicit dotted `pending` panel. TASK 10 has since completed "
          "Phases A–C and its run dirs exist. | Wire TASK-10's builder into "
          "`tools/dump_attention.py --model-builder module:function` and "
          "re-run the dump for that row; the other five models skip "
          "themselves on the idempotency guard, so minutes of GPU. |")
    A("| **Seed-level error bars** | One training run per cell. The 2xSE "
      "flags are over images. | A second seed per cell (300-epoch ViT-S runs) "
      "— expensive, and the framing question below may make it moot. |")
    for arch in archs:
        have = {r["variant"] for r in rows if r["arch"] == arch}
        for v in ("registers", "saga", "baseline"):
            if v not in have:
                A(f"| **{arch} / {v}** | No such run exists in the project. "
                  f"Reported ABSENT, never zero, never pooled across "
                  f"architectures. | A full training run. |")
    A("| **Curated images were never scored** | `curated` is the figure's "
      "illustration set only; all statistics come from `random200` and "
      "`boxes20`. This is deliberate — scoring the displayed images would "
      "make the panels part of the number they are captioned with. | n/a, "
      "this is the correct design. |")
    A("| **Per-image criterion verification** | The curated criteria are "
      "CLASS-LEVEL priors (`criterion_basis: class_prior`): the builder "
      "picks a synset pool per criterion and samples it. An individual image "
      "may not be a perfect example of its label. | "
      "`tools/build_probe_set.py --curated-paths FILE` accepts hand-chosen "
      "paths and records `criterion_basis: explicit_paths`. |")
    A("| **The framing decision** | The teaser's own number favours "
      "registers over SAGA. That is a paper-framing question, not a "
      "technical one, and it is explicitly left to the human. | — |")
    A("")

    # ── evidence base ───────────────────────────────────────────────────────
    A("## What the evidence base actually is")
    A("")
    A("### The frozen probe set (`results/probe/probe_set.json`)")
    A("")
    A("| group | n | status | sha256 | what it is for |")
    A("|---|---|---|---|---|")
    purpose = {
        "curated": "the 12 Figure-1 candidates; NEVER the basis of a statistic",
        "random200": "the population for every ImageNet statistic",
        "boxes20": "the population for the in-box metric",
    }
    for name in ("curated", "random200", "boxes20"):
        g = probe["groups"].get(name)
        if not g:
            continue
        A(f"| `{name}` | {g['n']} | {g['status']} | "
          f"`{str(g.get('sha256', '-'))[:12]}` | {purpose[name]} |")
    A("")
    A("Frozen forever and write-once **per group**: each carries a sha256 "
      "over its own canonical serialization, and building a later group "
      "re-verifies the earlier ones rather than trusting them. Paths are "
      "relative, never dataset indices.")
    A("")
    cur = probe["groups"]["curated"]
    A("Curated criteria (4 images each, class-level priors):")
    A("")
    for k, v in sorted(cur.get("criteria", {}).items()):
        A(f"- **`{k}`** — {v}")
    A("")

    A("### The five models dumped")
    A("")
    A("| run_id | arch | variant | prefix tokens | ckpt sha256 |")
    A("|---|---|---|---|---|")
    for rid, prov in sorted(runs.items()):
        A(f"| `{rid}` | {prov.get('arch')} | {prov.get('variant')} | "
          f"{prov.get('num_prefix_tokens')} | "
          f"`{str(prov.get('ckpt_sha256'))[:12]}` |")
    A("")
    A(f"Prefix-token counts come from the MODEL, never assumed — 1 for "
      f"baseline/SAGA, 5 for timm registers (CLS + 4 register tokens). "
      f"`{loc_meta['n_rows']}` rows in the per-image CSV, "
      f"`{len(loc_meta.get('absent', []))}` absent.")
    A("")
    reg = [rid for rid, p in runs.items() if p.get("variant") == "registers"]
    if reg:
        A(f"> **`{reg[0]}` is not seed-matched to the others.** It is a "
          f"LEGACY e2-era checkpoint (manifest seed `rlast`, no seed "
          f"control); the baseline and SAGA runs are the clean seeded e2r "
          f"reruns. Per the recipe erratum it belongs to the same "
          f"(vit_small, mixup) cell, so the comparison is legitimate — but "
          f"it mixes a training-era difference into every registers delta "
          f"above. This is the single biggest caveat on the headline.")
        A("")

    # ── artifacts ───────────────────────────────────────────────────────────
    A("## Artifacts — which file holds which result")
    A("")
    A("### Committed results")
    A("")
    A("| file | what is in it |")
    A("|---|---|")
    A(f"| `results/notes/teaser.md` | **the results note**, generated. The 3 "
      f"chosen images + criteria, missing/pending panels, the full table "
      f"with nulls, the honest reading, the caveat block, and the failure "
      f"cases. Read this first. |")
    A(f"| `results/tables/T_localization.csv` | **every aggregate number** — "
      f"{len(rows)} rows, one per (arch, group, metric, run): n, mean, "
      f"sample std, SE, null, paired-by-image delta vs that architecture's "
      f"baseline, delta SE, 2xSE flag, direction, Welch p. |")
    A(f"| `results/figures_data/F1_localization.csv` | **the per-image "
      f"values** — {loc_meta['n_rows']} rows of "
      f"(run_id, group, image_id, metric, value). Everything above is an "
      f"aggregate of this file. |")
    A("| `results/figures_data/F1_localization_meta.json` | provenance for "
      "the above: per-run ckpt sha256, arch, variant, prefix-token count, "
      "the dumping git sha, and the `absent` list. |")
    A("| `results/tables/T_localization_meta.json` | which run_ids belong to "
      "which architecture, the source CSV, and the generating git sha. |")
    A(f"| `results/figures_data/F1_teaser.npz` | **the figure's arrays** "
      f"({len(archive_keys)} of them): 12 thumbnails, per-model attention "
      f"maps for all 12 curated images, SAGA gate maps at layers "
      f"{index.get('gate_layers')}, TASK-07 sink-frequency maps, the "
      f"ring-1 mask ({ring_cells} of {grid * grid} patches), and an `index` "
      f"recording provenance and what is ABSENT. |")
    A("| `results/probe/probe_set.json` | **the frozen probe set** — the "
      "three groups, their per-group sha256, the selector that produced "
      "each, and the per-image criterion for `curated`. |")
    A("| `results/figures/F1_teaser_draft.pdf` | **the figure**. Rows = 3 "
      "curated images; columns = Input / Baseline / Registers / TTR / SAGA; "
      "population means under each column; bottom strip = baseline sink map, "
      "ring-1 mask, SAGA gate. |")
    A("")
    A("### Code")
    A("")
    A("| file | phase | what it does |")
    A("|---|---|---|")
    A("| `tools/build_probe_set.py` | A | freezes the probe set; write-once "
      "per group; stdlib only (no torch) so it runs on a login node |")
    A("| `tools/dump_attention.py` | A | per-image attention npz; prefix "
      "count from the model; `--model-builder` hook for TTR; idempotent on "
      "(ckpt sha, probe sha, schema) |")
    A("| `tools/localization_score.py` | A | the metrics; ring imported from "
      "TASK-07, box frame reproduced from the real val transform |")
    A("| `analysis/collect_F1.py` | A | builds the committed figure archive "
      "from the HPC-resident dumps |")
    A("| `plotting/plot_F1.py` | A/C | renders the figure; missing column "
      "renders as `pending` |")
    A("| `analysis/build_localization_tables.py` | C | `T_localization.csv` |")
    A("| `analysis/build_teaser_note.py` | C | `teaser.md` |")
    A("| `analysis/build_task11_handoff.py` | C | this document |")
    A("| `scripts/jobs/probe_attention.sbatch`, `scripts/stage_probe.sh` | "
      "A | the Phase-B job; val-only staging, scratch released on every exit "
      "path |")
    n_a = count_test_defs(Path("tests/test_task11_probe.py"))
    n_c = count_test_defs(Path("tests/test_task11_phasec.py"))
    A(f"| `tests/test_task11_probe.py`, `tests/test_task11_phasec.py` | A/C | "
      f"{n_a} + {n_c} test functions; pytest collects more, since some are "
      f"parametrized (over the three model variants, and over five image "
      f"shapes) |")
    A("")

    A("### NOT committed, and must not be deleted")
    A("")
    A("The raw attention dumps `<attn-root>/<run_id>/attn/probe_*.npz` are "
      "git-ignored (`results/**/attn/`) and live only on the HPC — about "
      "3 GB for these five models. `analysis/collect_F1.py` and every later "
      "figure read them. They were written to "
      "`/home/woody/iwi5/iwi5359h/SAGA/probe_attn` via the job's "
      "`ATTN_ROOT` override, because the `hpc` filesystem was over its soft "
      "quota.")
    A("")

    # ── regenerate ──────────────────────────────────────────────────────────
    A("## Regenerate")
    A("")
    A("### Everything downstream of the dumps (local, no GPU)")
    A("")
    A("```bash")
    A("python analysis/build_localization_tables.py")
    A("python analysis/build_teaser_note.py")
    A("python analysis/build_task11_handoff.py")
    A("pytest -q")
    A("```")
    A("")
    A("The figure needs its image selection passed explicitly so the note and "
      "the figure cannot disagree (a test pins that they agree):")
    A("")
    A("```bash")
    A("python plotting/plot_F1.py \\")
    A("    --columns \"Baseline=e2r_vits_mixup_baseline_s1,"
      "Registers=legacy_vits_registers,TTR=,SAGA=e2r_vits_mixup_saga_s1\"")
    A("```")
    A("")
    A("### The dumps themselves (HPC only)")
    A("")
    A("```bash")
    A("ATTN_ROOT=/home/woody/iwi5/iwi5359h/SAGA/probe_attn \\")
    A("    sbatch --partition=a100 --gres=gpu:a100:1 --cpus-per-task=8 \\")
    A("    scripts/jobs/probe_attention.sbatch")
    A("```")
    A("")
    A("Idempotent throughout: the probe set refuses to rebuild a frozen "
      "group, and the dumper skips any npz whose recorded ckpt sha, probe "
      "sha and schema all match. A resubmitted job burns no GPU.")
    A("")

    # ── provenance warnings ─────────────────────────────────────────────────
    A("## Provenance warnings for whoever picks this up")
    A("")
    A("- **Phase B's artifacts arrived in commit `c5320d2` (\"Results\").** "
      "A generic message covering an HPC pull; the TASK-11 files in it are "
      "the four Phase-B outputs. The same pattern as TASK-07's `efd4f9d "
      "(\"Task 9\")`. Verify by path, not by commit subject.")
    A("- **Commit `e97a293` says \"TASK-11/12 Phase C landed\" — that was "
      "premature for TASK 11.** Its Phase C landed later, in `78a3a0c` "
      "(merged `48c6e2b`). Do not date the teaser work from `e97a293`.")
    A("- **`scripts/jobs/probe_attention.sbatch` carries a TASK-10 edit.** "
      "`da4e631` moved `set -u` BELOW the env sourcing: `env_alex.sh` "
      "sources `/etc/profile`, whose site scripts dereference unset "
      "variables (`debuginfod.sh`, `DEBUGINFOD_URLS`), so the original "
      "ordering aborted the job during setup. Measured on Alex by TASK 10, "
      "which inherited the bug by copying this header. Do not revert it.")
    A("- **The job header still says `--partition=a40`.** The Phase-B run "
      "was submitted with an a100 override on the command line; the file "
      "was not changed. Either works.")
    A("- **`box_area_frac` and `uniform_ring1_mass` are nulls, not "
      "results.** They are properties of the image and the grid, identical "
      "across models by construction; the table builder asserts that to "
      "1e-9 and refuses to publish them as a reference if it ever fails.")
    A("- **Diagnostics come from the LAST checkpoint**, consistent with the "
      "rest of the project.")
    A("")
    A("---")
    A("")
    A("Open for the human: (a) how to frame a teaser whose number favours "
      "registers; (b) whether to fill the TTR column; (c) whether to add "
      "seeds so these deltas carry seed-level rather than image-level error "
      "bars.")

    atomic_write_text("\n".join(L) + "\n", Path(args.out))
    print(f"wrote {args.out} ({len(L)} lines); "
          f"{len(rows)} table rows, {len(sig)} significant deltas, "
          f"{len(runs)} runs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
