#!/usr/bin/env python3
"""
analysis/build_recipe_erratum.py
================================
TASK-06B 1.3: generate results/notes/recipe_erratum.md — the permanent
record of the recipe-identity finding. The config diffs stated in the note
are RECOMPUTED here on every run: the legacy resolver is taken verbatim from
git (commit 31f4bac, the last commit carrying the legacy trainer) and
executed against the committed YAMLs; the current resolver is imported from
classification/tools/train.py.

    python analysis/build_recipe_erratum.py \
        [--out results/notes/recipe_erratum.md]
"""

import argparse
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "classification" / "tools"))

LEGACY_TRAINER_COMMIT = "31f4bac"


def legacy_resolver():
    """load_yaml/deep_merge/load_config, verbatim from the legacy trainer."""
    src = subprocess.check_output(
        ["git", "show", f"{LEGACY_TRAINER_COMMIT}:classification/tools/train.py"],
        text=True, cwd=REPO)
    ns = {"yaml": yaml, "Path": Path}
    for fn in ("def load_yaml", "def deep_merge", "def load_config"):
        start = src.index(fn)
        end = src.index("\n\n\n", start)
        exec(compile(src[start:end], "legacy_train", "exec"), ns)
    return ns["load_config"]


def flatten(d, prefix=""):
    out = {}
    for k, v in d.items():
        key = f"{prefix}{k}"
        if isinstance(v, dict):
            out.update(flatten(v, key + "."))
        else:
            out[key] = v
    return out


IGNORE = ("paths.", "variant_id", "variant", "name", "run_id", "recipe",
          "seed", "knobs.", "instrumentation.")


def config_diff(a, b):
    fa, fb = flatten(a), flatten(b)
    rows = []
    for k in sorted(set(fa) | set(fb)):
        if any(k.startswith(i) or k == i.rstrip(".") for i in IGNORE):
            continue
        va, vb = fa.get(k, "<absent>"), fb.get(k, "<absent>")
        if va != vb:
            rows.append((k, va, vb))
    return rows


def main():
    parser = argparse.ArgumentParser(description="Generate the recipe erratum.")
    parser.add_argument("--out", default="results/notes/recipe_erratum.md")
    args = parser.parse_args()

    load_config = legacy_resolver()
    lg_mixup = load_config(str(REPO / "classification/configs/variants.yaml"),
                           0, str(REPO / "classification/configs/paths.yaml"))
    lg_nomix = load_config(
        str(REPO / "classification/configs/variants_nomix.yaml"),
        0, str(REPO / "classification/configs/paths.yaml"))
    legacy_diff = config_diff(lg_mixup, lg_nomix)

    import train as new_trainer
    matrix = str(REPO / "configs/e2r_matrix.yaml")
    new_mixup = new_trainer.resolve_run_config(matrix,
                                               "e2r_vits_mixup_baseline_s1")
    new_nomix = new_trainer.resolve_run_config(matrix,
                                               "e2r_vits_nomix_baseline_s1")
    truenomix_diff = config_diff(new_mixup, new_nomix)
    lg_aug = lg_nomix["augmentation"]

    L = [
        "# Recipe-identity erratum — the legacy \"nomix\" label is false",
        "",
        f"Generated by `analysis/build_recipe_erratum.py` (diffs recomputed "
        f"on every run); {datetime.now(timezone.utc).date().isoformat()}. "
        "Facts only.",
        "",
        "## Finding",
        "",
        "Every legacy e2 run trained WITH MixUp+CutMix, including all runs "
        "in `*_nomix` directories. **Cell identity comes from the RESOLVED "
        "training config, never from a directory name.** New column "
        "`recipe_actual` everywhere; the old `recipe` column is a directory "
        "name (`recipe_dirname`).",
        "",
        "## Mechanical proof",
        "",
        f"1. The legacy resolver (`load_config` in "
        f"`classification/tools/train.py` at commit "
        f"`{LEGACY_TRAINER_COMMIT}`, executed verbatim by this script) "
        "merges only `_base_` plus the matched variant entry "
        "(`id/name/model`). The top-level `augmentation:` block of "
        "`variants_nomix.yaml` — the only place mixing was disabled — was "
        "therefore never merged. `base_nomix.yaml` is referenced by no "
        "legacy code path.",
        f"2. Resolved-config diff, legacy nomix launch vs legacy mixup "
        f"launch (ViT-S id 0), recomputed now: "
        + ("**ZERO differing keys**." if not legacy_diff else
           "; ".join(f"{k}: {va} vs {vb}" for k, va, vb in legacy_diff)),
        f"   The resolved legacy \"nomix\" augmentation block: "
        f"mixup_alpha={lg_aug['mixup_alpha']}, "
        f"cutmix_alpha={lg_aug['cutmix_alpha']}, "
        f"rand_aug={lg_aug['rand_aug']} "
        f"(m{lg_aug['rand_aug_magnitude']}/n{lg_aug['rand_aug_layers']}), "
        f"random_erase_prob={lg_aug['random_erase_prob']}.",
        "3. Ground truth from the cluster (checked by the human, "
        "2026-09-04): the resolved config the legacy trainer itself dumped, "
        "`$OUT_ROOT/e2/checkpoints/ViT-S_baseline_nomix/config.yaml`, shows "
        "`mixup_alpha: 0.8, cutmix_alpha: 1.0`. The Part-2 provenance "
        "harvest commits all 12 dumped configs to "
        "`results/legacy/resolved_configs/`.",
        "",
        "## Relabeling (old cell -> recipe_actual)",
        "",
        "| legacy cell (dirname) | recipe_actual | consequence |",
        "|---|---|---|",
        "| ViT-S/mixup (3 runs) | mixup | unchanged |",
        "| ViT-S/nomix (3 runs) | **mixup** | additional repeats of the "
        "ViT-S/mixup cell -> 4 repeats per variant with e2r s1+s2 |",
        "| ViT-B/mixup (3 runs, incomplete) | mixup | still void "
        "(never completed training; see bmixup_forensics.md) |",
        "| ViT-B/nomix (3 runs) | **pending** | produced by configs not in "
        "git; cited NOWHERE until the Part-2 harvest resolves them |",
        "",
        "## What defines the TRUE-nomix cell (the parked e2r chains)",
        "",
        "Resolved-config diff of the new trainer's recipe 'nomix' vs "
        "'mixup' (recomputed now) — the complete intervention:",
        "",
    ]
    for k, va, vb in truenomix_diff:
        L.append(f"- `{k}`: {va} (mixup) -> {vb} (true-nomix)")
    L += [
        "",
        "Mechanical consequences in the trainer (identical conditional in "
        "legacy and new code): the timm `Mixup` op is not applied (raw "
        "images, hard integer labels), and the training criterion switches "
        "from `SoftTargetCrossEntropy` to "
        "`LabelSmoothingCrossEntropy(smoothing=0.1)` (smoothing 0.1 is "
        "present in both regimes). Every other setting is identical.",
        "",
        "## Threshold governance (recorded reconciliation)",
        "",
        "TASK-06 1.2 asked to add `vit_base|mixup` to the v2 thresholds "
        "file calibrated on `e2r_vitb_mixup_baseline_s1`, but that key "
        "ALREADY exists in `fixed_thresholds_v2.json` — added in TASK-02C, "
        "calibrated on the legacy ViT-B/mixup baseline whose training never "
        "completed (last.pth at epoch 199; the cell is void). Recalibrating "
        "would overwrite recorded provenance. Reconciliation: the v2 file "
        "is FROZEN as TASK-02C provenance (its `vit_base|mixup` entry "
        "included, clearly void-sourced); all analysis from TASK-06B onward "
        "uses `fixed_thresholds_canon.json`, whose taus are calibrated per "
        "(arch, recipe_actual) on seeded e2r baselines — for ViT-B/mixup, "
        "exactly the source TASK-06 1.2 intended. v2 fields are never "
        "applied to e2r run dirs.",
        "",
    ]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L), encoding="utf-8", newline="\n")
    print(f"wrote {out}")
    print(f"legacy nomix-vs-mixup differing keys: {len(legacy_diff)}")
    print(f"true-nomix intervention keys: "
          f"{[k for k, _, _ in truenomix_diff]}")


if __name__ == "__main__":
    main()
