#!/usr/bin/env python3
"""
analysis/build_finegrained_note.py
==================================
TASK-08 Phase C.2/C.3: generate results/notes/finegrained.md from
results/tables/T3_finegrained.csv and the per-run test JSONs.

Facts only. EVERY number in the note is computed here from the committed
files — nothing is hand-typed, so re-running after a table rebuild cannot
leave stale prose behind (the TASK-02C lesson).

    python analysis/build_finegrained_note.py \
        [--table results/tables/T3_finegrained.csv] \
        [--out results/notes/finegrained.md]
"""

import argparse
import csv
import json
import math
from pathlib import Path

MISSING = "MISSING"
REPO = Path(__file__).resolve().parents[1]

# The VOID legacy e6 headline deltas this task supersedes (bug B7:
# official TEST split used as val + best.pth selected on it +
# eval-every-5-epochs => a test-tuned peak). Quoted here ONLY to record
# that they are retired; they are never compared against the new numbers.
LEGACY_VOID = {"aircraft": 2.19, "cub": 1.29}

ARCH_LABEL = {"vit_small_patch16_224": "ViT-S", "vit_base_patch16_224": "ViT-B"}
DS_LABEL = {"cub": "CUB-200-2011", "aircraft": "FGVC-Aircraft"}
VAL_TEST_FLAG_PTS = 2.0     # task C.2: flag any run disagreeing by >2 pts


def load_table(path):
    with open(path) as f:
        return list(csv.DictReader(f))


def num(v):
    if v in ("", MISSING, None):
        return MISSING
    return float(v)


def fmt(v, nd=3):
    return MISSING if v == MISSING else f"{v:.{nd}f}"


def pick(rows, dataset, arch, variant, kind, ft_seed=None):
    for r in rows:
        if (r["dataset"] == dataset and r["arch"] == arch
                and r["variant"] == variant and r["kind"] == kind
                and (ft_seed is None or r["ft_seed"] == ft_seed)):
            return r
    return None


def repeats(rows, dataset, arch, variant):
    return [r for r in rows if r["dataset"] == dataset and r["arch"] == arch
            and r["variant"] == variant and r["kind"] == "repeat"]


def binomial_se_pts(p_pct, n):
    """SE of a proportion estimate, in percentage points — the intrinsic
    noise floor of a val set of n images at accuracy p."""
    p = p_pct / 100.0
    return 100.0 * math.sqrt(p * (1 - p) / n)


def build(table_path, runs_root: Path):
    rows = load_table(table_path)
    cells = []
    seen = []
    for r in rows:
        key = (r["dataset"], r["arch"])
        if key not in seen:
            seen.append(key)
    for dataset, arch in seen:
        cells.append((dataset, arch))

    L = []
    A = L.append

    A("# Fine-grained transfer — clean protocol (TASK-08)")
    A("")
    A("Generated by `analysis/build_finegrained_note.py` from")
    A("`results/tables/T3_finegrained.csv` and the per-run")
    A("`results/runs/ft_*/eval/test_final.json` files. Facts only; every")
    A("number below is computed from those files.")
    A("")

    # ── 0. the void legacy numbers ────────────────────────────────────────
    A("## 0. The legacy e6 numbers are superseded and VOID")
    A("")
    A(f"The legacy fine-grained headline deltas "
      f"(**+{LEGACY_VOID['aircraft']:.2f} Aircraft, "
      f"+{LEGACY_VOID['cub']:.2f} CUB**) are **VOID and are never cited**.")
    A("`evaluation/e6_finegrained/tools/train.py` used the official TEST")
    A("split as its validation set, selected `best.pth` on it, and")
    A("evaluated every 5 epochs, so the reported peak was tuned on test")
    A("(bug B7); it also loaded backbones with `strict=False` without")
    A("checking unexpected keys. Those numbers are superseded by the table")
    A("below and must not be compared against it: they measure a different")
    A("(invalid) quantity, not a weaker version of the same one.")
    A("")

    # ── 1. protocol ───────────────────────────────────────────────────────
    A("## 1. Protocol actually used")
    A("")
    A("- Val split: a frozen, committed, seeded stratified 10% carve of the")
    A("  OFFICIAL TRAIN split (`results/ftsplit/<dataset>_val_split.json`);")
    A("  `best.pth` selected on it, checked EVERY epoch.")
    A("- The official TEST split is touched EXACTLY ONCE per run, after")
    A("  training, with the val-selected `best.pth` loaded ->")
    A("  `eval/test_final.json`. Second evaluations are refused by the")
    A("  trainer.")
    A("- Backbones: the seeded e2r mixup s1 checkpoints, strict-loaded")
    A("  (zero missing/unexpected keys) with the sha256 asserted against")
    A("  `configs/ft_matrix.yaml`.")
    A("- Hyperparameters mirror the legacy e6 trainer (AdamW backbone")
    A("  1e-5 / head 1e-3, wd 0.05, cosine to 1e-7, 100 epochs, batch 64,")
    A("  label smoothing 0.1, grad clip 1.0, 224px).")
    A("")

    # ── 2. per-cell tables ────────────────────────────────────────────────
    A("## 2. T3 — test top-1 by (dataset, arch, variant)")
    A("")
    A("Repeats are listed individually before any mean. Every value is the")
    A("official test split evaluated once with the val-selected checkpoint.")
    A("")
    for dataset, arch in cells:
        n_test = None
        for r in repeats(rows, dataset, arch, "baseline"):
            n_test = r["n_test_images"]
        A(f"### {DS_LABEL[dataset]} — {ARCH_LABEL[arch]} "
          f"(test n = {n_test})")
        A("")
        A("| variant | ft-seed | test top-1 | test top-5 | val top-1 @ best "
          "| best epoch |")
        A("|---|---|---|---|---|---|")
        for variant in ("baseline", "saga"):
            for r in repeats(rows, dataset, arch, variant):
                A(f"| {variant} | {r['ft_seed']} | "
                  f"{fmt(num(r['test_top1']))} | {fmt(num(r['test_top5']))} "
                  f"| {fmt(num(r['val_top1_at_best']))} | "
                  f"{r['best_epoch']} |")
        A("")
        for variant in ("baseline", "saga"):
            mean_r = pick(rows, dataset, arch, variant, "mean")
            std_r = pick(rows, dataset, arch, variant, "std")
            if mean_r is None:
                continue
            sd = num(std_r["test_top1"]) if std_r else MISSING
            A(f"- **{variant} mean test top-1 = "
              f"{fmt(num(mean_r['test_top1']))}** "
              f"(n = {mean_r['n']}, std = {fmt(sd, 4)})")
        dm = pick(rows, dataset, arch, "saga", "paired_delta_mean")
        dse = pick(rows, dataset, arch, "saga", "paired_delta_se")
        dsig = pick(rows, dataset, arch, "saga", "significant_2xSE")
        if dm is not None:
            per_seed = ", ".join(
                f"{r['ft_seed']} {num(r['test_top1']):+.3f}"
                for r in rows
                if r["dataset"] == dataset and r["arch"] == arch
                and r["kind"] == "paired_delta"
                and num(r["test_top1"]) != MISSING)
            mu = num(dm["test_top1"])
            se = num(dse["test_top1"]) if dse else MISSING
            sig = dsig["test_top1"] if dsig else MISSING
            sig_txt = {"1": "YES", "0": "no"}.get(str(sig), MISSING)
            n_pairs = int(dm["n"]) if str(dm["n"]).isdigit() else 0
            A("")
            A(f"- **SAGA paired Δ (by ft-seed) = "
              f"{('%+.3f' % mu) if mu != MISSING else MISSING}** "
              f"(n = {dm['n']} pair{'' if n_pairs == 1 else 's'}; "
              f"per-seed: {per_seed})")
            A(f"  - SE = {fmt(se, 4)}; significant at 2×SE: **{sig_txt}**")
            if se != MISSING and sig_txt != MISSING:
                direction = ("SAGA above baseline" if mu > 0
                             else "SAGA BELOW baseline" if mu < 0
                             else "no difference")
                margin = abs(mu) - 2 * se
                A(f"  - direction: **{direction}**; "
                  f"|Δ| − 2×SE = {margin:+.4f} "
                  f"(the 2×SE threshold is {2 * se:.4f})")
                if sig_txt == "YES" and margin < 0.25 * 2 * se:
                    A(f"  - the verdict clears the threshold by a thin "
                      f"margin on n = {n_pairs} seeds; read it as a "
                      f"direction, not a precise effect size")
            if se == MISSING:
                A(f"  - single ft-seed by design ⇒ no std, no SE, **no")
                A(f"    significance claim is possible for this cell**; the")
                A(f"    delta is one paired observation.")
            wt = pick(rows, dataset, arch, "saga", "welch_t")
            wp = pick(rows, dataset, arch, "saga", "welch_p")
            if wp is not None and num(wp["test_top1"]) != MISSING:
                A(f"  - unpaired robustness: Welch t = "
                  f"{fmt(num(wt['test_top1']), 4)}, "
                  f"p = {fmt(num(wp['test_top1']), 4)}")
        A("")

    # ── 3. sanity paragraph (task C.2) ────────────────────────────────────
    A("## 3. Sanity checks")
    A("")
    all_reps = [r for r in rows if r["kind"] == "repeat"]
    peaked_early, peaked_last, unknown = [], [], []
    for r in all_reps:
        be, ep = num(r["best_epoch"]), num(r["epochs_trained"])
        if be == MISSING or ep == MISSING:
            unknown.append(r)
        elif be < ep - 1:
            peaked_early.append(r)
        else:
            peaked_last.append(r)
    A(f"**Val curve peaked before the final epoch?** "
      f"{len(peaked_early)} of {len(all_reps)} runs peaked strictly before "
      f"their final epoch; {len(peaked_last)} peaked at (or one before) the "
      f"last epoch"
      + (f"; {len(unknown)} could not be determined" if unknown else "")
      + ".")
    if peaked_early:
        bes = [num(r["best_epoch"]) for r in peaked_early]
        eps = sorted({int(num(r["epochs_trained"])) for r in peaked_early})
        A("")
        A(f"Best epochs range {int(min(bes))}..{int(max(bes))} out of "
          f"{'/'.join(str(e) for e in eps)} trained. Selecting on the "
          f"held-out val split therefore changed which weights were "
          f"evaluated for these runs — the final-epoch weights were not the "
          f"val-best weights.")
    if peaked_last:
        A("")
        A("Runs peaking at the last epoch (schedule may be too short):")
        for r in peaked_last:
            A(f"- {r['dataset']} {ARCH_LABEL[r['arch']]} {r['variant']} "
              f"{r['ft_seed']}: best epoch {r['best_epoch']} of "
              f"{r['epochs_trained']}")
    A("")

    flagged = []
    for r in all_reps:
        gap = num(r["val_minus_test"])
        if gap != MISSING and abs(gap) > VAL_TEST_FLAG_PTS:
            flagged.append((r, gap))
    A(f"**Val vs test disagreement > {VAL_TEST_FLAG_PTS:.0f} pts:** "
      f"{len(flagged)} of {len(all_reps)} runs flagged.")
    if flagged:
        A("")
        A("| run | val top-1 @ best | test top-1 | val − test |")
        A("|---|---|---|---|")
        for r, gap in sorted(flagged, key=lambda t: -abs(t[1])):
            A(f"| {r['dataset']} {ARCH_LABEL[r['arch']]} {r['variant']} "
              f"{r['ft_seed']} | {fmt(num(r['val_top1_at_best']))} | "
              f"{fmt(num(r['test_top1']))} | {gap:+.3f} |")
    gaps = [g for _, g in
            [(r, num(r["val_minus_test"])) for r in all_reps]
            if g != MISSING]
    if gaps:
        A("")
        A(f"All {len(gaps)} gaps have the same sign convention "
          f"(val − test); range {min(gaps):+.3f} .. {max(gaps):+.3f}, "
          f"mean {sum(gaps) / len(gaps):+.3f}. "
          f"{sum(1 for g in gaps if g > 0)} of {len(gaps)} are positive "
          f"(val optimistic relative to test).")
        A("")
        A("Scale for reading those gaps: the val splits are small, so their")
        A("own sampling noise is of the same order as the flag threshold.")
        for dataset in dict.fromkeys(d for d, _ in cells):
            accs = [num(r["val_top1_at_best"]) for r in all_reps
                    if r["dataset"] == dataset
                    and num(r["val_top1_at_best"]) != MISSING]
            if not accs:
                continue
            split = json.load(open(
                REPO / "results" / "ftsplit" / f"{dataset}_val_split.json"))
            acc = sum(accs) / len(accs)
            se = binomial_se_pts(acc, split["n_val"])
            A(f"- {DS_LABEL[dataset]}: val n = {split['n_val']} ⇒ binomial "
              f"SE ≈ {se:.2f} pts at the cell's mean val accuracy "
              f"{acc:.1f}%")
        A("")
        A("A val-selected maximum over many epochs is additionally biased")
        A("upward relative to an independent test estimate, so a positive")
        A("val − test gap of this size is expected and is not evidence of a")
        A("protocol fault. It is reported here, not corrected for.")
    A("")

    # ── 4. provenance ─────────────────────────────────────────────────────
    A("## 4. Provenance")
    A("")
    A("| run | backbone | backbone sha256 (12) | val split sha256 (12) | "
      "test n | git sha (12) |")
    A("|---|---|---|---|---|---|")
    for dataset, arch in cells:
        for variant in ("baseline", "saga"):
            for r in repeats(rows, dataset, arch, variant):
                run_id = (f"ft_{dataset}_"
                          f"{'vits' if 'small' in arch else 'vitb'}_"
                          f"{variant}_bs1_{r['ft_seed']}")
                p = runs_root / run_id / "eval" / "test_final.json"
                if not p.exists():
                    A(f"| {run_id} | {MISSING} | {MISSING} | {MISSING} | "
                      f"{MISSING} | {MISSING} |")
                    continue
                d = json.load(open(p))
                A(f"| {run_id} | {d.get('backbone_run', MISSING)} | "
                  f"`{d.get('backbone_sha256', '')[:12]}` | "
                  f"`{d.get('val_split_sha256', '')[:12]}` | "
                  f"{d.get('n_images', MISSING)} | "
                  f"`{d.get('git_sha', '')[:12]}` |")
    A("")
    A("Split files: " + ", ".join(
        f"{DS_LABEL[ds]} "
        f"{json.load(open(REPO / 'results' / 'ftsplit' / f'{ds}_val_split.json'))['n_official_train']}"
        f" official train → "
        f"{json.load(open(REPO / 'results' / 'ftsplit' / f'{ds}_val_split.json'))['n_train']}"
        f" train + "
        f"{json.load(open(REPO / 'results' / 'ftsplit' / f'{ds}_val_split.json'))['n_val']}"
        f" val (seed "
        f"{json.load(open(REPO / 'results' / 'ftsplit' / f'{ds}_val_split.json'))['seed']})"
        for ds in dict.fromkeys(d for d, _ in cells)) + ".")
    A("")
    return "\n".join(L) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Generate results/notes/finegrained.md (facts only).")
    parser.add_argument("--table", default="results/tables/T3_finegrained.csv")
    parser.add_argument("--runs-root", default="results/runs")
    parser.add_argument("--out", default="results/notes/finegrained.md")
    args = parser.parse_args()

    text = build(args.table, Path(args.runs_root))
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
