#!/usr/bin/env python3
"""
analysis/build_task07_handoff.py
================================
Render docs/TASK_07_HANDOFF.md — the one-document summary of TASK 07 for a
reader who was not in the session (a collaborator, or a future session).

Every experimental number is READ FROM the committed results tables
(`results/tables/sink_address.csv`, `results/tables/e2_pooled.csv`), never
typed here, so the handoff cannot drift from the data and re-running this
script after new runs land updates it. The prose that surrounds those
numbers is fixed text: task structure, method, provenance, commands.

    python analysis/build_task07_handoff.py
"""

import argparse
import csv
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from analysis.build_sink_address_note import (ALPHA, Table, cell_label, fmt,
                                              gate_extremes, rng_txt)

CELLS = [("vit_small", "mixup"), ("vit_small", "nomix"),
         ("vit_base", "mixup")]
VARIANTS = ["baseline", "saga", "registers"]
MISSING = "MISSING"


def load(path: Path):
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def git_sha() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                              capture_output=True, text=True,
                              check=True).stdout.strip()
    except Exception:
        return "unknown"


def repeat_counts(t: Table):
    """(cell, variant) -> number of repeats actually used."""
    out = {}
    for arch, rec in CELLS:
        for variant in VARIANTS:
            r = t.one(question="Q1_concentration", arch=arch,
                      recipe_actual=rec, map_basis="canon", variant=variant,
                      subject="MEAN", statistic="gini")
            out[(arch, rec, variant)] = int(r["n"]) if r else 0
    return out


def pooled_lookup(pooled, arch, rec, variant, kind, metric="top1_last"):
    """The single row of this kind, formatted, or None."""
    for r in pooled:
        if (r["arch"] == arch and r["recipe_actual"] == rec
                and r["variant"] == variant and r["kind"] == kind):
            v = r[metric]
            if v in ("", MISSING):
                return None
            try:
                if kind == "significant_2xSE":      # a 0/1 flag, not a value
                    return str(int(float(v)))
                return f"{float(v):+.3f}" if kind.endswith("delta_mean") \
                    else f"{float(v):.3f}"
            except ValueError:
                return v
    return None


def pooled_deltas(pooled, arch, rec, variant, metric="top1_last"):
    """[(provenance, formatted value)] for EVERY paired delta — the spread
    between them is the reason the mean is or is not significant, so all of
    them must be quoted, not just the first."""
    out = []
    for r in pooled:
        if (r["arch"] == arch and r["recipe_actual"] == rec
                and r["variant"] == variant and r["kind"] == "paired_delta"
                and r[metric] not in ("", MISSING)):
            out.append((r["provenance"], f"{float(r[metric]):+.3f}"))
    return out


# ── sections ─────────────────────────────────────────────────────────────────

def section_status(lines, sha):
    lines += [
        "# TASK 07 — sink-address analysis: handoff", "",
        f"GENERATED by `analysis/build_task07_handoff.py` at git `{sha}`. "
        "Every experimental number below is read from "
        "`results/tables/sink_address.csv` and `results/tables/"
        "e2_pooled.csv`; none is typed by hand. Re-run the script after new "
        "runs land and this document updates itself.", "",
        "## Status", "",
        "| phase | what | state |", "|---|---|---|",
        "| A | `tools/sink_address.py` + optional-run prep | **done** "
        "(`86122e8`) |",
        "| B | HPC: 44 `_addr.json` maps; registers smoke | **done** "
        "(`7ad53a1`, smoke in `fd98185`) |",
        "| C | analysis, figure, note | **done** (`17ccb2a`, log "
        "`01170fa`) |",
        "| A2 | four optional strengthening runs | **prepared, not "
        "submitted** — the human's call |", "",
        "Nothing is pending from the HPC. The task's conclusions are "
        "complete and stated below with their limitations.", "",
        "## The question this task had to settle", "",
        "Whether the paper's central mechanism claim holds: that sinks form "
        "at predictable positions (an \"address\"), that the address is a "
        "property of training rather than of one model, and that SAGA's "
        "learned gate relates to it. The five sub-questions below are the "
        "task's own.", "",
    ]


def section_method(lines):
    lines += [
        "## How to read these numbers (read this before quoting any)", "",
        "An adversarial review of the first Phase-C pass returned 11 "
        "confirmed findings; two of them had inverted a reported result. "
        "Both are now modelled explicitly, and neither reference is zero:",
        "",
        "**1. Concentration has a finite-sample floor.** A *spatially "
        "uniform* ground truth does not produce Gini 0 when it is estimated "
        "from 10000 images. At ~20 sinks per image the null Gini is about "
        "0.017; at ~0.02 sinks per image it is about 0.49. Sink mass spans "
        "three orders of magnitude across variants, so RAW Gini, entropy "
        "and top-k shares are not comparable between them. Every "
        "concentration statistic therefore carries its own null (`*_null`, "
        "a binomial null at that map's own mass) and an excess value "
        "(`*_excess`), and Q4 reports PAIRED differences of excess. "
        "Differencing raw values instead flips the sign of the registers "
        "result.", "",
        "**2. The 196 positions are not 196 independent samples.** The maps "
        "are spatially smooth, so the iid Spearman reference (sd 0.0716) is "
        "far too generous. Every correlation carries an exact permutation "
        "p-value over the 8 dihedral x 196 torus-roll transforms of one map "
        "(1568 transforms, deterministic, no seed), which preserves both "
        "maps' autocorrelation. Under it the effective sample size is "
        "roughly 20, not 196 — so use the p-value, not the `n` column, "
        "which is the position count.", "",
        f"Significance below means p < {ALPHA} under that permutation null. "
        "Q5's per-run extremal layer is an argmax over 12 layers, so it also "
        "carries a Bonferroni-corrected p.", "",
    ]


def section_answers(t: Table, lines):
    lines += ["## Answers", ""]

    # Q1
    lines += ["### 1. Does an address exist? Yes, but it is diffuse.", "",
              "| cell | n | mean sinks/image | H/H_uniform | excess Gini | "
              "top-5 share | x uniform |", "|---|---|---|---|---|---|---|"]
    for arch, rec in CELLS:
        kw = dict(question="Q1_concentration", arch=arch, recipe_actual=rec,
                  map_basis="canon", variant="baseline", subject="MEAN")
        row = t.one(**kw, statistic="gini")
        if row is None:
            continue
        t5 = t.num(**kw, statistic="top5_share")
        lines.append(
            f"| {cell_label(arch, rec)} | {row['n']} | "
            f"{fmt(t.num(**kw, statistic='total_mass'))} | "
            f"{fmt(t.num(**kw, statistic='entropy_normalized'))} | "
            f"{fmt(t.num(**kw, statistic='gini_excess'))} | {fmt(t5)} | "
            f"{t5 / (5 / 196):.2f}x |")
    lines += ["", "Entropy sits close to the uniform 1.0 everywhere, yet "
              "the top-5 positions carry several times their uniform share "
              "and the excess Gini is positive in every baseline cell. The "
              "sink mass is spread widely but not evenly.", ""]

    # geometry
    lines += ["### 1b. Where is it? A ring one patch inside the border.", "",
              "Mean sink frequency per ring of constant distance from the "
              "grid border (ring 0 = outermost row/column, ring 6 = centre), "
              "canon maps, baseline repeats:", "",
              "| cell | ring0 | ring1 | ring2 | ring3 | ring4 | ring5 | "
              "ring6 | peak |", "|---|---|---|---|---|---|---|---|---|"]
    for arch, rec in CELLS:
        vals, peaks = [], []
        for k in range(7):
            v = t.nums(question="Q1b_geometry", arch=arch, recipe_actual=rec,
                       map_basis="canon", variant="baseline",
                       statistic=f"ring{k}_mean_freq")
            vals.append(sum(v) / len(v) if v else None)
        peaks = t.nums(question="Q1b_geometry", arch=arch, recipe_actual=rec,
                       map_basis="canon", variant="baseline",
                       statistic="peak_ring")
        if not peaks:
            continue
        lines.append(f"| {cell_label(arch, rec)} | "
                     + " | ".join(fmt(v) for v in vals)
                     + f" | {', '.join(str(int(p)) for p in sorted(set(peaks)))} |")
    lines += ["", "The two mixup cells peak on ring 1. The true-nomix cell "
              "is essentially flat, which is the same fact Q3 reports as a "
              "correlation: the border address is created by the "
              "MixUp/CutMix recipe, not by ViT training as such.", ""]

    # Q2
    lines += ["### 2. Is it seed-stable? Yes — this is the make-or-break "
              "number, and it holds.", "",
              "Spearman between baseline maps of a cell's repeats, all "
              "pairs:", "",
              "| cell | n pairs | mean rho | range | p range | "
              f"pairs p<{ALPHA} |", "|---|---|---|---|---|---|"]
    for arch, rec in CELLS:
        kw = dict(question="Q2_seed_stability", arch=arch, recipe_actual=rec,
                  map_basis="canon", variant="baseline", subject="all-pairs")
        m = t.one(**kw, statistic="spearman_mean")
        if m is None or m["value"] in (MISSING, ""):
            continue
        ps = t.nums(question="Q2_seed_stability", arch=arch,
                    recipe_actual=rec, map_basis="canon", variant="baseline",
                    statistic="spearman_p_spatial")
        lines.append(
            f"| {cell_label(arch, rec)} | {m['n']} | "
            f"{fmt(float(m['value']))} | "
            f"{fmt(t.num(**kw, statistic='spearman_min'))} to "
            f"{fmt(t.num(**kw, statistic='spearman_max'))} | "
            f"{rng_txt(ps)} | {sum(1 for p in ps if p < ALPHA)}/{len(ps)} |")
    all_ps = t.nums(question="Q2_seed_stability", map_basis="canon",
                    variant="baseline", statistic="spearman_p_spatial")
    lines += ["", f"Across all cells, {sum(1 for p in all_ps if p < ALPHA)} "
              f"of {len(all_ps)} baseline pairs are significant. The "
              "ViT-S/mixup pairs span legacy runs and fresh seeded reruns "
              "months apart under different trainer code, so the address is "
              "a property of the training distribution, not of a "
              "particular model.", ""]

    # Q3
    lines += ["### 3. Is it recipe-stable? No.", "",
              "| basis | n pairs | mean rho | range | "
              f"pairs p<{ALPHA} |", "|---|---|---|---|---|"]
    for basis in ("canon", "mad"):
        kw = dict(question="Q3_recipe_stability", map_basis=basis,
                  subject="all-cross-pairs")
        m = t.one(**kw, statistic="spearman_mean")
        if m is None or m["value"] in (MISSING, ""):
            continue
        ps = t.nums(question="Q3_recipe_stability", map_basis=basis,
                    statistic="spearman_p_spatial")
        lines.append(
            f"| {basis} | {m['n']} | {fmt(float(m['value']))} | "
            f"{fmt(t.num(**kw, statistic='spearman_min'))} to "
            f"{fmt(t.num(**kw, statistic='spearman_max'))} | "
            f"{sum(1 for p in ps if p < ALPHA)}/{len(ps)} |")
    within = t.num(question="Q2_seed_stability", arch="vit_small",
                   recipe_actual="mixup", map_basis="canon",
                   variant="baseline", subject="all-pairs",
                   statistic="spearman_mean")
    lines += ["", f"Against a within-recipe mean of {fmt(within)}, the "
              "cross-recipe value lies largely inside its own spatial null. "
              "This is not evidence that the address transfers between "
              "recipes.", ""]

    # Q4
    lines += ["### 4. Does SAGA relocate it? No — it consolidates it. "
              "Registers does relocate it.", "",
              "Correlation against the same-provenance baseline map "
              "(1 = identical address, 0 = relocated), and the paired change "
              "in excess concentration and in mass:", "",
              "| cell | variant | n pairs | rho vs baseline | "
              f"pairs p<{ALPHA} | d excess Gini | d mean sinks/image |",
              "|---|---|---|---|---|---|---|"]
    for arch, rec in CELLS:
        for variant in ("saga", "registers"):
            kw = dict(question="Q4_relocation", arch=arch, recipe_actual=rec,
                      map_basis="canon", variant=variant)
            m = t.one(**kw, subject="paired", statistic="spearman_mean")
            if m is None or m["value"] in (MISSING, ""):
                continue
            ps = t.nums(**kw, statistic="spearman_p_spatial")
            lines.append(
                f"| {cell_label(arch, rec)} | {variant} | {m['n']} | "
                f"{fmt(float(m['value']))} | "
                f"{sum(1 for p in ps if p < ALPHA)}/{len(ps)} | "
                f"{fmt(t.num(**kw, subject='MEAN', comparator='baseline-matched', statistic='delta_gini_excess'))} | "
                f"{fmt(t.num(**kw, subject='MEAN', comparator='baseline-matched', statistic='delta_total_mass'))} |")
    lines += ["", "SAGA keeps the same positions while removing sinks and "
              "tightening what remains, in both mixup cells. Registers "
              "moves the pattern instead and de-concentrates it. Note the "
              "ViT-B registers row rests on one legacy repeat whose map is "
              "almost empty and is noise-flagged in the note.", ""]

    # Q5
    lines += ["### 5. Does the gate know the address? Only in ViT-S/mixup, "
              "and negatively.", "",
              "Each SAGA repeat's largest-|rho| gate layer against its "
              "matched baseline map, both threshold bases, with the "
              "Bonferroni-corrected p for the 12-layer argmax:", "",
              "| cell | repeat | basis | layer | rho | Bonferroni p | "
              "gate std at layer |", "|---|---|---|---|---|---|---|"]
    for arch, rec in CELLS:
        for basis in ("canon", "mad"):
            for (tag, layer, rho, p, bonf, o_l, o_r,
                 std) in gate_extremes(t, arch, rec, basis):
                if rho is None:
                    continue
                mark = "" if (bonf is not None and bonf < ALPHA) else " (n.s.)"
                lines.append(
                    f"| {cell_label(arch, rec)} | {tag} | {basis} | {layer} "
                    f"| {fmt(rho, 3)} | {fmt(bonf)}{mark} | "
                    f"{fmt(std, 5)} |")
    lines += ["", "ViT-S/mixup is unambiguous: every repeat picks layer 7 "
              "or 8, every rho is negative, in both bases, and all are "
              "significant after correction. The gate is suppressed exactly "
              "on the border ring where sinks form — visible directly in "
              "`results/figures/Faddr_draft.pdf`. ViT-B and ViT-S/nomix are "
              "undecided: nothing survives correction there, and the "
              "repeats disagree in sign between bases. Note the gate's "
              "absolute modulation is small (the `gate std` column) — a "
              "rank correlation is scale-free, so the pattern is "
              "systematic but shallow.", ""]


def section_evidence(t: Table, pooled, lines):
    counts = repeat_counts(t)
    lines += ["## What the evidence base actually is", "",
              "| cell | baseline | saga | registers |", "|---|---|---|---|"]
    for arch, rec in CELLS:
        lines.append(
            f"| {cell_label(arch, rec)} | "
            + " | ".join(str(counts[(arch, rec, v)]) for v in VARIANTS) + " |")
    delta = pooled_lookup(pooled, "vit_base", "mixup", "saga",
                          "paired_delta_mean")
    se = pooled_lookup(pooled, "vit_base", "mixup", "saga",
                       "paired_delta_se")
    sig = pooled_lookup(pooled, "vit_base", "mixup", "saga",
                        "significant_2xSE")
    s_delta = pooled_lookup(pooled, "vit_small", "mixup", "saga",
                            "paired_delta_mean")
    s_se = pooled_lookup(pooled, "vit_small", "mixup", "saga",
                         "paired_delta_se")
    lines += ["", "Repeat counts are the limiting factor, and they are "
              "uneven. Only ViT-S/mixup has four baseline repeats (6 pairs); "
              "ViT-B/mixup and ViT-S/nomix have two each (1 pair). Registers "
              "is legacy-only everywhere and absent from ViT-S/nomix — no "
              "registers run has yet gone through the seeded trainer, though "
              "its 2-epoch smoke passed.", "",
              "### The two optional runs, and what they would buy", "",
              "`e2r_vitb_mixup_baseline_s2` and `e2r_vitb_mixup_saga_s2` "
              "(ViT-B/16, mixup, seed 2, 300 epochs, ~29 h each on 4x A100) "
              "are prepared and unsubmitted. They address the ViT-B cell, "
              "which is the weakest part of this analysis, in four ways:",
              ""]
    if delta is not None:
        spread = pooled_deltas(pooled, "vit_base", "mixup", "saga")
        spread_txt = ", ".join(f"{tag} {v}" for tag, v in spread)
        lines.append(
            f"1. **Top-1 significance.** SAGA's ViT-B gain is "
            f"{delta} with SE {se} and `significant_2xSE = {sig}` — not "
            f"significant, because its two paired deltas disagree "
            f"({spread_txt}). With four repeats the ViT-S/mixup equivalent "
            f"is {s_delta} with SE {s_se} and IS significant. A third ViT-B "
            f"pair would settle it either way.")
    lines += [
        "2. **Seed-stability is confounded, not just thin.** ViT-B's one "
        "pair compares a LEGACY run (old trainer, no seed control) with a "
        "seeded one, so it mixes seed variation with a code-version change. "
        "`baseline_s2` would give the first clean same-code, different-seed "
        "pair at ViT-B.",
        "3. **The gate question at ViT-B is genuinely undecided** (Q5 "
        "above: nothing significant, and the two repeats differ in sign "
        "between bases). A third gate dump is the only way to break it.",
        "4. **Q4 would gain a third pair** — least urgent, that result is "
        "already solid.", "",
        "They do nothing for ViT-S, nothing for the true-nomix cell (also "
        "one pair), and nothing for registers, which needs its own prepared "
        "run `e2r_vitb_mixup_registers_s1`. Cost is real: ~58 h of 4x A100, "
        "competing with TASK-08 and TASK-09 for the queue. Nothing in TASK "
        "07 is blocked either way — the limitations are recorded in the "
        "note's OPEN ITEMS.", ""]


def section_artifacts(lines):
    lines += [
        "## Artifacts", "",
        "| file | what |", "|---|---|",
        "| `results/notes/sink_address.md` | the results note, generated; "
        "the five questions with full tables |",
        "| `results/tables/sink_address.csv` | every number, long format; "
        "each correlation row carries its p and null sd |",
        "| `results/figures/Faddr_draft.pdf` | per cell: 14x14 frequency "
        "maps (shared colorbar) + the extremal gate layer; plus an "
        "excess-concentration panel |",
        "| `results/figures_data/Faddr.npz` | the maps, gate maps and "
        "per-layer profiles the figure draws |",
        "| `results/legacy/diag/*_addr.json`, `results/runs/*/diag/"
        "diag_final_*_addr.json` | the 44 per-position maps from Phase B |",
        "| `tools/sink_address.py` | Phase-A tool: builds an `_addr.json` "
        "from a `_norms.npz` (runs on the HPC) |",
        "| `analysis/address_analysis.py` | Phase-C analysis |",
        "| `analysis/build_sink_address_note.py` | renders the note from "
        "the CSV |",
        "| `tests/test_task07_{sink_address,address_analysis}.py` | 53 "
        "tests, including a brute-force check of real files and a "
        "regression test pinning the corrected sign |", "",
        "### Regenerate everything locally (no GPU, no HPC)", "",
        "```bash",
        "python analysis/address_analysis.py",
        "python plotting/plot_address.py",
        "python analysis/build_sink_address_note.py",
        "python analysis/build_task07_handoff.py",
        "pytest -q",
        "```", "",
        "### Rebuild the Phase-B maps (HPC only — the `_norms.npz` are "
        "git-ignored and live there)", "",
        "```bash",
        "python tools/sink_address.py",
        "```", "",
        "It is idempotent and skips up-to-date files, so it is safe to "
        "re-run; expect `44 written` on a first pass and `44 skipped` "
        "afterwards.", "",
    ]


def section_provenance(lines):
    lines += [
        "## Provenance warnings for whoever picks this up", "",
        "- **Do not read numbers out of commit `efd4f9d` (\"Task 9\").** "
        "That commit contains only these seven TASK-07 Phase-C files: a "
        "repo-wide `git add` swept the work in progress under a Task-9 "
        "label. It is the PRE-REVIEW snapshot and its registers "
        "concentration numbers have the wrong sign. `17ccb2a` supersedes "
        "it.",
        "- **The TASK-07 commits are on `main`, not on a task branch.** "
        "CLAUDE.md gained a one-branch-per-task rule mid-task; by then two "
        "of these commits were already pushed. History was deliberately "
        "left alone because `main` is shared live with the TASK-08 and "
        "TASK-09 sessions, and switching or rewinding the branch in this "
        "one worktree would hijack their commits. The reconciliation is "
        "still the human's to choose.",
        "- **Three sessions shared this checkout**, which is what CLAUDE.md "
        "now forbids and what caused the sweep above. Parallel work needs "
        "`git worktree add`.",
        "- Diagnostics throughout come from the LAST checkpoint. "
        "`*_best_addr.json` files exist and are deliberately never read.",
        "- Cell membership is imported from "
        "`analysis/build_pooled_tables.py` rather than redefined, so the "
        "recipe erratum (legacy directory names are NOT recipes) and the "
        "exclusion of the VOID legacy ViT-B mixup-dir trio cannot drift "
        "between the two tables. A decoy test pins the exclusion.", "",
    ]


def build(rows, pooled, sha) -> str:
    t = Table(rows)
    lines = []
    section_status(lines, sha)
    section_method(lines)
    section_answers(t, lines)
    section_evidence(t, pooled, lines)
    section_artifacts(lines)
    section_provenance(lines)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Render the TASK-07 handoff.")
    parser.add_argument("--table", default="results/tables/sink_address.csv")
    parser.add_argument("--pooled", default="results/tables/e2_pooled.csv")
    parser.add_argument("--out", default="docs/TASK_07_HANDOFF.md")
    args = parser.parse_args()

    text = build(load(Path(args.table)), load(Path(args.pooled)), git_sha())
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
